### PR TITLE
Fix parse related functions return behavior in case of NULL input

### LINKED ISSUE #4380: [BUG] Grok/Parse/Patterns parse a null field should return an empty string with Calcite
**What is the bug?**
Grok parse a null field will return an empty string in v2, [ref](https://github.com/opensearch-project/sql/blob/main/docs/user/ppl/cmd/grok.rst#example-1-create-the-new-field). but it returns null in v3.

**How can one reproduce the bug?**
```
source=accounts | grok email '.+@%{HOSTNAME:host}' | fields email, host ;
    fetched rows / total rows = 4/4
    +-----------------------+------------+
    | email                 | host       |
    |-----------------------+------------|
    | amberduke@pyrami.com  | pyrami.com |
    | hattiebond@netagy.com | netagy.com |
    | null                  | null       |
    | daleadams@boink.com   | boink.com  |
    +-----------------------+------------+
```

```
source=accounts | parse email '.+@(?<host>.+)' | fields email, host ;
    fetched rows / total rows = 4/4
    +-----------------------+------------+
    | email                 | host       |
    |-----------------------+------------|
    | amberduke@pyrami.com  | pyrami.com |
    | hattiebond@netagy.com | netagy.com |
    | null                  | null       |
    | daleadams@boink.com   | boink.com  |
    +-----------------------+------------+
```

```
source=accounts | patterns email method=simple_pattern | fields email, patterns_field ;
    fetched rows / total rows = 4/4
    +-----------------------+----------------+
    | email                 | patterns_field |
    |-----------------------+----------------|
    | amberduke@pyrami.com  | @.             |
    | hattiebond@netagy.com | @.             |
    | null                  | null           |
    | daleadams@boink.com   | @.             |
    +-----------------------+----------------+
```

### PR DESCRIPTION
**Pull request by songkant-aws**
### Description
Fix the bug when input string is NULL, parse/grok/patterns(simple_pattern) returns NULL value instead of empty string. This is to align with V2 behaviors described in the docs. It will reduce breaking changes as well.

### Related Issues
Resolves #4380 

### Check List
- [x] New functionality includes testing.
- [ ] New functionality has been documented.
 - [ ] New functionality has javadoc added.
 - [ ] New functionality has a user manual doc added.
- [ ] New PPL command [checklist](https://github.com/opensearch-project/sql/blob/main/docs/dev/ppl-commands.md) all confirmed.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff` or `-s`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: core/src/main/java/org/opensearch/sql/utils/ParseUtils.java [hunk 1]
```diff
@@ -30,7 +30,7 @@ public class ParseUtils {
           ParseMethod.PATTERNS, PatternsExpression::new);
   public static final Map<ParseMethod, BuiltinFunctionName> BUILTIN_FUNCTION_MAP =
       ImmutableMap.of(
-          ParseMethod.REGEX, BuiltinFunctionName.INTERNAL_REGEXP_EXTRACT,
+          ParseMethod.REGEX, BuiltinFunctionName.INTERNAL_PARSE,
```
Comment (LantaoJin) [inline core/src/main/java/org/opensearch/sql/utils/ParseUtils.java:33]: q: `INTERNAL_REGEXP_EXTRACT` will never be used with the patch?

**Review by LantaoJin — DISMISSED** [review]

File: core/src/main/java/org/opensearch/sql/utils/ParseUtils.java (hunk 1 above)
Comment (songkant-aws) [reply core/src/main/java/org/opensearch/sql/utils/ParseUtils.java:33]: Yes, it's not used anymore. Will quickly remove it.

**Comment by LantaoJin** [comment]
Will the patch change the behavior of `rex` command?

**Comment by songkant-aws** [comment]
> Will the patch change the behavior of rex command?

@LantaoJin No, `rex` command uses its own UDFs and couple of other Calcite internal functions. Its logic is more complex.

**Review by LantaoJin — APPROVED** [review]

**Comment by LantaoJin** [comment]
Need to backport manually @songkant-aws
