### PR TITLE
Eliminate reliance on assert in Calcite for integration test

### LINKED ISSUE #3896: [AUTOCUT] Integration Test Failed for sql-3.2.0
#### Details

| Platform | Dist | Arch | Dist Build No. | RC | Test Report | Workflow Run | Failing tests |
|----------|------|------|----------------|----|-------------|--------------|---------------|
| linux | tar | arm64 | 11257 | 0 | https://ci.opensearch.org/ci/dbc/integ-test/3.2.0/11257/linux/arm64/tar/test-results/10131/integ-test/test-report.yml | https://build.ci.opensearch.org/job/integ-test/10131/display/redirect | [Check metrics](https://metrics.opensearch.org/_dashboards/app/dashboards?security_tenant=global#/view/21aad140-49f6-11ef-bbdd-39a9b324a5aa?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-30d,to:now))&_a=(description:'OpenSearch%20Release%20Build%20and%20Integration%20Test%20Results',expandedPanelId:c570bdfd-3122-4e31-a02d-2130d797d9fc,filters:!(('':(store:appState),meta:(alias:!n,disabled:!f,index:d90d2ba0-8fe0-11ef-a168-f19b1bbc360c,key:version,negate:!f,params:(query:'3.2.0'),type:phrase),query:(match_phrase:(version:'3.2.0'))),('':(store:appState),meta:(alias:!n,disabled:!f,index:d90d2ba0-8fe0-11ef-a168-f19b1bbc360c,key:component,negate:!f,params:(query:sql),type:phrase),query:(match_phrase:(component:sql)))),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'OpenSearch%20Release%20Build%20and%20Integration%20Test%20Results',viewMode:view)) |
| linux | tar | x64 | 11257 | 0 | https://ci.opensearch.org/ci/dbc/integ-test/3.2.0/11257/linux/x64/tar/test-results/10132/integ-test/test-report.yml | https://build.ci.opensearch.org/job/integ-test/10132/display/redirect | [Check metrics](https://metrics.opensearch.org/_dashboards/app/dashboards?security_tenant=global#/view/21aad140-49f6-11ef-bbdd-39a9b324a5aa?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-30d,to:now))&_a=(description:'OpenSearch%20Release%20Build%20and%20Integration%20Test%20Results',expandedPanelId:ddafb9c5-2d35-482a-9c61-1ba78b67f406,filters:!(('':(store:appState),meta:(alias:!n,disabled:!f,index:d90d2ba0-8fe0-11ef-a168-f19b1bbc360c,key:version,negate:!f,params:(query:'3.2.0'),type:phrase),query:(match_phrase:(version:'3.2.0'))),('':(store:appState),meta:(alias:!n,disabled:!f,index:d90d2ba0-8fe0-11ef-a168-f19b1bbc360c,key:component,negate:!f,params:(query:sql),type:phrase),query:(match_phrase:(component:sql)))),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'OpenSearch%20Release%20Build%20and%20Integration%20Test%20Results',viewMode:view)) |

Check out test report manifest linked above for steps to reproduce, cluster and integration test failure logs. For additional information checkout the [wiki](https://github.com/opensearch-project/opensearch-build/wiki/Testing-the-Distribution) and [OpenSearch Metrics Dashboard](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/21aad140-49f6-11ef-bbdd-39a9b324a5aa).

### PR DESCRIPTION
**Pull request by yuancu**
### Description

Previously, the test `failWhenNumOfColumnsNotMatchOutputOfSubquery` relied on `assert` for integration test. However, assert is ignored in production in Java by default. This PR address the problem by eliminating the reliance on `assert` in the test.

Additionally, this PR enfores `script.disable_max_compilations_rate increases` to `true` for SQL & PPL integration tests, and set `script.context.*.max_compilations_rate` to `unlimited` as fallback .

### Related Issues
Resolves #3896 

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
 - [ ] New functionality has javadoc added.
 - [ ] New functionality has a user manual doc added.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff`.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: common/src/main/java/org/opensearch/sql/common/setting/Settings.java [hunk 1]
```diff
@@ -61,6 +61,9 @@ public enum Key {
     SESSION_INACTIVITY_TIMEOUT_MILLIS(
         "plugins.query.executionengine.spark.session_inactivity_timeout_millis"),
 
+    SCRIPT_DISABLE_MAX_COMPILATIONS_RATE("script.disable_max_compilations_rate"),
+    SCRIPT_CONTEXT_MAX_COMPILATIONS_RATE_PATTERN("script.context.*.max_compilations_rate"),
```
Comment (LantaoJin) [inline common/src/main/java/org/opensearch/sql/common/setting/Settings.java]: No need to add these config keys if they are used only for IT.

File: integ-test/src/test/java/org/opensearch/sql/legacy/OpenSearchSQLRestTestCase.java [hunk 2]
```diff
@@ -301,4 +320,92 @@ public void configureMultiClusters(String remote) throws IOException {
...
+    // set
+    if (!Objects.equals(
+        getClusterSetting(
+            ScriptService.SCRIPT_DISABLE_MAX_COMPILATIONS_RATE_SETTING.getKey(), "persistent"),
+        "true")) {
+      List<String> contexts = getScriptContexts();
+      for (String context : contexts) {
+        String contextCompilationsRate =
+            SCRIPT_CONTEXT_MAX_COMPILATIONS_RATE_PATTERN.replace("*", context);
+        updateClusterSetting(contextCompilationsRate, "unlimited", true);
```
Comment (dai-chen) [inline integ-test/src/test/java/org/opensearch/sql/legacy/OpenSearchSQLRestTestCase.java:343]: Just wonder what's the difference between this setting and `script.max_compilations_rate`?

**Review by Swiddis — APPROVED** [review]

File: integ-test/src/test/java/org/opensearch/sql/legacy/OpenSearchSQLRestTestCase.java (hunk 2 above)
Comment (yuancu) [reply integ-test/src/test/java/org/opensearch/sql/legacy/OpenSearchSQLRestTestCase.java:343]: `script.max_compilations_rate` is deprecated.

File: common/src/main/java/org/opensearch/sql/common/setting/Settings.java (hunk 1 above)
Comment (yuancu) [reply common/src/main/java/org/opensearch/sql/common/setting/Settings.java]: Removed from settings.
