### PR TITLE
[BugFix] Fix PushDownContext shallow copy bug

### LINKED ISSUE #5125: Reverse Optimization fails when creating consecutive sorts due to Calcite physical optimizer merging
## Description

The `reverse` command's sort-collation-reversal optimization does not work correctly when the reversed sort is placed directly on top of the original sort with no intermediate operator between them. Calcite's physical optimizer merges (or eliminates) consecutive `LogicalSort` nodes, causing the reversed direction to be lost.

Related PR: #4775 

## Root Cause

The `reverse` optimization in `CalciteRelNodeVisitor.visitReverse()` detects an existing sort collation and creates a new `LogicalSort` with the reversed direction on top of the original sort. This produces a plan like:

```
LogicalSort(sort0=[$1], dir0=[DESC])      <-- reverse adds this
  LogicalSort(sort0=[$1], dir0=[ASC])     <-- original sort
    ...
```

While this logical plan is correct, Calcite's physical optimizer (e.g., `SortRemoveRule`) recognizes that two consecutive sorts on the same field are redundant and merges them — but it keeps the **original** (lower) sort direction instead of the **top-level** (reversed) one, effectively making the `reverse` a no-op.

## When It Works vs. When It Fails

**Works** — when there is an intermediate operator (filter, project, eval) between the original sort and the reversed sort. The intermediate operator prevents Calcite from merging the two sorts:

```
-- WORKS: sort -> fields (project) -> reverse
source=accounts | sort account_number | fields account_number | reverse

Logical plan:
  LogicalSort(sort0=[$0], dir0=[DESC])     <-- reversed sort
    LogicalProject(account_number=[$0])    <-- intermediate operator prevents merging
      LogicalSort(sort0=[$0], dir0=[ASC])
        LogicalTableScan
```

```
-- WORKS: sort -> where (filter) -> reverse
source=accounts | sort account_number | where balance > 30000 | reverse

Logical plan:
  LogicalSort(sort0=[$0], dir0=[DESC])
    LogicalFilter(condition=[>($4, 30000)])  <-- intermediate operator prevents merging
      LogicalSort(sort0=[$0], dir0=[ASC])
        LogicalTableScan
```

**Fails** — when the reversed sort sits directly on top of the original sort with no intermediate operator:

```
-- FAILS: stats -> sort -> reverse (two consecutive sorts, no operator between them)
source=accounts | stats count() as c by gender | sort gender | reverse

Logical plan:
  LogicalSort(sort0=[$1], dir0=[DESC])     <-- reversed sort
    LogicalSort(sort0=[$1], dir0=[ASC])    <-- original sort (nothing between them)
      LogicalProject(c=[$1], gender=[$0])
        LogicalAggregate(...)

Expected: M, F (descending)
Actual:   F, M (ascending — reverse was ignored)
```

```
-- FAILS: timechart -> reverse (timechart adds a sort, reverse adds another directly on top)
source=events | timechart span=1m count() | reverse

Logical plan:
  LogicalSort(sort0=[$0], dir0=[DESC])     <-- reversed sort
    LogicalSort(sort0=[$0], dir0=[ASC])    <-- timechart's sort (nothing between them)
      LogicalAggregate(...)

Expected: 00:04, 00:03, 00:02, 00:01, 00:00 (descending)
Actual:   00:00, 00:01, 00:02, 00:03, 00:04 (ascending — reverse was ignored)
```

## Affected Scenarios

| Query Pattern | Why It Fails |
|---|---|
| `stats ... \| sort field \| reverse` | Sort after aggregation + reverse = consecutive sorts |
| `timechart ... \| reverse` | Timechart's built-in sort + reverse = consecutive sorts |
| `timechart timefield=X ... \| reverse` | Same as above with custom time field |
| `timechart ... by field \| reverse` | Same as above with group-by |

## Expected Behavior

`reverse` should always flip the sort direction, regardless of whether the reversed sort is directly adjacent to the original sort.

## Suggested Fix

Instead of creating a **new** sort on top of the existing sort, modify the **existing** sort node in-place to flip its direction. This avoids creating consecutive sorts entirely. For example:

```java
// Instead of:
context.relBuilder.sort(reversedCollation);  // adds a NEW sort on top

// Consider replacing the existing sort:
RelNode currentNode = context.relBuilder.build();  // pop current
// Replace the top-level Sort with one that has reversed collation
RelNode modifiedSort = LogicalSort.create(
    ((Sort) currentNode).getInput(),  // keep the sort's child
    reversedCollation,                // use reversed direction
    ((Sort) currentNode).offset,
    ((Sort) currentNode).fetch);
context.relBuilder.push(modifiedSort);
```

This would produce a single sort node with the correct (reversed) direction, eliminating the problem entirely.

## Tests

The following integration tests in `CalciteReverseCommandIT` are affected and currently use `verifyDataRows` (unordered) as a workaround:

- `testReverseAfterAggregationWithSort`
- `testTimechartWithReverse`
- `testTimechartWithCustomTimefieldAndReverse`
- `testTimechartWithGroupByAndReverse`

The corresponding unit tests in `CalcitePPLReverseTest` verify the logical plan is correct — the issue is only in physical execution.

### PR DESCRIPTION
**Pull request by songkant-aws**
### Description
PushdownContext.clone() / cloneWithoutSort() / cloneForAggregate() replays add(operation) to construct new context. Aggregation operations reuses the same `AggPushDownAction` instance in both old and new context due to shallow copy side effect happened during cloning PushdownContext. The following pushdown actions from other equivalent RelSubsets will modify this shared mutable action object, which could contaminate previous context's agg states.

### Related Issues
Resolves #5125 

### Check List
- [x] New functionality includes testing.
- [ ] New functionality has been documented.
 - [ ] New functionality has javadoc added.
 - [ ] New functionality has a user manual doc added.
- [ ] New PPL command [checklist](https://github.com/opensearch-project/sql/blob/main/docs/dev/ppl-commands.md) all confirmed.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff` or `-s`.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by LantaoJin** [comment]
cc @qianheng-aws as proper reviewer

File: opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/context/AggPushDownAction.java [hunk 1]
```diff
@@ -64,6 +66,156 @@ public AggPushDownAction(
...
+    if (builder instanceof HistogramAggregationBuilder histogram) {
+      return copyHistogramAggregationBuilder(histogram);
+    }
+    if (builder instanceof TopHitsAggregationBuilder topHits) {
+      return copyTopHitsAggregationBuilder(topHits);
+    }
+    if (builder instanceof NestedAggregationBuilder nested) {
+      return copyNestedAggregationBuilder(nested);
+    }
+    return builder;
```
Comment (qianheng-aws) [inline opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/context/AggPushDownAction.java]: What if there is other missed or upcoming agg builder?

File: opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/context/AggPushDownAction.java [hunk 2]
```diff
@@ -64,6 +66,156 @@ public AggPushDownAction(
...
+    return metadata == null || metadata.isEmpty() ? null : metadata;
+  }
+
+  private static final class CompositeAggregationBuilderCopy extends CompositeAggregationBuilder {
+    private CompositeAggregationBuilderCopy(CompositeAggregationBuilder source) {
+      super(source, copySubAggregations(source), copyMetadataOrNull(source));
+    }
+  }
+
+  private static final class TermsAggregationBuilderCopy extends TermsAggregationBuilder {
```
Comment (qianheng-aws) [inline opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/context/AggPushDownAction.java]: Can this be replaced with 
```
source.shallowCopy(source, copySubAggregations(source), copyMetadataOrNull(source))
```
instead of defining these extended class?

**Review by qianheng-aws — COMMENTED** [review]
Have you ever tried lazy push-down for `AggregationBuilderAction`? If that approach can work, we don't need to create AggregationBuilder in the planning phase, neither need to do deep copy for AggregationBuilder then.

**Comment by songkant-aws** [comment]
@qianheng-aws Now the fix is changed to lazily push down agg request at the createRequest phase. But it introduces some intermediate immutable spec object to record any logical pushdown operations. It touches more logic now but I think it could mitigate the current problem of AggPushDownAction's mutation during planning.

File: opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/context/AggSpec.java [hunk 3]
```diff
@@ -0,0 +1,520 @@
...
+  private static LimitPushdownMode inferLimitPushdownMode(AggKind kind) {
+    return switch (kind) {
+      case COMPOSITE, TERMS, MULTI_TERMS, TOP_HITS, RARE_TOP -> LimitPushdownMode.BUCKET_SIZE;
+      case OTHER, DATE_HISTOGRAM, HISTOGRAM -> LimitPushdownMode.UNSUPPORTED;
+    };
+  }
+
+  private static LimitPushdownMode inferLimitPushdownMode(
+      List<AggregationBuilder> builders, @Nullable AggregationBuilder rootBuilder) {
+    if (builders.isEmpty()) {
```
Comment (qianheng-aws) [inline opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/context/AggSpec.java]: Nit: seems no need to pass in param `builders` here. This can be replaced with rootBuilder==null.

File: opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/context/AggSpec.java [hunk 4]
```diff
@@ -0,0 +1,520 @@
...
+      // count() optimization uses hits.total and leaves the builder list empty. Keeps
+      // LIMIT in PushDownContext for these cases even though no request-side limit is applied.
+      return LimitPushdownMode.ESTIMATE_ONLY;
+    }
+    AggregationBuilder builder = unwrapNestedBuilder(rootBuilder);
+    if (builder instanceof ValuesSourceAggregationBuilder.LeafOnly<?, ?>) {
+      // Treats leaf metric aggregations as limit-pushable because they produce a single row.
+      return LimitPushdownMode.LEAF_METRIC;
+    }
+    return inferLimitPushdownMode(inferKind(rootBuilder));
```
Comment (qianheng-aws) [inline opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/context/AggSpec.java]: Nit: pass in `kind` to avoid calling inferKind method here, it's already evaluated before calling `inferLimitPushdownMode`.

File: opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/context/AggSpec.java [hunk 5]
```diff
@@ -0,0 +1,520 @@
...
+        outputFields,
+        rowType,
+        fieldTypes,
+        cluster,
+        bucketNullable,
+        queryBucketSize,
+        extendedTypeMapping,
+        bucketNames,
+        bucketNames,
+        new AggPushDownAction(builderAndParser, extendedTypeMapping, bucketNames).getScriptCount(),
```
Comment (qianheng-aws) [inline opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/context/AggSpec.java]: It's weird to new a AggPushDownAction here only to get the script count. Replace it with builderAndParser.getLeft().stream().mapToInt(AggPushDownAction::getScriptCount).sum()

File: opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/context/AggSpec.java [hunk 6]
```diff
@@ -0,0 +1,520 @@
...
+        fieldTypes,
+        cluster,
+        bucketNullable,
+        queryBucketSize,
+        extendedTypeMapping,
+        initialBucketNames,
+        bucketNames,
+        scriptCount,
+        measureSortTarget,
+        inferLimitPushdownMode(measureSortTarget),
```
Comment (qianheng-aws) [inline opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/context/AggSpec.java]: Why invoking infer again while measureSortTarget is unchanged here?

File: opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/context/AggSpec.java [hunk 7]
```diff
@@ -0,0 +1,520 @@
...
+        rareTopDigest,
+        size);
+  }
+
+  public Pair<List<AggregationBuilder>, OpenSearchAggregationResponseParser> build() {
+    try {
+      AggregateAnalyzer.AggregateBuilderHelper helper =
+          new AggregateAnalyzer.AggregateBuilderHelper(
+              rowType, fieldTypes, cluster, bucketNullable, queryBucketSize);
+      Pair<List<AggregationBuilder>, OpenSearchAggregationResponseParser> builderAndParser =
```
Comment (qianheng-aws) [inline opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/context/AggSpec.java]: Why should we analyze the `aggregate` again? Can we reuse the `builderAndParser` generated when pushing down the `aggregate`? Even more, we may be able to reuse the `AggPushDownAction`.

Since we pushdown everything lazily until this build() method, which will only be invoked once. It should be safe to reuse.

**Review by qianheng-aws — COMMENTED** [review]
As commented here:https://github.com/opensearch-project/sql/pull/5199/changes#r2980342004, if the `AggPushDownAction` can be reusable, plenty of params can be removed, which are maintained all the way but only for creating `AggPushDownAction` in the end in `build()` method.

**Comment by qianheng-aws** [comment]
> As commented here:https://github.com/opensearch-project/sql/pull/5199/changes#r2980342004, if the `AggPushDownAction` can be reusable, plenty of params can be removed, which are maintained all the way but only for creating `AggPushDownAction` in the end in `build()` method.

As far as I can see, only these params are getting changed in the push down process for agg.
```
bucketNames, kind, limitPushdownMode, bucketSortCollations, bucketSortFieldNames, digest, bucketSize
```

File: opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/context/AggSpec.java (hunk 3 above)
Comment (songkant-aws) [reply opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/context/AggSpec.java]: Yes, replace it with `rootBuilder == null` check now.

File: opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/context/AggSpec.java (hunk 4 above)
Comment (songkant-aws) [reply opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/context/AggSpec.java]: Done

File: opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/context/AggSpec.java (hunk 5 above)
Comment (songkant-aws) [reply opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/context/AggSpec.java]: Done. It's now calling getScriptCount instead

File: opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/context/AggSpec.java (hunk 6 above)
Comment (songkant-aws) [reply opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/context/AggSpec.java]: This was incorrect. Now it will infer rewriteTarget in local method and based on rewritten AggKind to inferLimitPushdownMode again.

File: opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/context/AggSpec.java (hunk 7 above)
Comment (songkant-aws) [reply opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/context/AggSpec.java]: As discussed offline. Ideally if we don't care about afterKey rewrite in agg pagination, then the `builderAndParser` can be reusable. I change the behavior to reuse passed builderAndParser to AggSpec.

However, I reviewed the whole process. I still think we still need AggSpec like object to hold planning stage agg state immutable copies(can't fully AggPushDownAction). AggPushDownAction is used at the final materialization of replayed PushDownOperations for agg. It will be better to separate them into two different objects. During optimizer planning stage, we still need to record some agg state changes in different RelSubsets. One for planning side agg state immutable objects, the other one is for replaying final operations to materialize final AggregationBuilder(lazily generate request builder).

**Comment by songkant-aws** [comment]
@qianheng-aws Now I have streamlined the AggSpec. And choose not to reuse AggPushDownAction because we need several immutable objects copies in different RelSubsets to represent different logical agg states per RelSubset. However, replaying pushdown operations to change internal agg parser is a one-time mutable state change, which is better lazily built at last.

**Review by qianheng-aws — APPROVED** [review]

**Review by LantaoJin — APPROVED** [review]
