### PR TITLE
Fix flaky TPC-H Q1 test due to bugs in `MatcherUtils.closeTo()`

### LINKED ISSUE #5282: [BUG][Test] Flaky `CalcitePPLTpchIT` on Linux arm64 when pushdown enabled
**What is the bug?**
When pushdown enabled, the aggregation result depends on OpenSearch DSL. We found the testQ1 could flaky on different platform:

> Suite: Test class org.opensearch.sql.calcite.tpch.CalcitePPLTpchIT
> 
>   2> REPRODUCE WITH: ./gradlew ':integ-test:integTest' --tests 'org.opensearch.sql.calcite.tpch.CalcitePPLTpchIT.testQ1' -Dtests.seed=5AD3AA18D9879132 -Dtests.security.manager=false -Dtests.locale=ksf-CM -Dtests.timezone=Brazil/DeNoronha -Druntime.java=25 -Djava.security.properties=/tmp/tmphfxkwakx/sql/distribution/src/config/fips_java.security
> 
>   2> java.lang.AssertionError: 
> 
>     Expected: iterable with items [[A, F, 37474, 3.756962464E7, 3.5676192097E7, 3.7101416222424E7, 25.354533152909337, 25419.231826792962, 0.0508660351826793, 1478], [N, F, 1041, 1041301.07, 999060.898, 1036450.8022800001, 27.394736842105264, 27402.659736842103, 0.04289473684210526, 38], [N, O, 75168, 7.538495537E7, 7.16531663034E7, 7.4498798133073E7, 25.558653519211152, 25632.42277116627, 0.049697381842910573, 2941], [R, F, 36511, 3.657084124E7, 3.47384728758E7, 3.6169060112193E7, 25.059025394646532, 25100.09693891558, 0.05002745367192862, 1457]] in any order
> 
>          but: not matched: <["A","F",37474,37569624.64,35676192.096999995,37101416.222424,25.354533152909337,25419.231826792962,0.0508660351826793,1478]>
> 
> 
> Suite: Test class org.opensearch.sql.calcite.tpch.CalcitePPLTpchPaginatingIT
> 
>   2> REPRODUCE WITH: ./gradlew ':integ-test:integTest' --tests 'org.opensearch.sql.calcite.tpch.CalcitePPLTpchPaginatingIT.testQ1' -Dtests.seed=5AD3AA18D9879132 -Dtests.security.manager=false -Dtests.locale=ff-Latn-MR -Dtests.timezone=America/Argentina/Tucuman -Druntime.java=25 -Djava.security.properties=/tmp/tmphfxkwakx/sql/distribution/src/config/fips_java.security
> 
>   2> java.lang.AssertionError: 
> 
>     Expected: iterable with items [[A, F, 37474, 3.756962464E7, 3.5676192097E7, 3.7101416222424E7, 25.354533152909337, 25419.231826792962, 0.0508660351826793, 1478], [N, F, 1041, 1041301.07, 999060.898, 1036450.8022800001, 27.394736842105264, 27402.659736842103, 0.04289473684210526, 38], [N, O, 75168, 7.538495537E7, 7.16531663034E7, 7.4498798133073E7, 25.558653519211152, 25632.42277116627, 0.049697381842910573, 2941], [R, F, 36511, 3.657084124E7, 3.47384728758E7, 3.6169060112193E7, 25.059025394646532, 25100.09693891558, 0.05002745367192862, 1457]] in any order
> 
>          but: not matched: <["N","F",1041,1041301.0700000001,999060.8979999999,1036450.8022800001,27.394736842105264,27402.659736842106,0.04289473684210526,38]>

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - OS: Linux ARM65
 - Version 3.6.0
 - Plugins SQL

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

### PR DESCRIPTION
**Pull request by LantaoJin**
### Description
Fixes intermittent failures in `CalcitePPLTpchIT.testQ1` and `CalcitePPLTpchPaginatingIT.testQ1` caused by two bugs in  `MatcherUtils.closeTo()`:

1. **Incorrect element pairing via indexOf**: The old code used `actualValues.indexOf(v)` to find each element's position, then looked up the corresponding expected value. `indexOf` returns the index of the first occurrence matching via `equals()`, so duplicate values would silently compare against the wrong expected element. This also meant no size mismatch was ever detected.
2. **Made `closeTo()` ULP-aware** to handle floating-point precision differences.

### Related Issues
Resolves #5282

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
 - [ ] New functionality has javadoc added.
 - [ ] New functionality has a user manual doc added.
- [ ] New PPL command [checklist](https://github.com/opensearch-project/sql/blob/main/docs/dev/ppl-commands.md) all confirmed.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff` or `-s`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: integ-test/src/test/java/org/opensearch/sql/calcite/tpch/CalcitePPLTpchIT.java [hunk 1]
```diff
@@ -62,7 +56,9 @@ public void testQ1() throws IOException {
             "F",
             37474,
             isPushdownDisabled() ? 37569624.63999998 : 37569624.64,
-            isPushdownDisabled() ? 35676192.096999995 : 35676192.097,
+            isPushdownDisabled()
+                ? 35676192.096999995
+                : approx(35676192.097, 1e-6), // workaround for arm64
```
Comment (songkant-aws) [inline integ-test/src/test/java/org/opensearch/sql/calcite/tpch/CalcitePPLTpchIT.java]: The `approx(35676192.097, 1e-6)` change in `CalcitePPLTpchIT.testQ1()` looks too targeted for `#5282`. The issue shows at least two observed arm64 failures in IEEE-754 double standard:
- `35676192.096999995` vs `35676192.097` in CalcitePPLTpchIT.testQ1()
- `1041301.0700000001` vs `1041301.07` (and also `999060.8979999999` vs `999060.898`) in CalcitePPLTpchPaginatingIT.testQ1()

Would it make sense to change the default numeric comparison in `closeTo()` to something ULP-aware instead of hardcoding a single absolute threshold? For example, something along the lines of:

`abs(actual - expected) <= max(1e-10, k * max(Math.ulp(actual), Math.ulp(expected)))`, we could start with k = 4, aka 4 ULP error tolerance. Though the failed case has around 1 ULP error, we'd better set a conservative threshold.

Comment (LantaoJin) [reply integ-test/src/test/java/org/opensearch/sql/calcite/tpch/CalcitePPLTpchIT.java]: addressed.
