### PR TITLE
Byte number should treated as Long in doc values

### LINKED ISSUE #3927: [BUG] Script pushdown cannot handle byte type
**What is the bug?**
`source=test002 | eval a = abs(byte_number) | stats count() by a` failed.

### PR DESCRIPTION
**Pull request by LantaoJin**
### Description
` | eval a = abs(byte_number) | stats count() by a ` failed with
```
Caused by: java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Byte (java.lang.Long and java.lang.Byte are in module java.base of loader 'bootstrap')
        at Reducer.apply(Unknown Source) ~[?:?]
        at Reducer.apply(Unknown Source) ~[?:?]
        at org.opensearch.sql.opensearch.storage.script.core.CalciteScript.lambda$execute$0(CalciteScript.java:45) ~[?:?]
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:319) ~[?:?]
        at org.opensearch.sql.opensearch.storage.script.core.CalciteScript.execute(CalciteScript.java:43) ~[?:?]
        at org.opensearch.sql.opensearch.storage.script.aggregation.CalciteAggregationScript.execute(CalciteAggregationScript.java:50) ~[?:?]
```
### Related Issues
Resolves #3927 

### Check List
- [x] New functionality includes testing.
- [ ] New functionality has been documented.
 - [ ] New functionality has javadoc added.
 - [ ] New functionality has a user manual doc added.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/CalciteScriptEngine.java [hunk 1]
```diff
@@ -206,7 +207,7 @@ public org.apache.calcite.linq4j.tree.Expression field(
      */
     private Expression tryConvertDocValue(Expression docValueExpr, ExprType exprType) {
       return switch (exprType) {
-        case INTEGER, SHORT -> EnumUtils.convert(docValueExpr, Long.class);
+        case INTEGER, SHORT, BYTE -> EnumUtils.convert(docValueExpr, Long.class);
```
Comment (LantaoJin) [inline opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/CalciteScriptEngine.java:210]: this is the code change to fix the bug. The rests are protected programming which is not related to this bug.

**Review by penghuo — APPROVED** [review]
