### PR TITLE
Return comparable LinkedHashMap in `valueForCalcite()` of ExprTupleValue

### LINKED ISSUE #4339: [BUG] dedup raise 500 error when object attribute is specified
**What is the bug?**
`dedup` command raise 500 error when object attribute is specified.
Sample query:
```
source=logs-* | head 10 | dedup attributes
```
where attributes is struct like:
```
      {
        "cluster": {
          "name": "xyz-cluster1-ci-prod-us-east-1",
          "region": "us-east-1",
          "env": "prod"
        },
        "log": {
          "file": {
            "path": "/var/log/xyz/abc.log"
          }
        },
        "obs_body_length": 146
      },
```

error:
```
{
  "error": {
    "reason": "There was internal problem at backend",
    "details": "java.sql.SQLException: exception while executing query: class java.util.LinkedHashMap cannot be cast to class java.lang.Comparable (java.util.LinkedHashMap and java.lang.Comparable are in module java.base of loader 'bootstrap')",
    "type": "RuntimeException"
  },
  "status": 500
}
```

**How can one reproduce the bug?**
run ppl query: `source=logs-* | head 10 | dedup attributes`

**What is the expected behavior?**
It should return invalid query error with 4xx status code.

**What is your host/environment?**
 - Version [e.g. 22] 3.1
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

### PR DESCRIPTION
**Pull request by LantaoJin**
### Description
Fix `class java.util.LinkedHashMap cannot be cast to class java.lang.Comparable` in `dedup` struct field

### Related Issues
Resolves #4339

### Check List
- [x] New functionality includes testing.
- [ ] New functionality has been documented.
 - [ ] New functionality has javadoc added.
 - [ ] New functionality has a user manual doc added.
- [ ] New PPL command [checklist](https://github.com/opensearch-project/sql/blob/main/docs/dev/ppl-commands.md) all confirmed.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff` or `-s`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: core/src/main/java/org/opensearch/sql/data/utils/ComparableLinkedHashMap.java [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+      return -1;
+    }
+    if (other.isEmpty()) {
+      return 1;
+    }
+
+    V thisFirstValue = this.values().iterator().next();
+    V otherFirstValue = other.values().iterator().next();
+
+    if (thisFirstValue instanceof Comparable) {
```
Comment (qianheng-aws) [inline core/src/main/java/org/opensearch/sql/data/utils/ComparableLinkedHashMap.java]: Only comparing the first element?

Comment (LantaoJin) [reply core/src/main/java/org/opensearch/sql/data/utils/ComparableLinkedHashMap.java]: changed to compare recursively

File: core/src/test/java/org/opensearch/sql/utils/ComparableLinkedHashMapTest.java [hunk 2]
```diff
@@ -0,0 +1,258 @@
...
+    map1.put("a", 1);
+    map1.put("b", 2);
+
+    ComparableLinkedHashMap<String, Integer> map2 = new ComparableLinkedHashMap<>();
+    map2.put("c", 3);
+    map2.put("d", 2);
+
+    assertTrue(map1.compareTo(map2) < 0);
+    assertTrue(map2.compareTo(map1) > 0);
+  }
```
Comment (yuancu) [inline core/src/test/java/org/opensearch/sql/utils/ComparableLinkedHashMapTest.java:62]: Can the keys of ExprTupleValues be ignored? Or are they guaranteed to come with the same order?

**Review by qianheng-aws — APPROVED** [review]

**Comment by LantaoJin** [comment]
@qianheng-aws I filed a followup [PR](https://github.com/opensearch-project/sql/pull/4648). The current ComparableLinkedHashMap only compares the values. Change it to compare key than value.
