### PR TITLE
Fix bug that `Streamstats` command incorrectly treats null as a valid group

### LINKED ISSUE #4751: [BUG] Streamstats command incorrectly treats null as a valid group
**What is the bug?**
When using the `streamstats by <field>` clause, the current implementation treats `null` values as a valid group key and computes separate statistics for them. Which is not consistent with the expected behavior.

**How can one reproduce the bug?**
1. Set data:

```
PUT stream_test_null
{
  "mappings": {
    "properties": {
      "name": {
        "type": "keyword"
      },
      "age": {
        "type": "integer"
      },
      "state": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      },
      "country": {
        "type": "text"
      },
      "year": {
        "type": "integer"
      },
      "month": {
        "type": "integer"
      }
    }
  }
}
```
```
POST stream_test_null/_bulk?refresh=true
{"index":{"_id":"1"}}
{"name":"Jake","age":70,"state":"California","country":"USA","year":2023,"month":4}
{"index":{"_id":"2"}}
{"name":"Hello","age":30,"state":"New York","country":"USA","year":2023,"month":4}
{"index":{"_id":"3"}}
{"name":"John","age":25,"state":"Ontario","country":"Canada","year":2023,"month":4}
{"index":{"_id":"4"}}
{"name":"Jane","age":20,"state":"Quebec","country":"Canada","year":2023,"month":4}
{"index":{"_id":"5"}}
{"name":null,"age":10,"state":null,"country":"Canada","year":2023,"month":4}
{"index":{"_id":"6"}}
{"name":"Kevin","year":2023,"month":4}
```

2. Run this query

```
POST _plugins/_ppl
{
  "query": """
  source=stream_test_null | streamstats avg(age) as avg_age by state
  """
}
```

3. See error

```
{
  "schema": [
    {
      "name": "name",
      "type": "string"
    },
    {
      "name": "country",
      "type": "string"
    },
    {
      "name": "state",
      "type": "string"
    },
    {
      "name": "month",
      "type": "int"
    },
    {
      "name": "year",
      "type": "int"
    },
    {
      "name": "age",
      "type": "int"
    },
    {
      "name": "avg_age",
      "type": "double"
    }
  ],
  "datarows": [
    [
      "Jake",
      "USA",
      "California",
      4,
      2023,
      70,
      70
    ],
    [
      "Hello",
      "USA",
      "New York",
      4,
      2023,
      30,
      30
    ],
    [
      "John",
      "Canada",
      "Ontario",
      4,
      2023,
      25,
      25
    ],
    [
      "Jane",
      "Canada",
      "Quebec",
      4,
      2023,
      20,
      20
    ],
    [
      null,
      "Canada",
      null,
      4,
      2023,
      10,
      10
    ],
    [
      "Kevin",
      null,
      null,
      4,
      2023,
      null,
      10
    ]
  ],
  "total": 6,
  "size": 6
}
```
The two `null` value for state are incorrectly considered in one valid group.

**What is the expected behavior?**

```
"datarows": [
    [
      "Jake",
      "USA",
      "California",
      4,
      2023,
      70,
      70
    ],
    [
      "Hello",
      "USA",
      "New York",
      4,
      2023,
      30,
      30
    ],
    [
      "John",
      "Canada",
      "Ontario",
      4,
      2023,
      25,
      25
    ],
    [
      "Jane",
      "Canada",
      "Quebec",
      4,
      2023,
      20,
      20
    ],
    [
      null,
      "Canada",
      null,
      4,
      2023,
      10,
      null
    ],
    [
      "Kevin",
      null,
      null,
      4,
      2023,
      null,
      null
    ]
  ]
```

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

### PR DESCRIPTION
**Pull request by ishaoxy**
### Description

1. Added a `groupNotNull` predicate  

2. Wrapped each window expression in a conditional form:

`CASE WHEN groupNotNull THEN raw_expr ELSE CAST(NULL AS expr_type) END`

### Related Issues
* Resolve #4751 

### Check List
- [x] New functionality includes testing.
- [ ] New functionality has been documented.
 - [ ] New functionality has javadoc added.
 - [ ] New functionality has a user manual doc added.
- [ ] New PPL command [checklist](https://github.com/opensearch-project/sql/blob/main/docs/dev/ppl-commands.md) all confirmed.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff` or `-s`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java
Comment (RyanL1997) [inline core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java]: nit: unnecessary change.

File: core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java [hunk 1]
```diff
@@ -1692,21 +1652,61 @@ public RelNode visitStreamWindow(StreamWindow node, CalcitePlanContext context)
...
+  private List<RexNode> wrapWindowFunctionsWithGroupNotNull(
+      List<RexNode> overExpressions, RexNode groupNotNull, CalcitePlanContext context) {
+    List<RexNode> wrappedOverExprs = new ArrayList<>(overExpressions.size());
+    for (RexNode overExpr : overExpressions) {
+      RexNode rawExpr = overExpr;
+      String aliasName = null;
+      if (overExpr instanceof RexCall rc && rc.getOperator() == SqlStdOperatorTable.AS) {
+        rawExpr = rc.getOperands().get(0);
+        if (rc.getOperands().size() >= 2 && rc.getOperands().get(1) instanceof RexLiteral lit) {
+          aliasName = lit.getValueAs(String.class);
```
Comment (RyanL1997) [inline core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java:1692]: Potential NPE: Add null check before calling `lit.getValueAs(String.class)`. The literal value could be null.

```java
  if (rc.getOperands().size() >= 2 && rc.getOperands().get(1) instanceof RexLiteral lit
      && lit.getValue() != null) {
      aliasName = lit.getValueAs(String.class);
  }
```

File: integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteExplainIT.java [hunk 2]
```diff
@@ -745,6 +742,7 @@ public void testExplainOnFirstLast() throws IOException {
   }
 
   // Only for Calcite
+  @Test
```
Comment (RyanL1997) [inline integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteExplainIT.java:745]: nice :)

File: core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java [hunk 3]
```diff
@@ -1692,21 +1652,61 @@ public RelNode visitStreamWindow(StreamWindow node, CalcitePlanContext context)
...
+      // wrap each expr: CASE WHEN groupNotNull THEN rawExpr ELSE CAST(NULL AS rawType) END
+      List<RexNode> wrappedOverExprs =
+          wrapWindowFunctionsWithGroupNotNull(overExpressions, groupNotNull, context);
+      context.relBuilder.projectPlus(wrappedOverExprs);
+      // resort when there is by condition
       context.relBuilder.sort(context.relBuilder.field(ROW_NUMBER_COLUMN_FOR_STREAMSTATS));
       context.relBuilder.projectExcept(context.relBuilder.field(ROW_NUMBER_COLUMN_FOR_STREAMSTATS));
+    } else {
+      List<RexNode> overExpressions =
+          node.getWindowFunctionList().stream().map(w -> rexVisitor.analyze(w, context)).toList();
```
Comment (RyanL1997) [inline core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java]: The same `overExpressions` calculation appears twice. Consider extracting this to a variable before the if-else block:

```java
List<RexNode> overExpressions = node.getWindowFunctionList().stream()
    .map(w -> rexVisitor.analyze(w, context)).toList();
```

File: core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java [hunk 4]
```diff
@@ -1692,21 +1652,61 @@ public RelNode visitStreamWindow(StreamWindow node, CalcitePlanContext context)
...
+      List<RexNode> groupByList =
+          groupList.stream().map(expr -> rexVisitor.analyze(expr, context)).toList();
+      List<RexNode> notNullList =
+          PlanUtils.getSelectColumns(groupByList).stream()
+              .map(context.relBuilder::field)
+              .map(context.relBuilder::isNotNull)
+              .toList();
+      RexNode groupNotNull =
+          notNullList.isEmpty()
+              ? context.relBuilder.literal(true)
```
Comment (RyanL1997) [inline core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java]: Just for my understanding: when `notNullList.isEmpty()`, returning `literal(true)` means all rows pass the null check. Is this the intended behavior when there are no grouping fields?

**Review by RyanL1997 — COMMENTED** [review]
Hi @ishaoxy , thanks for taking this on. I just left some comments. In addition, for the testing, I saw we have covered most of the 'happy' cases, consider adding more negative cases (e.g. “What happens when `GROUP BY col1, col2` and only one column is null?”).

**Comment by RyanL1997** [comment]
nit: I noticed that there were multiple empty space line deletion in the diff - consider revert these changes.

File: core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java (hunk 1 above)
Comment (LantaoJin) [reply core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java:1692]: `null instanceOf Class` always return false. So no need to check again.

File: integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteExplainIT.java (hunk 2 above)
Comment (ishaoxy) [reply integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteExplainIT.java:745]: :)

**Comment by ishaoxy** [comment]
> Hi @ishaoxy , thanks for taking this on. I just left some comments. In addition, for the testing, I saw we have covered most of the 'happy' cases, consider adding more negative cases (e.g. “What happens when `GROUP BY col1, col2` and only one column is null?”).

Thank you for the suggestion! I have added such negative test.

File: core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java (hunk 3 above)
Comment (ishaoxy) [reply core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java]: fixed.

File: core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java [hunk 5]
```diff
@@ -1641,7 +1641,7 @@ public RelNode visitStreamWindow(StreamWindow node, CalcitePlanContext context)
           new String[] {ROW_NUMBER_COLUMN_FOR_STREAMSTATS});
     }
 
-    // Default
+    // default
     if (hasGroup) {
```
Comment (yuancu) [inline core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java:1648]: I'm a little curious why is this patch only applied to the default case. How about case 2: `node.isGlobal() && hasWindow && hasGroup`, why won't the current implementation regard two rows with `null` grouping fields as the same group? The results seem correct, but I haven't figured out the trick.

**Review by yuancu — DISMISSED** [review]

File: core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java (hunk 4 above)
Comment (ishaoxy) [reply core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java]: This code now has been modified; sorry for this redundant logic. Because in this branch always hasGroup==true, notNullList will never be empty, and it will get result like `[state IS NOT NULL, country IS NOT NULL]` based on the group field.

File: core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java (hunk 5 above)
Comment (ishaoxy) [reply core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java:1648]: Because `global` path grouping uses `return context.relBuilder.equals(rightGroup, outerGroup);` to achieve grouping, `null == null` will not return true, so `null` value will not be treated as a group. However, the `default` path uses SQL's native partition semantics. In the future, we may add a button to support both these behaviors.

File: integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteStreamstatsCommandIT.java [hunk 6]
```diff
@@ -644,10 +645,43 @@ public void testMultipleStreamstatsWithNull() throws IOException {
...
+        rows("Jake", "USA", "California", 4, 2023, 70, 70, 70),
+        rows("Hello", "USA", "New York", 4, 2023, 30, 30, 50),
+        rows("John", "Canada", "Ontario", 4, 2023, 25, 25, 25),
+        rows("Jane", "Canada", "Quebec", 4, 2023, 20, 20, 22.5),
+        rows("Jay", "USA", null, 4, 2023, 28, null, 50));
+
+    Request deleteRequest =
+        new Request(
+            "DELETE", String.format("/%s/_doc/%d?refresh=true", TEST_INDEX_STATE_COUNTRY, docId));
+    client().performRequest(deleteRequest);
```
Comment (LantaoJin) [inline integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteStreamstatsCommandIT.java]: please change the code (and all others) to
```
...
client().performRequest(insertRequest);
try {
...
} finally {
    Request deleteRequest =
        new Request(
            "DELETE", String.format("/%s/_doc/%d?refresh=true", TEST_INDEX_STATE_COUNTRY, docId));
    client().performRequest(deleteRequest);
}
```

File: integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteStreamstatsCommandIT.java [hunk 7]
```diff
@@ -644,10 +645,43 @@ public void testMultipleStreamstatsWithNull() throws IOException {
         rows("Hello", "USA", "New York", 4, 2023, 30, 30, 50),
         rows("John", "Canada", "Ontario", 4, 2023, 25, 25, 25),
         rows("Jane", "Canada", "Quebec", 4, 2023, 20, 20, 22.5),
-        rows(null, "Canada", null, 4, 2023, 10, 10, 18.333333333333332),
+        rows(null, "Canada", null, 4, 2023, 10, null, 22.5),
         rows("Kevin", null, null, 4, 2023, null, null, null));
   }
 
+  @Test
+  public void testMultipleStreamstatsWithNull2() throws IOException {
```
Comment (LantaoJin) [inline integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteStreamstatsCommandIT.java:657]: can you add a test for complex expression:
```
source=%s
| eval new_state=lower(state), new_country=lower(country) 
| streamstats avg(age) as avg_age by new_state, new_country
```

Comment (ishaoxy) [reply integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteStreamstatsCommandIT.java:657]: added.

File: integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteStreamstatsCommandIT.java (hunk 6 above)
Comment (ishaoxy) [reply integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteStreamstatsCommandIT.java]: fixed.

**Review by LantaoJin — APPROVED** [review]

**Review by RyanL1997 — APPROVED** [review]
@ishaoxy LGTM thanks for the change.
