### PR TITLE
Fix the flaky CalcitePPLTcphIT

### LINKED ISSUE #4261: [BUG] CalcitePPLTpchIT is flaky
**What is the bug?**

TestQ1 is occasionally failing in main, e.g. https://github.com/opensearch-project/sql/actions/runs/17594180049/job/49982291692.

```
CalcitePPLTpchIT > testQ1 FAILED
    java.lang.AssertionError: 
    Expected: iterable with items [[], [], [], []] in any order
         but: not matched: <["A","F",37474,37569624.64,35676192.096999995,37101416.222424,25.354533152909337,25419.231826792962,0.0508660351826793,1478]>
        at __randomizedtesting.SeedInfo.seed([7DBF59379F8C433E:DF95364E8E9BEC79]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at org.opensearch.sql.util.MatcherUtils.verify(MatcherUtils.java:193)
        at org.opensearch.sql.util.MatcherUtils.verifyDataRows(MatcherUtils.java:160)
        at org.opensearch.sql.calcite.tpch.CalcitePPLTpchIT.testQ1(CalcitePPLTpchIT.java:59)
```

At a quick glance, seems like data is being fetched before a refresh runs.

**How can one reproduce the bug?**
With great care.

**What is the expected behavior?**
Should pass consistently.

**What is your host/environment?**
 - OS: Mac OS 13
 - Java 24

**Do you have any screenshots?**
N/A

**Do you have any additional context?**
N/A

### PR DESCRIPTION
**Pull request by LantaoJin**
### Description
Fix the flaky CalcitePPLTcphIT

### Related Issues
Resolves #4261

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
 - [ ] New functionality has javadoc added.
 - [ ] New functionality has a user manual doc added.
- [ ] New PPL command [checklist](https://github.com/opensearch-project/sql/blob/main/docs/dev/ppl-commands.md) all confirmed.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff` or `-s`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: integ-test/src/test/java/org/opensearch/sql/calcite/tpch/CalcitePPLTpchIT.java [hunk 1]
```diff
@@ -143,21 +142,19 @@ public void testQ3() throws IOException {
...
         actual,
-        rows("1-URGENT", 7),
+        rows("1-URGENT", 9),
         rows("2-HIGH", 7),
-        rows("3-MEDIUM", 4),
-        rows("4-NOT SPECIFIED", 7),
-        rows("5-LOW", 10));
+        rows("3-MEDIUM", 9),
+        rows("4-NOT SPECIFIED", 8),
+        rows("5-LOW", 12));
```
Comment (yuancu) [inline integ-test/src/test/java/org/opensearch/sql/calcite/tpch/CalcitePPLTpchIT.java:157]: Can you explain how blocking the index load relates to this integration test fix? The connection isn't clear to me from the current changes.

Comment (LantaoJin) [reply integ-test/src/test/java/org/opensearch/sql/calcite/tpch/CalcitePPLTpchIT.java:157]: Not related to the fix. I found this test was ignored due to the bucket size 1000 limitation. Just correct the results and enable it again.

**Review by yuancu — APPROVED** [review]
