### PR TITLE
PPL `fillnull` command enhancement

### LINKED ISSUE #4419: [RFC] Enhancement for PPL `fillnull` command
## Short-Term Goal

* **Add option-style syntax** for `fillnull`:

  ```
  fillnull [value=<string>] [<field-list>]
  ```
* **`value` is mandatory for now**.
* **Rationale:** Backward-compatible with current queries and ergonomics, while **preserving strict, schema-stable behavior**.

## Long-Term Goal (aligned with permissive mode)

Introduce an **opt-in permissive/schemaless execution mode** so `fillnull` (and related expressions) can **gracefully handle mixed types**

See detailed planning at:
#4349

## Current State

* **Syntax today:**

  * `fillnull with <replacement> [in <field-list>]`
  * `fillnull using <field>=<replacement> [, <field>=<replacement> ...]`
* **Typing today:** Lowered to standard `COALESCE(field, <value>)` (type-strict, returns original field type); single replacement across mixed types errors.

## Proposal

* **Short term:** Add the option-style surface (`fillnull [value=<string>] [<field-list>]`) alongside existing forms; semantics remain strict and schema-preserving; require `value=`.
* **Long term:** Implement the permissive/schemaless mode described above

## Examples (short term behavior)

* Same-typed fields:

  ```
  source=logs | fillnull value=0 response_time, status_code
  ```

  (Equivalent to `fillnull with 0 in response_time, status_code`)

* Apply to all fields (strict typing still applies, all fields must be strings in this case):

  ```
  source=logs | fillnull value="missing"
  ```

* Mixed-type workarounds today:

  ```
  source=logs | fillnull using host="N/A", response_time=0
  -- or
  source=logs | fillnull with "N/A" in host | fillnull with 0 in response_time
  ```

* **Type coercion failure (today, single replacement across mixed types):**

  ```
  source=logs | fillnull value="N/A" host, response_time
  ```

  Representative error:

  ```
  {
    "error": {
      "reason": "Invalid Query",
      "details": "Cannot infer return type for COALESCE; operand types: [INTEGER, VARCHAR]",
      "type": "IllegalArgumentException"
    },
    "status": 400
  }
  ```

### PR DESCRIPTION
**Pull request by ahkcs**
### What does this PR do?

Adds an alternative, option-style form for `fillnull` (available **since 3.4**) alongside existing `with/using` syntax. Semantics remain **strict and schema-stable** (no permissive casting in this PR).

**New syntax (option-style):**

```ppl
source=accounts | fillnull value=0              // apply to all fields (subject to type constraints)
source=accounts | fillnull value=0 age balance  // apply to specific fields
```

**Existing syntax (still supported):**

```ppl
source=accounts | fillnull with 0 in age, balance
source=accounts | fillnull using age=0, balance=0
```

---

### Notes / Limitations (intentional in this PR)

* `value` is **mandatory** (no default value yet).
* Mixed-type fills with a single replacement still error by design (strict typing preserved).
* Semantics remain strict and schema-preserving

---

### Future Work

* Track and implement an **opt-in permissive/schemaless mode** for mixed-type scenarios (follow-up: **#4349**).

### Related Issues
Partially resolves #4419 

### Check List
- [x] New functionality includes testing.
- [x] New functionality has been documented.
 - [x] New functionality has a user manual doc added.
- [x] New PPL command [checklist](https://github.com/opensearch-project/sql/blob/main/docs/dev/ppl-commands.md) all confirmed.
- [x] Commits are signed per the DCO using `--signoff` or `-s`.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

### CODE REVIEW

File: integ-test/src/test/java/org/opensearch/sql/calcite/CalciteNoPushdownIT.java [hunk 1]
```diff
@@ -19,88 +18,87 @@
...
-  CalciteSortCommandIT.class,
-  CalciteStatsCommandIT.class,
-  CalciteSystemFunctionIT.class,
-  CalciteTextFunctionIT.class,
-  CalciteTopCommandIT.class,
-  CalciteTrendlineCommandIT.class,
-  CalciteVisualizationFormatIT.class,
-  CalciteWhereCommandIT.class,
-  CalcitePPLTpchIT.class
+@Suite.SuiteClasses({CalciteExplainIT.class
```
Comment (dai-chen) [inline integ-test/src/test/java/org/opensearch/sql/calcite/CalciteNoPushdownIT.java]: why all comment out?

File: docs/user/ppl/cmd/fillnull.rst [hunk 2]
```diff
@@ -90,7 +102,57 @@ PPL query::
...
+
+**Note:** When applying the same value to all fields, all fields must be the same type. For mixed types, use separate fillnull commands.
+
 Limitations
 ===========
 * The ``fillnull`` command is not rewritten to OpenSearch DSL, it is only executed on the coordination node.
 * Before 3.1.0, at least one field is required.
+* **Type Restrictions**:
+
+  The replacement value type must match ALL field types in the field list. When applying the same value to multiple fields, all fields must be the same type (all strings or all numeric).
```
Comment (dai-chen) [inline docs/user/ppl/cmd/fillnull.rst]: I didn't find validation code and test. What will happen if users provide replacement value of different type?

File: integ-test/src/test/java/org/opensearch/sql/ppl/FillNullCommandIT.java [hunk 3]
```diff
@@ -212,4 +212,55 @@ public void testFillNullWithFunctionMultipleCommands() throws IOException {
         rows("sixteen", 16.81),
         rows("unknown", 7.12));
   }
+
+  @Test
+  public void testAggregationSumWithNullValues() throws IOException {
+    JSONObject result =
+        executeQuery(String.format("source=%s | stats sum(num0) as total", TEST_INDEX_CALCS));
+    verifyDataRows(result, rows(10));
+  }
```
Comment (ykmr1224) [inline integ-test/src/test/java/org/opensearch/sql/ppl/FillNullCommandIT.java]: Looks like this test case is not for `fillnull`.

File: integ-test/src/test/java/org/opensearch/sql/ppl/FillNullCommandIT.java [hunk 4]
```diff
@@ -212,4 +212,55 @@ public void testFillNullWithFunctionMultipleCommands() throws IOException {
...
+                TEST_INDEX_CALCS));
+    verifyDataRows(result, rows(10));
+  }
+
+  @Test
+  public void testAggregationCountWithNullValues() throws IOException {
+    JSONObject result =
+        executeQuery(String.format("source=%s | stats count(num0) as total", TEST_INDEX_CALCS));
+    verifyDataRows(result, rows(8));
+  }
```
Comment (ykmr1224) [inline integ-test/src/test/java/org/opensearch/sql/ppl/FillNullCommandIT.java]: Same as above.

File: integ-test/src/test/java/org/opensearch/sql/ppl/FillNullCommandIT.java [hunk 5]
```diff
@@ -212,4 +212,55 @@ public void testFillNullWithFunctionMultipleCommands() throws IOException {
...
+                TEST_INDEX_CALCS));
+    verifyDataRows(result, rows(17));
+  }
+
+  @Test
+  public void testAggregationAvgWithNullValues() throws IOException {
+    JSONObject result =
+        executeQuery(String.format("source=%s | stats avg(num0) as average", TEST_INDEX_CALCS));
+    verifyDataRows(result, rows(1.25));
+  }
```
Comment (ykmr1224) [inline integ-test/src/test/java/org/opensearch/sql/ppl/FillNullCommandIT.java]: Same as above.

File: integ-test/src/test/java/org/opensearch/sql/ppl/FillNullCommandIT.java [hunk 6]
```diff
@@ -212,4 +212,55 @@ public void testFillNullWithFunctionMultipleCommands() throws IOException {
...
+        executeQuery(String.format("source=%s | stats sum(num0) as total", TEST_INDEX_CALCS));
+    verifyDataRows(result, rows(10));
+  }
+
+  @Test
+  public void testAggregationSumAfterFillNull() throws IOException {
+    JSONObject result =
+        executeQuery(
+            String.format(
+                "source=%s | fillnull with 0 in num0 | stats sum(num0) as total",
```
Comment (ykmr1224) [inline integ-test/src/test/java/org/opensearch/sql/ppl/FillNullCommandIT.java]: I don't see much value to test with multiple aggregate functions.

And should we add tests for new syntax?

File: ppl/src/main/antlr/OpenSearchPPLLexer.g4 [hunk 7]
```diff
@@ -264,6 +262,7 @@ EARLIEST:                           'EARLIEST';
 LATEST:                             'LATEST';
 TAKE:                               'TAKE';
 LIST:                               'LIST';
+VALUE:                              'VALUE';
```
Comment (ykmr1224) [inline ppl/src/main/antlr/OpenSearchPPLLexer.g4]: I think it does not belong to AGGREGATIONS.

File: docs/user/ppl/cmd/fillnull.rst [hunk 8]
```diff
@@ -90,7 +102,57 @@ PPL query::
...
+    os> source=accounts | fields age, balance | fillnull value=0;
+    fetched rows / total rows = 4/4
+    +-----+---------+
+    | age | balance |
+    |-----+---------|
+    | 32  | 39225   |
+    | 36  | 5686    |
+    | 28  | 32838   |
+    | 33  | 4180    |
+    +-----+---------+
```
Comment (ykmr1224) [inline docs/user/ppl/cmd/fillnull.rst]: This example does not demonstrate the behavior (no field is filled)

File: ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java [hunk 9]
```diff
@@ -281,6 +281,18 @@ public void testFillNullWithoutFields() {
...
+  public void testFillNullValueSyntaxWithFields() {
+    assertEquals(
+        "source=table | fillnull with *** in identifier, identifier",
+        anonymize("source=t | fillnull value=0 f1 f2"));
+  }
+
+  @Test
+  public void testFillNullValueSyntaxAllFields() {
+    assertEquals("source=table | fillnull with ***", anonymize("source=t | fillnull value=0"));
+  }
```
Comment (ykmr1224) [inline ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java:294]: Why does it anonymize to different syntax?

File: integ-test/src/test/java/org/opensearch/sql/ppl/FillNullCommandIT.java (hunk 3 above)
Comment (ahkcs) [reply integ-test/src/test/java/org/opensearch/sql/ppl/FillNullCommandIT.java]: Hi Tomo, I added these test case to track how `fillnull` interacts with aggregate functions

File: integ-test/src/test/java/org/opensearch/sql/ppl/FillNullCommandIT.java (hunk 6 above)
Comment (ahkcs) [reply integ-test/src/test/java/org/opensearch/sql/ppl/FillNullCommandIT.java]: Hi Tomo, the new syntax is tested in `CalciteFillNullCommandIT`
These tests are added to test how `fillnull` command interacts with aggregate functions, I think they are optional but it can show how aggregate functions changed after using fillnull

File: integ-test/src/test/java/org/opensearch/sql/ppl/FillNullCommandIT.java (hunk 3 above)
Comment (ahkcs) [reply integ-test/src/test/java/org/opensearch/sql/ppl/FillNullCommandIT.java]: I updated to remove these tests as they are not directly related to `fillnull` command

File: integ-test/src/test/java/org/opensearch/sql/ppl/FillNullCommandIT.java (hunk 4 above)
Comment (ahkcs) [reply integ-test/src/test/java/org/opensearch/sql/ppl/FillNullCommandIT.java]: Removed

File: integ-test/src/test/java/org/opensearch/sql/ppl/FillNullCommandIT.java (hunk 5 above)
Comment (ahkcs) [reply integ-test/src/test/java/org/opensearch/sql/ppl/FillNullCommandIT.java]: Removed

File: integ-test/src/test/java/org/opensearch/sql/ppl/FillNullCommandIT.java (hunk 6 above)
Comment (ahkcs) [reply integ-test/src/test/java/org/opensearch/sql/ppl/FillNullCommandIT.java]: I updated to remove these tests as they are not directly related to fillnull command

File: ppl/src/main/antlr/OpenSearchPPLLexer.g4 (hunk 7 above)
Comment (ahkcs) [reply ppl/src/main/antlr/OpenSearchPPLLexer.g4]: Moved Value to COMMAND ASSIST KEYWORDS

File: docs/user/ppl/cmd/fillnull.rst (hunk 8 above)
Comment (ahkcs) [reply docs/user/ppl/cmd/fillnull.rst]: Updated

File: ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java (hunk 9 above)
Comment (ahkcs) [reply ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java:294]: It was reusing the existing logic to anonymize.
The existing logic distinguishes between two syntaxes based on semantic behavior:
  - Same values → with...in
  - Different values → using

However, value= syntax also applies the same value to all fields (like with...in), so we can't rely on this check alone to distinguish them. We need to track which syntax was originally used.

  Added a useValueSyntax boolean flag to the FillNull AST node:
  - Set to true when parsing fillnull value=...
  - Set to false for with...in and using (default)
  
This change might introduce some changes that is not clean so I think maybe it is also okay to keep using the existing logic since it only affects anonymizer test now. 

I updated the implementation to have the same syntax now for anonymizer test

File: integ-test/src/test/java/org/opensearch/sql/calcite/CalciteNoPushdownIT.java (hunk 1 above)
Comment (ahkcs) [reply integ-test/src/test/java/org/opensearch/sql/calcite/CalciteNoPushdownIT.java]: Hi Chen, I forgot to put it back after testing, restored

File: docs/user/ppl/cmd/fillnull.rst (hunk 2 above)
Comment (ahkcs) [reply docs/user/ppl/cmd/fillnull.rst]: Hi Chen, I added test cases in `CalciteFillNullCommandIT` to show the error message when users provide replacement value of different type

File: integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteFillNullCommandIT.java [hunk 10]
```diff
@@ -13,4 +21,120 @@ public void init() throws Exception {
...
+    // fillnull value=0 on mixed type fields without explicit field list
+    // When no fields specified, all fields must be same type
+    Throwable t =
+        assertThrowsWithReplace(
+            RuntimeException.class,
+            () ->
+                executeQuery(
+                    String.format(
+                        "source=%s | fields str2, int0 | fillnull value=0", TEST_INDEX_CALCS)));
+    verifyErrorMessageContains(t, "Cannot infer return type for COALESCE");
```
Comment (dai-chen) [inline integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteFillNullCommandIT.java]: I feel this error message is confusing to users? Should we validate in analyzer layer and return clear error message like 'the replacement value type is not compatible ..."?

File: core/src/main/java/org/opensearch/sql/ast/tree/FillNull.java [hunk 11]
```diff
@@ -42,8 +47,14 @@ public static FillNull ofSameValue(UnresolvedExpression replacement, List<Field>
 
   private final List<Pair<Field, UnresolvedExpression>> replacementPairs;
 
-  FillNull(List<Pair<Field, UnresolvedExpression>> replacementPairs) {
+  // Track if value= syntax was used (added in 3.4). Only needed to distinguish from with...in
+  // since both apply same value to all fields. using syntax is detected by checking if all
+  // replacement values are the same.
+  private final boolean useValueSyntax;
```
Comment (dai-chen) [inline core/src/main/java/org/opensearch/sql/ast/tree/FillNull.java:53]: Is this only for anonymizer?

Comment (ahkcs) [reply core/src/main/java/org/opensearch/sql/ast/tree/FillNull.java:53]: Yes, I think this change is debatable, you can refer to this comment: https://github.com/opensearch-project/sql/pull/4421#discussion_r2395563594

File: docs/user/ppl/cmd/fillnull.rst [hunk 12]
```diff
@@ -90,7 +102,57 @@ PPL query::
     +-----------------------+---------------+
 
 
+Example 5: replace null with specified value on specific fields (value= syntax)
+===============================================================================
+
+Since 3.4.
```
Comment (RyanL1997) [inline docs/user/ppl/cmd/fillnull.rst]: is this the new format of unified rst doc for ppl? cc @ritvibhatt

File: integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteFillNullCommandIT.java [hunk 13]
```diff
@@ -13,4 +21,120 @@ public void init() throws Exception {
     super.init();
     enableCalcite();
   }
+
+  // value= syntax tests
```
Comment (RyanL1997) [inline integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteFillNullCommandIT.java]: what is this? is this referencing to the following test case?

File: integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteFillNullCommandIT.java (hunk 10 above)
Comment (RyanL1997) [reply integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteFillNullCommandIT.java]: +1

File: docs/user/ppl/cmd/fillnull.rst [hunk 14]
```diff
@@ -90,7 +102,57 @@ PPL query::
...
+    | amberduke@pyrami.com  | Pyrami      |
+    | hattiebond@netagy.com | Netagy      |
+    | <not found>           | Quility     |
+    | daleadams@boink.com   | <not found> |
+    +-----------------------+-------------+
+
+Example 6: replace null with specified value on all fields (value= syntax)
+==========================================================================
+
+Since 3.4. This example only works when Calcite enabled. When no field list is specified, the replacement applies to all fields in the result.
```
Comment (RyanL1997) [inline docs/user/ppl/cmd/fillnull.rst]: question: since calcite is enabled by default, do we still need to emphasize this? cc @ritvibhatt

File: integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteFillNullCommandIT.java (hunk 13 above)
Comment (ahkcs) [reply integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteFillNullCommandIT.java]: Yes, this is for testing the new value= syntax

Comment (RyanL1997) [reply integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteFillNullCommandIT.java]: nit: we can remove it, since the test name itself should explain the purpose

Comment (ahkcs) [reply integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteFillNullCommandIT.java]: Updated to remove this

File: docs/user/ppl/cmd/fillnull.rst (hunk 14 above)
Comment (ahkcs) [reply docs/user/ppl/cmd/fillnull.rst]: Update doc to remove the mentioning of calcite

File: docs/user/ppl/cmd/fillnull.rst (hunk 12 above)
Comment (ahkcs) [reply docs/user/ppl/cmd/fillnull.rst]: Updated doc to not mention version info

File: integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteFillNullCommandIT.java (hunk 10 above)
Comment (ahkcs) [reply integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteFillNullCommandIT.java]: Updated the error message handling to make it clearer to users, modified IT tests

File: core/src/main/java/org/opensearch/sql/ast/tree/FillNull.java (hunk 11 above)
Comment (Swiddis) [reply core/src/main/java/org/opensearch/sql/ast/tree/FillNull.java:53]: I agree with you, we should just have the anonymizer output a consistent format if the underlying parse rule is irrecoverable without special tracking.

Personally I'd actually prefer the anonymizer defaulted to `value=` syntax, since it's consistent and more in line with other command syntax.

File: core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java [hunk 15]
```diff
@@ -1493,6 +1494,30 @@ public RelNode visitWindow(Window node, CalcitePlanContext context) {
...
+   * SemanticCheckException if types are incompatible.
+   */
+  private void validateFillNullTypeCompatibility(
+      RexNode replacement, RexNode fieldRef, String fieldName) {
+    RelDataTypeFamily replacementFamily = replacement.getType().getFamily();
+    RelDataTypeFamily fieldFamily = fieldRef.getType().getFamily();
+
+    // Check if the replacement type is compatible with the field type
+    // Allow NULL type family as it's compatible with any type
+    if (fieldFamily != replacementFamily
```
Comment (Swiddis) [inline core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java:1508]: question: what are the semantics of family equality? Will it automatically down-cast?

Wondering what would happen if you tried to fillnull an int with 8589934592 (2^33)

Comment (ahkcs) [reply core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java:1508]: ~~if the replacement value is 2^33, then the replacement value would be LONG, which will throw error if the field type is INT~~
Let me add an IT test for this case

Comment (ahkcs) [reply core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java:1508]: The type family equality check allows it. Both INT and BIGINT belong to SqlTypeFamily.NUMERIC, so the validation passes. Calcite's COALESCE function then handles the type widening automatically - it will widen the INT field to BIGINT to accommodate the larger value. No error is thrown; The result type becomes BIGINT.

I added an IT test (testFillNullWithLargeIntegerOnIntField) that confirms this behavior works correctly at runtime.

**Review by dai-chen — APPROVED** [review]
Thanks for the changes!

File: core/src/main/java/org/opensearch/sql/ast/tree/FillNull.java (hunk 11 above)
Comment (ykmr1224) [reply core/src/main/java/org/opensearch/sql/ast/tree/FillNull.java:53]: I don't have strong preference on this. I think anonimized query log is needed for operator to check the input query in case of trouble shooting(I suppose we don't use it for analyzing use case statistics, but not quite sure), while we don't want to log sensitive information.

**Review by RyanL1997 — APPROVED** [review]
