### PR TITLE
Fixed DateTimeFunctionTest.testWeekOfYearWithTimeType and YearWeekTestt.testYearWeekWithTimeType Test Failures

### LINKED ISSUE #2477: [BUG] Fix DateTimeFunctionTest. testWeekOfYearWithTimeType() YearweekTest. testYearweekWithTimeType() Unit tests.
**What is the bug?**

* ```DateTimeFunctionTest. testWeekOfYearWithTimeType() YearweekTest. testYearweekWithTimeType()``` unit tests are temporarily fixed in this PR here : https://github.com/opensearch-project/sql/pull/2476. 
* The ask from this bug is to come up with a proper fix for it.

Issue details: Jan 2024 starts with Monday and we calculate weekoftheyear using SUNDAY as the firstdayoftheweek this makes 22nd Jan 3rd week of the year rather 4th week. 

We can consider moving to LocalDateTime instead of Calendar.

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

### PR DESCRIPTION
**Pull request by kenrickyap**
### Description
Certain tests failed due to inconsistencies with how ISO 8601 and how opensearch sql calculates number of weeks since start of year. Specifically ISO 8601 calculates weeks using the following criteria:
- Weeks start on Monday
- The first week of a year is any week containing 4 or more days in the new year.

Whereas YEARWEEK counts only full weeks, where weeks start on Sunday. To fix the discrepancy we find the first Sunday of the year and start counting weeks from that date.

### Related Issues
Resolves #2477 

### Check List
- [x] New functionality includes testing.
- [x] New functionality has been documented.
 - [x] New functionality has javadoc added.
 - [x] New functionality has a user manual doc added.
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff`.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java [hunk 1]
```diff
@@ -1232,26 +1234,37 @@ public void testWeekFormats(
   // Issue: https://github.com/opensearch-project/sql/issues/2477
   @Test
   public void testWeekOfYearWithTimeType() {
+    // The following calculation is needed to correct the discrepancy in how ISO 8601
```
Comment (acarbonetto) [inline core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java:1237]: Can we move this logic to a common test util class to avoid duplication?  

Unfortunately, neither `YearweekTest` nor `DateTimeFunctionTest` extends `DateTimeTestBase`.  But I think that might be a good place to move the function (maybe as a static method?) unless you can find a better place.

**Review by acarbonetto — APPROVED** [review]

File: core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java (hunk 1 above)
Comment (kenrickyap) [reply core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java]: addressed comment

**Comment by LantaoJin** [comment]
@kenrickyap could this patch address the flaky test listed in and workaround by PR https://github.com/opensearch-project/sql/pull/3225 either? If yes, please update that test too.

**Comment by kenrickyap** [comment]
> @kenrickyap could this patch address the flaky test listed in and workaround by PR #3225? If yes, please update that test too.

@LantaoJin I have tried to apply the same logic but for some reason the unit test is still failing after I remove the check for January and December. Will spend a little more time to investigate!

File: core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeTestBase.java [hunk 2]
```diff
@@ -231,4 +234,19 @@ protected Double unixTimeStampOf(LocalDateTime value) {
...
     return unixTimeStampOf(DSL.literal(new ExprTimestampValue(value))).valueOf().doubleValue();
   }
+
+  // The following calculation is needed to correct the discrepancy in how ISO 860 and our
+  // implementation of YEARWEEK calculates. ISO 8601 calculates weeks using the following criteria:
+  //   - Weeks start on Monday
+  //   - The first week of a year is any week containing 4 or more days in the new year.
+  // Whereas YEARWEEK counts only full weeks, where weeks start on Sunday. To fix the discrepancy
+  // we find the first Sunday of the year and start counting weeks from that date.
+  protected static int getYearWeek(LocalDate date) {
```
Comment (acarbonetto) [inline core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeTestBase.java:244]: why protected?

**Review by acarbonetto — DISMISSED** [review]

**Review by YANG-DB — APPROVED** [review]

**Review by LantaoJin — CHANGES_REQUESTED** [review]
> https://github.com/opensearch-project/sql/pull/3235#issuecomment-2584933070

any update?

**Comment by kenrickyap** [comment]
> > [#3235 (comment)](https://github.com/opensearch-project/sql/pull/3235#issuecomment-2584933070)
> 
> any update?

Have found fix for #3225. However, in finding the fix have identified inconsistency of behaviour between extract and yearweek implementation. Specifically, `extract` is calculating week_of_year using java.time libaray (setting Local to Local.English) where as `yearweek` using CalendarLookup.getWeekNumber (to align with MySQL). Depending on which function users use, they will get a different value.

I believe it would be best to align the behaviour of extract and yearweek. However as the current test are failing and preventing other PRs from being merge, we should merge this ticket asap and aim to align function behaviour in another ticket

File: core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeTestBase.java (hunk 2 above)
Comment (kenrickyap) [reply core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeTestBase.java:244]: since this is a test util, protected would ensure that only unit tests can use the above function.

**Comment by kenrickyap** [comment]
@YANG-DB @acarbonetto @LantaoJin would we be able to review and merge this ticket? Currently the above unit tests are failing for https://github.com/opensearch-project/sql/pull/3230

**Review by acarbonetto — APPROVED** [review]

**Comment by acarbonetto** [comment]
> Have found fix for #3225. However, in finding the fix have identified inconsistency of behaviour between extract and yearweek implementation. Specifically, `extract` is calculating week_of_year using java.time libaray (setting Local to Local.English) where as `extract` using CalendarLookup.getWeekNumber (to align with MySQL). Depending on which function users use, they will get a different value.

This as a separate bug with reference to the work here.  Aligning implementation for `extract` and `extract` can be out of scope for this issue and can be solved separately.  

Will raise a BUG and get this moving forward as it is blocking further development.

**Review by YANG-DB — DISMISSED** [review]

File: core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeTestBase.java [hunk 3]
```diff
@@ -231,4 +234,19 @@ protected Double unixTimeStampOf(LocalDateTime value) {
...
+    LocalDate firstSundayOfYear = date.withDayOfYear(1).with(nextOrSame(SUNDAY));
+    int week =
+        date.isBefore(firstSundayOfYear)
+            ? 52
```
Comment (acarbonetto) [inline core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeTestBase.java:248]: some years have 52 week unfortunately

**Review by acarbonetto — CHANGES_REQUESTED** [review]

**Review by YANG-DB — APPROVED** [review]

**Review by noCharger — APPROVED** [review]
CI failed on BWC, doesn't seem related though

```
Execution failed for task ':integ-test:sqlBwcCluster#mixedClusterTask'.
> `cluster{:integ-test:sqlBwcCluster0}` failed to wait for cluster health yellow after 40 SECONDS
    IO error while waiting cluster
    503 Service Unavailable
```

**Comment by acarbonetto** [comment]
> CI failed on BWC, doesn't seem related though
> 
> ```
> Execution failed for task ':integ-test:sqlBwcCluster#mixedClusterTask'.
> > `cluster{:integ-test:sqlBwcCluster0}` failed to wait for cluster health yellow after 40 SECONDS
>     IO error while waiting cluster
>     503 Service Unavailable
> ```

No it is not. See: https://github.com/opensearch-project/sql/issues/3184

**Review by acarbonetto — APPROVED** [review]
