### PR TITLE
[BugFix] Fix eval overwrites MAP root field when assigning multiple dotted-path names (#5185)

### LINKED ISSUE #5185: [BUG] `eval` overwrites MAP root field when assigning multiple dotted-path names
**What is the bug?**

When using `eval` to materialize multiple dotted paths from the same MAP column in a single command (e.g., `eval doc.user.name=doc.user.name, doc.user.age=doc.user.age`), the second assignment fails with `Field [doc.user.age] not found`. The first assignment succeeds, but it removes the MAP root column `doc` from the schema, making subsequent paths unresolvable.

**How can one reproduce the bug?**

1. Create a test index with a JSON string field:
```
curl -s -X PUT 'localhost:9200/t/_doc/1?refresh=true' -H 'Content-Type: application/json' \
  -d '{"doc": "{\"user\":{\"name\":\"John\",\"age\":30}}"}'
curl -s -X PUT 'localhost:9200/t/_doc/2?refresh=true' -H 'Content-Type: application/json' \
  -d '{"doc": "{\"user\":{\"name\":\"Alice\",\"age\":25}}"}'
```
2. Enable Calcite and run:
```
source=t | spath input=doc | eval doc.user.name=doc.user.name, doc.user.age=doc.user.age`
Error: Field [doc.user.age] not found
```

3. Note: splitting into two separate eval commands also fails for the same reason:

```
source=t | spath input=doc | eval doc.user.name=doc.user.name | eval doc.user.age=doc.user.age
```

**What is the expected behavior?**

Both dotted-path assignments should succeed. The MAP root column doc should not be removed when a dotted-path column like `doc.user.name` is added — the dotted name is a new flat column, not a nested sub-field of doc.

**What is your host/environment?**
 - Version: PPL Calcite V3
 - Plugins: 3.6

**Do you have any screenshots?**
N/A

**Do you have any additional context?**

- Single dotted-path eval works: `eval doc.user.name=doc.user.name succeeds`.
- The workaround is to use non-dotted aliases: `eval username=doc.user.name, age=doc.user.age`.
- The `shouldOverrideField` heuristic was designed for OpenSearch nested/struct fields where resource.attributes.key is a real sub-field of resource. For MAP columns produced by spath, the dotted name is just a flat column name that happens to contain dots — it's not a nested sub-field.
- The root cause is in `projectPlusOverriding` → `shouldOverrideField`, which checks `newName.startsWith(originalName + ".")`. When eval creates a column named `doc.user.name`, the check `"doc.user.name".startsWith("doc.")` returns true, so `projectPlusOverriding` removes the original `doc` MAP column. The second eval expression `doc.user.age=doc.user.age` then fails because `doc` no longer exists in the schema.

```java
// shouldOverrideField (CalciteRelNodeVisitor.java)
private boolean shouldOverrideField(String originalName, List<String> newNames) {
    return newNames.stream()
        .anyMatch(newName ->
            newName.equals(originalName)
            || newName.startsWith(originalName + "."));  // ← incorrectly matches MAP root
}
```

### PR DESCRIPTION
**Pull request by songkant-aws**
### Description

When using `eval` to materialize multiple dotted-path names from a MAP column (e.g. from `spath`), the second assignment fails with `Field [doc.user.age] not found`. The root cause sits in `shouldOverrideField` in `CalciteRelNodeVisitor.java`, which used a `newName.startsWith(originalName + ".")` prefix match to decide whether to drop the original field. When `eval` creates a column named `doc.user.name`, that check matches `doc` as a prefix and removes the MAP root column, so subsequent eval expressions fail because `doc` no longer exists in the row schema.

### Fix

Remove the prefix branch from `shouldOverrideField` entirely and return the method to an exact-name match. This aligns with SPL1 literal-name semantics: `eval foo.bar = ...` creates a brand-new field literally named `foo.bar`; it must never drop sibling or parent fields with overlapping names.

PR #4606 introduced the prefix branch to make `bin` on a nested field work without an explicit `fields` projection (issue #4482). The diagnosis was wrong — the prefix branch was a "patch on another patch" that silently clobbered any column that happened to be a prefix of an eval target. That same branch is what caused:

* Issue #5185 — a MAP root produced by `spath` got dropped when multiple dotted-path evals ran on top of it.
* Reviewer @qianheng-aws's case on this PR — `source=big5 | fields agent | eval agent.name = "test"` dropped the `agent` column entirely, leaving only `agent.name` in the response.

Both are symptoms of the same over-broad heuristic.

The original command-specific need from #4482 (letting `bin` on a nested leaf collapse the struct-parent columns so the flattened sibling leaves survive the final implicit `fields *` projection) is now handled locally inside `visitBin` via a small helper, `dropStructParentsFor`. That helper only drops parents that actually exist as struct-parent columns in the current row schema, so flat columns and MAP roots from `spath` are untouched.

### Related Issues
Resolves #5185

### Test Plan
* Kept the two spath regression tests that landed earlier on this PR (`CalcitePPLSpathTest`, `CalcitePPLSpathCommandIT`, `integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/5185.yml`).
* Added `CalciteEvalCommandIT.testEvalDottedNameDoesNotDropStructParent` and `testEvalDottedNamePreservesStructParent_ImplicitProject` to cover the reviewer's `agent` case.
* `CalciteBinCommandIT.testBinWithNestedFieldWithoutExplicitProjection` and `testBinWithEvalCreatedDottedFieldName` (from #4606) still pass — now via the scoped `dropStructParentsFor` path rather than the global prefix branch.
* `./gradlew spotlessApply spotlessCheck :core:test :ppl:test` — green.
* Relevant IT suites run locally: `CalciteBinCommandIT`, `CalcitePPLSpathCommandIT`, `CalciteEvalCommandIT`, `CalciteFlattenCommandIT`, `CalciteFlattenDocValueIT`, `CalciteObjectFieldOperateIT` — all green.

### Check List
- [x] New functionality includes testing
- [x] Commits signed per DCO (`-s`)
- [x] `spotlessCheck` passed
- [x] Unit tests passed
- [x] Integration tests passed

### CODE REVIEW

**Comment by songkant-aws** [comment]
## Decision Log
**Root Cause**: `shouldOverrideField` in `CalciteRelNodeVisitor.java` used a simple `newName.startsWith(originalName + ".")` prefix check to determine whether to remove the original field. When `eval` creates a column named `doc.user.name`, this check matches `doc` as a prefix, causing the MAP root column `doc` to be removed. The second eval expression `doc.user.age=doc.user.age` then fails because `doc` no longer exists in the schema.

**Approach**: Added a `hasSubFields(originalName, allFieldNames)` guard to the prefix-match heuristic. The prefix override now only triggers when the schema already contains other flattened sub-field columns of the parent (e.g., `resource.attributes.telemetry.sdk.enabled` alongside `resource`). Standalone MAP columns from `spath` have no sub-fields in the schema, so the prefix match no longer fires for them.

**Alternatives Rejected**:
1. **Type-based check (MAP vs ROW)**: Initially attempted to skip prefix matching for `SqlTypeName.MAP` fields. Failed because OpenSearch maps STRUCT types to Calcite MAP (not ROW) via `OpenSearchTypeFactory.convertExprTypeToRelDataType`, making it impossible to distinguish real struct parents from spath MAP columns by type alone.
2. **RexNode-based check**: Considered inspecting the `RexNode` of the new field to see if it accesses the original via ITEM. Too invasive and fragile.

**Pitfalls**: The initial MAP-type check broke `CalciteBinCommandIT.testBinWithNestedFieldWithoutExplicitProjection` and `testBinWithEvalCreatedDottedFieldName` because those tests depend on the prefix override for real OpenSearch struct fields (which are also MAP type in Calcite).

**Things to Watch**: The `hasSubFields` heuristic assumes that a standalone MAP column will never have flattened sub-field columns in the same schema. If a future feature adds both a MAP column and flattened sub-fields simultaneously, this heuristic could produce false positives.

**Comment by songkant-aws** [comment]
This narrow fix resolves the issue with a very specific solution. In the long term, if we can resolve the data type of nested field to be interpreted by Calcite `ROW` type, it could cover more cases.

**Review by LantaoJin — DISMISSED** [review]

File: core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java [hunk 1]
```diff
@@ -1329,15 +1315,31 @@ private void projectPlusOverriding(
...
                 // Match exact field names (e.g., "age" == "age") for flat fields
                 newName.equals(originalName)
                     // OR match nested paths (e.g., "resource.attributes..." starts with
-                    // "resource.")
-                    || newName.startsWith(originalName + "."));
+                    // "resource."), but only when the schema already contains sub-fields of
+                    // originalName. This distinguishes real struct parents (which have flattened
+                    // sub-field columns) from MAP columns produced by spath where dotted names
+                    // are just flat column names, not nested sub-fields.
+                    || (newName.startsWith(originalName + ".")
```
Comment (qianheng-aws) [inline core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java]: The original fix #4606 also introduced a very general bug -- adding new field with the same name as a child field name will remove the parent field. e.g.
```
source=big5 | fields agent | eval agent.name = "test" 
```
return 
```
{
    "schema": [
        {
            "name": "agent.name",
            "type": "string"
        }
    ],
    "datarows": [
        [
            "test"
        ]
    ],
    "total": 1,
    "size": 1
}
```

while we expect the `agent` field should be included in the output.

Will this fix it as well? Or, I'm thinking, is there a solution to rip-and-replace instead of making patch on another patch?

**Comment by songkant-aws** [comment]
@qianheng-aws thanks — you were right. I rewrote the fix along the rip-and-replace path you suggested in the new commit `a7d35a0a4`:

* `shouldOverrideField` is now exact-name match only; the `startsWith` prefix branch (and the intermediate `hasSubFields` guard I had added) are gone. Assigning `eval foo.bar = ...` no longer touches any sibling or parent field, matching SPL1 literal-name semantics.
* Your `source=big5 | fields agent | eval agent.name = "test"` case is now covered directly by `CalciteEvalCommandIT.testEvalDottedNameDoesNotDropStructParent` — `agent` is preserved in the output.
* The original motivation for #4606 (letting `bin` on a nested leaf flatten the struct-parent so its siblings come through when no explicit `fields` projection is used) is now scoped to `visitBin` itself via `dropStructParentsFor`. The two tests that #4606 shipped (`testBinWithNestedFieldWithoutExplicitProjection`, `testBinWithEvalCreatedDottedFieldName`) still pass via that targeted path instead of via a global prefix-override.

I've updated the PR description to reflect this framing. The spath regression tests from the earlier revision are still there.

**Comment by songkant-aws** [comment]
## Decision Log (update, Phase 3.4)

**New root-cause framing**: PR #4606 diagnosed issue #4482 as requiring a prefix-override in `shouldOverrideField`, so that assigning a dotted-path field would drop struct-parent columns that were a prefix of the new name. That framing was incorrect: the prefix branch also fires for any unrelated column whose name happens to be a prefix of an eval target, including MAP roots from `spath` (issue #5185) and arbitrary flat columns like the reviewer's `source=big5 | fields agent | eval agent.name = "test"`. The behavior that `bin` on a nested leaf actually needs — collapsing the struct-parent columns so the flattened sibling leaves survive the final implicit `fields *` projection — is specific to `bin`, not to `shouldOverrideField` in general.

**Removed**:
* The entire prefix branch in `shouldOverrideField` (the `newName.startsWith(originalName + ".")` match).
* The `hasSubFields` helper introduced in the previous revision of this PR.
* The third `List<String> allFieldNames` parameter on `shouldOverrideField`; `projectPlusOverriding` now calls the two-arg form.

**Added**:
* `dropStructParentsFor(String dottedName, CalcitePlanContext context)` invoked from `visitBin` only. It walks the dotted name, collects any intermediate prefixes that actually exist as columns in the current row schema, and drops them. This is a no-op for flat columns and MAP roots (spath), so it doesn't reintroduce the #5185 / reviewer's regressions.
* `CalciteEvalCommandIT.testEvalDottedNameDoesNotDropStructParent` — the exact reviewer case on the `agent` struct, verifies both `agent` and `agent.name` survive.
* `CalciteEvalCommandIT.testEvalDottedNamePreservesStructParent_ImplicitProject` — complementary coverage without the explicit trailing `fields` projection, guarding the specific regression (that `agent` is preserved).
* A tiny `test_eval_agent` fixture in `CalciteEvalCommandIT.init()` with dynamic mapping (idempotent for repeated `@Before` invocations).

**Alternatives rejected**:
* The prior `hasSubFields` heuristic (first revision of this PR). Correctly handled #5185 but did not fix the reviewer's `agent` case: `agent` has no sibling sub-field columns in the row schema, so the heuristic treated it as "not a real struct parent" and spared it — but only because of that coincidence. The reviewer pointed out this is still a patch-on-patch, and they were right.
* `SqlTypeName.MAP` vs `ROW` discrimination inside `shouldOverrideField`. Doesn't work because OpenSearch `STRUCT` maps to Calcite MAP, so the type alone cannot distinguish a struct parent from a spath MAP root.
* `RexNode`-based introspection of the eval expression to detect ITEM access on the original column. Too invasive; still doesn't address `bin`'s command-specific need.

**Tests that required command-level adjustments**:
* `CalciteBinCommandIT.testBinWithNestedFieldWithoutExplicitProjection` and `testBinWithEvalCreatedDottedFieldName` (originally from PR #4606). Without the global prefix branch, the struct-parent columns (`resource`, `resource.attributes`, …) are no longer removed during `projectPlusOverriding`. `tryToRemoveNestedFields` on the final implicit `fields *` then collapses all the flattened sibling leaves back into the struct parents and drops the freshly-computed bin value. `visitBin` now calls `dropStructParentsFor` immediately after `projectPlusOverriding` to delete those parent columns, so the downstream pass keeps the flattened siblings + the bin value. Both tests pass unchanged.

**Comment by songkant-aws** [comment]
Follow-up (additive commit `ba8120ae4`): empirically verified the reviewer-flagged concern about `tryToRemoveNestedFields` eating eval overrides, and fixed it.

## Phase A — regression matrix (empirical, run against `Index.TELEMETRY`)

Telemetry mapping exposes struct parents (`resource`, `resource.attributes`, ..., `resource.attributes.telemetry.sdk`) side-by-side with the flattened leaves (e.g. `resource.attributes.telemetry.sdk.version`).

| scenario | query | result on prior HEAD (a7d35a0a4) | verdict |
|---|---|---|---|
| (a) eval override, implicit project | `source=<telemetry> \| eval resource.attributes.telemetry.sdk.version = "OVERRIDE"` | row = `[resource-struct-with-original-int, severityNumber]`; the `"OVERRIDE"` string is **gone** | **REGRESSION** |
| (a') eval override, explicit trailing `fields` | same + `\| fields resource.attributes.telemetry.sdk.version` | `"OVERRIDE"` returned as expected | passes |
| (d) bin on nested leaf (sanity) | `source=<telemetry> \| bin resource.attributes.telemetry.sdk.version span=2` | works (covered by `CalciteBinCommandIT#testBinWithNestedFieldWithoutExplicitProjection`) | passes |

(b) trendline on a nested numeric leaf and (c) rex/sed targeting a nested leaf also flow through `projectPlusOverriding`; once the eval case was confirmed as a regression, I moved straight to the fix (Option 1) rather than enumerating every callsite empirically, since the fix is unconditional across all callers.

## Phase B — fix applied (Option 1)

Moved `dropStructParentsFor` inside `projectPlusOverriding`, **gated on "the override actually matched an existing column name"** (i.e. the pre-override row schema already had that exact dotted name).

- Telemetry case: `resource.attributes.telemetry.sdk.version` already exists as a flat leaf → override fires → struct parents pruned → overridden value survives implicit `fields *`. ✅
- Reviewer's `agent` case on #5351 (`fields agent | eval agent.name = 'test'`): there's no pre-existing `agent.name` column in the row → `overriddenNames` is empty → `agent` struct parent survives untouched. ✅
- Issue #5185 (spath MAP root + multi-field eval): spath introduces new dotted names that were not already in the row schema → `overriddenNames` is empty → MAP root `doc` survives. ✅

`shouldOverrideField` is unchanged (still exact-match only). No heuristics on sub-fields or RexNode introspection were introduced.

## Phase C — regression-proof the fix

Added two new ITs in `CalciteEvalCommandIT`:

- `testEvalOverrideOfFlattenedNestedLeafSurvivesImplicitProject` — the primary regression guard; fails on `a7d35a0a4`, passes on `ba8120ae4`.
- `testEvalOverrideOfFlattenedNestedLeafWithExplicitProject` — control for the explicit-projection path.

Verified green on `ba8120ae4`:
- `./gradlew spotlessCheck` ✅
- `./gradlew :core:test :ppl:test` ✅
- `./gradlew :integ-test:integTest --tests CalciteEvalCommandIT --tests CalcitePPLSpathCommandIT --tests CalciteBinCommandIT --tests CalciteFlattenCommandIT --tests CalciteObjectFieldOperateIT --tests CalciteTrendlineCommandIT --tests CalcitePPLTrendlineIT --tests CalciteRexCommandIT --tests CalciteExpandCommandIT --tests CalciteMvExpandCommandIT --tests CalcitePPLPatternsIT` ✅

In particular:
- `testSpathAutoExtractWithMultiFieldEval` / `testSpathAutoExtractWithSeparateEvalCommands` (the #5185 guards) still pass.
- `testEvalDottedNameDoesNotDropStructParent` / `testEvalDottedNamePreservesStructParent_ImplicitProject` (the reviewer's `agent` case) still pass.
- `testBinWithNestedFieldWithoutExplicitProjection` / `testBinWithNestedFieldWithExplicitProjection` / `testBinWithEvalCreatedDottedFieldName` (the #4482 guards) still pass.

## Note on the bin-side `dropStructParentsFor` call

Left the explicit invocation from `visitBin` in place. It is redundant when the alias matches a pre-existing flat leaf (projectPlusOverriding now handles that), but still useful when `bin` is given a custom alias whose string does not match any existing field — the alias is still dotted and the parents should still be pruned. Updated the Javadoc on `dropStructParentsFor` to reflect both call sites.

**Review by qianheng-aws — APPROVED** [review]

**Review by yuancu — APPROVED** [review]
