### PR TITLE
Fix: CSV handling of embedded crlf

### LINKED ISSUE #3514: [BUG] CSV output does not handle entries with CRLF
**What is the bug?**
CSV output of entries like a\nb or a\r\nb should, according to RFC 4180, escape them to be "a\nb" and "a\r\nb", respectively, respectively. See section 2.5, https://www.rfc-editor.org/rfc/rfc4180

**How can one reproduce the bug?**
1. Add values to a test index
```
#!/usr/bin/env bash

# Assuming OPENSEARCH_SERVER is the server,
# OPENSEARCH_USER is the host, OPENSEARCH_PASSWORD is the password.
# and the user has the rights to create and query this index.

# Add an entry to the index that has a newline in it.
curl -XPUT "https://${OPENSEARCH_SERVER}:9200/csv_error/_doc/1" \
    --insecure \
    -H 'Content-Type: application/json' \
    -d'{  "field1": "a\nb" }' --user "${OPENSEARCH_USER}":"${OPENSEARCH_PASSWORD}"
# Optional, add an entry that has a quote in it.
curl -XPUT "https://${OPENSEARCH_SERVER}:9200/csv_error/_doc/2" \
    --insecure \
    -H 'Content-Type: application/json' \
    -d'{ "field1": "\"a\" b" }' --user "${OPENSEARCH_USER}":"${OPENSEARCH_PASSWORD}"
# Optional, add an entry that has no quotes, newlines, or commas.
curl -XPUT "https://${OPENSEARCH_SERVER}:9200/csv_error/_doc/3" \
    --insecure \
    -H 'Content-Type: application/json' \
    -d'{ "field1": "a b" }' --user "${OPENSEARCH_USER}":"${OPENSEARCH_PASSWORD}"
```
2. Query the index to CSV output or RAW output
```
#!/usr/bin/env bash

# CSV
curl -XPOST "https://${OPENSEARCH_SERVER}:9200/_plugins/_sql?format=csv" \
    --insecure \
    -H 'Content-Type: application/json' \
    -d'{ "query": "SELECT * FROM csv_error LIMIT 50" }' \
    --user "${OPENSEARCH_USER}":"${OPENSEARCH_PASSWORD}"

# Raw
curl -XPOST "https://${OPENSEARCH_SERVER}:9200/_plugins/_sql?format=raw" \
    --insecure \
    -H 'Content-Type: application/json' \
    -d'{ "query": "SELECT * FROM csv_error LIMIT 50" }' \
    --user "${OPENSEARCH_USER}":"${OPENSEARCH_PASSWORD}"
```
Output:
```
field1
a                      <-- no start quote
b                      <-- no end quote
"""a"" b"
```

**What is the expected behavior?**
The entries with `\r` and `\n` in any combination will be quoted.

**What is your host/environment?**
 - OS: Ubuntu 20.04
 - Version 2.19.1
 - Plugins - default

**Do you have any additional context?**
I should have caught this when I worked on https://github.com/opensearch-project/sql/issues/3050

### PR DESCRIPTION
**Pull request by Michael-S**
### Description

According to RFC 4180 for the CSV file format,
section 2, item 6, if a CSV cell contains a
carriage return ('\r') or line feed ('\n') it
must be quoted.

### Related Issues
Resolves #3514

### Check List
- [x ] New functionality includes testing.
- [ ] New functionality has been documented.  (N/A, bug fix)
 - [ ] New functionality has javadoc added.  (N/A, bug fix)
 - [ ] New functionality has a user manual doc added.  (N/A, bug fix)
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md). (N/A, bug fix)
- [x ] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose). (N/A, bug fix)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: protocol/src/main/java/org/opensearch/sql/protocol/response/format/FlatResponseBase.java [hunk 1]
```diff
@@ -84,7 +84,10 @@ protected List<List<String>> formatData(List<List<String>> lines) {
 
   protected String quoteIfRequired(String separator, String cell) {
     final String quote = "\"";
-    if (cell.contains(separator) || cell.contains(quote)) {
+    if (cell.contains(separator)
+        || cell.contains(quote)
+        || cell.contains("\r")
+        || cell.contains("\n")) {
```
Comment (Swiddis) [inline protocol/src/main/java/org/opensearch/sql/protocol/response/format/FlatResponseBase.java:90]: thought: We're now traversing the string 4 times instead of 2.

It might not have much of an impact in practice (benchmark?). But for formatting a large amount of data, I could see all these redundant checks adding up (imagining something like 1M rows of small cells with 0 special characters). Is there any built-in that can do this better?

**Review by Swiddis — APPROVED** [review]
Thanks for the contribution!

File: protocol/src/test/java/org/opensearch/sql/protocol/response/format/RawResponseFormatterTest.java [hunk 2]
```diff
@@ -135,6 +135,42 @@ void quoteIfRequired() {
...
+    String expected =
+        "field1|num%n"
+            + "abc|5%n"
+            + "\"def\r\"|\"\n6\"%n"
+            + "\"gh\ri\"|\"7\n\"%n"
+            + "\"jk\r\nl\"|\"\n\r8\"%n"
+            + "\"\r\nmno\r\n\"|\"9\n\r0\"";
+    assertEquals(format(expected), getRawFormatter().format(response));
+    // Pretty formatting raw or CSV data with embedded newlines and carriage
+    // returns will still look awful on output.
```
[the remark this answers is not in the document]
Comment (Michael-S) [reply protocol/src/test/java/org/opensearch/sql/protocol/response/format/RawResponseFormatterTest.java:163]: I'm not sure what would look better for pretty-printing with newlines in fields.

File: protocol/src/main/java/org/opensearch/sql/protocol/response/format/FlatResponseBase.java (hunk 1 above)
Comment (Michael-S) [reply protocol/src/main/java/org/opensearch/sql/protocol/response/format/FlatResponseBase.java:90]: I think to see if something matters, we would have to benchmark it.  My first thought would be to use a `java.lang.String::matches` with a regex like `"[\",\r\n]"` (but the first two entries would need to be dynamically added based on the input quote and separator characters).  My second would be to do a single traversal like:

```
for (int i = 0; i < cell.length(); i++) {
   int c = cell.codePointAt(c);
   if (c == ... || c == ... || c == ... || c == ) {
       return quote + cell.replaceAll(quote, quote + quote) + quote;
    }
    replace c;
```

For right now, if I understand OpenSearch properly the plugin is restricted to 10,000 rows.  I'm guessing on that scale, the extra string traversals are harmless.   But that's a completely wild guess, I won't argue with anyone who suggests otherwise.

Comment (Swiddis) [reply protocol/src/main/java/org/opensearch/sql/protocol/response/format/FlatResponseBase.java:90]: Yeah, checks out. Unless someone is outputting [very large text fields](https://github.com/opensearch-project/opensearch-spark/issues/625) the traversals shouldn't be noticeable. I think you could theoretically nitpick and say the "c == ... || c == ..." approach is better for CPU cache locality, but I don't think there's a realistic situation where that makes a real difference. Thanks!

**Comment by Swiddis** [comment]
Failing test tracked in #3516

File: protocol/src/test/java/org/opensearch/sql/protocol/response/format/RawResponseFormatterTest.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (Swiddis) [reply protocol/src/test/java/org/opensearch/sql/protocol/response/format/RawResponseFormatterTest.java:163]: IMO escaped literals like "\\n" would be better, but it's no big deal. Can let someone open a feature request down the road if they have a specific solution they like.

File: protocol/src/main/java/org/opensearch/sql/protocol/response/format/FlatResponseBase.java (hunk 1 above)
Comment (Michael-S) [reply protocol/src/main/java/org/opensearch/sql/protocol/response/format/FlatResponseBase.java:90]: > thought: We're now traversing the string 4 times instead of 2.
> 
> It might not have much of an impact in practice (benchmark?). But for formatting a large amount of data, I could see all these redundant checks adding up (imagining something like 1M rows of small cells with 0 special characters). Is there any built-in that can do this better?

You piqued my interest, so I wrote a simplistic benchmark.  https://github.com/Michael-S/silly_java_string_search
Ten million random unicode strings, length 20-520, with the quotable characters sprinkled throughout.  On my mid-range Intel laptop, in a single-threaded search: using the four `contains` calls took about 2.5 seconds; a manual loop to look at each character with four equality checks took about 3.8 seconds; and a regex took about 6.1 second.  (And the regex didn't find the same number of matches as the others, which confused me because I thought the regex was simple.)

So it looks like `contains` is a decent default.  Maybe some JVM wizard has a better solution.

**Review by seankao-az — APPROVED** [review]
