### PR TITLE
bin command error message enhancement

### LINKED ISSUE #4590: [BUG] `bin` Command Validation enhancement on Non-Numeric Fields
### **Description**

When the bin command is applied to a non-numeric field while using numeric span parameters (span, minspan, etc.), the command currently fails with an unclear or misleading error message.
Users cannot easily identify that the root cause is the use of a non-numeric field for numeric binning.

The expected behavior is that the bin command should gracefully skip numeric binning for non-numeric fields and preserve the original field values instead of throwing an error.
This ensures query continuity and prevents unexpected pipeline failures in mixed-type datasets.

---

### **Steps to Reproduce**

1. Execute a query that applies numeric binning to a non-numeric field:

   ```json
   {
     "query": "source=otellogs | bin severityText minspan=10"
   }
   ```

   (`severityText` is a **non-numeric field**, e.g., categorical text.)
2. Observe the returned error message.

---

### **Expected Behavior**

* The `bin` command should continue without error and return the original non-numeric value
  Example:
With this data
```
{\"_time\":1753722000, \"value\":\"1\"},
{\"_time\":1753722017, \"value\":2},
{\"_time\":1753722023, \"value\":\"invalid\"}
```
If we use
```
bin value span=10 | table _time, value, category | sort _time
```
Result:
_time | value | category
-- | -- | --
2025-07-28 17:00:00 | 0-10 | D
2025-07-28 17:00:17 | 0-10 | D
2025-07-28 17:00:23 | invalid | D

---

### **Actual Behavior**

* The current behavior is to throw error message

---

### PR DESCRIPTION
**Pull request by ahkcs**
### Description
When the bin command is applied to a non-numeric field (e.g., string) with numeric span parameters, the command fails with unclear Calcite type validation errors, making it difficult for users to identify the root cause

This PR Added clear validation in BinFieldValidator that throws SemanticCheckException with message,  Added field type checks in all numeric bin handlers before Calcite validation, providing clearer user-facing error messages

### Related Issues
Partially resolves #4590 

### Check List
- [x] New functionality includes testing.
- [x] New functionality has been documented.
 - [x] New functionality has javadoc added.
 - [x] New functionality has a user manual doc added.
- [ ] New PPL command [checklist](https://github.com/opensearch-project/sql/blob/main/docs/dev/ppl-commands.md) all confirmed.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff` or `-s`.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: core/src/main/java/org/opensearch/sql/calcite/utils/binning/BinFieldValidator.java [hunk 1]
```diff
@@ -59,4 +60,39 @@ public static boolean isTimeBasedField(RelDataType fieldType) {
...
+      throw new SemanticCheckException(
+          String.format(
+              "Cannot apply binning: field '%s' is non-numeric and not time-related, expected"
+                  + " numeric or time-related type",
+              fieldName));
+    }
+  }
+
+  /** Checks if the field type is numeric. */
+  private static boolean isNumericField(RelDataType fieldType) {
```
Comment (Swiddis) [inline core/src/main/java/org/opensearch/sql/calcite/utils/binning/BinFieldValidator.java]: thought: This is a pretty useful general utility outside of `bin`

Should we define it closer to where `SqlTypeName` is defined? We have lots of hand-rolled field logic for different commands and it's led to some issues when the type list change (e.g. OpenSearch recently introducing `TIMESTAMP_MICROS`).

File: core/src/main/java/org/opensearch/sql/calcite/utils/binning/BinFieldValidator.java [hunk 2]
```diff
@@ -59,4 +60,39 @@ public static boolean isTimeBasedField(RelDataType fieldType) {
     // Check if type string contains EXPR_TIMESTAMP
     return fieldType.toString().contains("EXPR_TIMESTAMP");
   }
+
+  /** Validates that the field type is numeric for numeric binning operations. */
+  public static void validateNumericField(RelDataType fieldType, String fieldName) {
```
Comment (Swiddis) [inline core/src/main/java/org/opensearch/sql/calcite/utils/binning/BinFieldValidator.java]: suggestion: Instead, load numeric fields into a data class that directly supports binning operations.

When we validate with a `void` method, we don't track any validation information in the type system, so we rely on downstream logic to "know" validation was run. It's easy to forget it or unnecessarily run it multiple times. If we instead put this validation in a constructor for a relevant class, and Bin uses this class, then the fact the class exists means we've definitely run validation.

This adds safety, makes these field operations easier to test, makes useful "numeric-field-only" operations more reusable, and simplifies the bin command's logic.

File: core/src/main/java/org/opensearch/sql/calcite/utils/binning/BinFieldValidator.java (hunk 1 above)
Comment (ahkcs) [reply core/src/main/java/org/opensearch/sql/calcite/utils/binning/BinFieldValidator.java]: Good suggestion! I've moved the type checking utilities to OpenSearchTypeFactory.  Future type additions (like TIMESTAMP_MICROS) will only need updates in one place

File: core/src/main/java/org/opensearch/sql/calcite/utils/binning/BinFieldValidator.java (hunk 2 above)
Comment (ahkcs) [reply core/src/main/java/org/opensearch/sql/calcite/utils/binning/BinFieldValidator.java]: Great suggestion! I've refactored to use a type-safe validation approach by creating a `BinnableField` class that validates in its constructor and updated all 5 bin handlers to use it.

File: core/src/main/java/org/opensearch/sql/calcite/utils/binning/BinnableField.java [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+              fieldName));
+    }
+  }
+
+  /**
+   * Returns true if this field requires numeric binning logic (not time-based binning).
+   *
+   * @return true if the field should use numeric binning, false if it should use time-based binning
+   */
+  public boolean requiresNumericBinning() {
```
Comment (ykmr1224) [inline core/src/main/java/org/opensearch/sql/calcite/utils/binning/BinnableField.java:61]: nit: This method was confusing to me. It might be better changing it to `isNumeric` is it is actually used to check if the field is numeric.

**Comment by ahkcs** [comment]
> QQ: what's the expected behavior? In PR description, semantic exception is expected. In issue #4590, the expectation is "the bin command should gracefully skip numeric binning for non-numeric fields and preserve the original field values instead of throwing an error." ?

Hi @dai-chen , this PR is for short-term fix to enhance error handling, our long-term goal would be the expected behavior in #4590

File: core/src/main/java/org/opensearch/sql/calcite/utils/binning/BinnableField.java (hunk 3 above)
Comment (ahkcs) [reply core/src/main/java/org/opensearch/sql/calcite/utils/binning/BinnableField.java:61]: Hi Tomo, this method exists because some parameters such as `minspan`, `start`, `end` currently don't support time-based binning, so they will use this method to check first

**Comment by LantaoJin** [comment]
@ahkcs backport required, thanks.
