### PR TITLE
Fix: correct ATAN(x, y) and CONV(x, a, b) functions bug

### LINKED ISSUE #3672: [BUG] `ATAN(x, y)` and `CONV(x, a, b)` functions not work with Calcite
**What is the bug?**
`ATAN(x, y)` and `CONV(x, a, b)` functions not work with Calcite

**How can one reproduce the bug?**
```
... | eval f = atan(2, 3) | fields f
... | eval f = conv(age, 10, 16) | fields f
```

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

### PR DESCRIPTION
**Pull request by ishaoxy**
### Description
Solved the bug that **ATAN(x, y)** function does not support two parameters in v3 version. Also fixed a bug in the **CONV(x, a, b)** function where incorrect type conversion caused unexpected results.

### Related Issues
Resolves #3672

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by LantaoJin** [comment]
@ishaoxy Remove these rows https://github.com/opensearch-project/sql/blob/270aa0dc3349e3a3c3b4e8e0e19c772f81c17781/integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteMathematicalFunctionIT.java#L20-L29
to enable the tests with your patch.

File: core/src/main/java/org/opensearch/sql/expression/function/PPLFuncImpTable.java [hunk 1]
```diff
@@ -531,6 +531,11 @@ void populate() {
                       builder.makeLiteral(" "),
                       arg),
               PPLTypeChecker.family(SqlTypeFamily.STRING)));
+      register(
+          ATAN,
```
Comment (dai-chen) [inline core/src/main/java/org/opensearch/sql/expression/function/PPLFuncImpTable.java:535]: Could you elaborate why we register ATAN2 as ATAN? I see both Calcite and SparkSQL has ATAN and ATAN2 separately: https://calcite.apache.org/docs/reference.html, https://spark.apache.org/docs/latest/api/sql/#atan

Comment (LantaoJin) [reply core/src/main/java/org/opensearch/sql/expression/function/PPLFuncImpTable.java:535]: ATAN can accept 2 arguments in v2 which is not existing in standard SQL, this PR is to align with v2 to avoid breaking changes. If you think it's unnecessary, we can delete it in v2 and comment ATAN will 2 arguments will not accept since 3.1.0.

**Review by LantaoJin — APPROVED** [review]

File: core/src/main/java/org/opensearch/sql/expression/function/PPLFuncImpTable.java (hunk 1 above)
Comment (dai-chen) [reply core/src/main/java/org/opensearch/sql/expression/function/PPLFuncImpTable.java:535]: I see. Sure, we can go ahead if we follow aligning with V2 criteria for all functions. Just feel this may cause unnecessary work in both Calcite and Spark. We can discuss later. Thanks!

**Review by dai-chen — APPROVED** [review]
