### PR TITLE
WIP: Array values are preserved (#1300)

### LINKED ISSUE #1300: [DISCUSSION] Properly support array values in new engine
## What is the bug?
The new engine does not return values in an array while the Legacy engine returns all values in a row as an array. Implementing same support as `V1` does isn't a right way, because legacy engine produces inconsistent value.

## How can one reproduce the bug?
1. Start OpenSearch server
2. Clean index if was created before: `curl -XDELETE 'http://localhost:9200/dbg'`
3. Create a simple index with automatic mapping: `curl -X POST "localhost:9200/dbg/_doc/?pretty" -H 'Content-Type: application/json' -d '{"myNum": 5}'`
4. Query data: `select * from dbg`. Not bas so far.
5. Add new doc: `curl -X POST "localhost:9200/dbg/_doc/?pretty" -H 'Content-Type: application/json' -d '{"myNum": [3, 4]}'`
6. Check mapping: `curl -X GET "localhost:9200/dbg?pretty"`
```json
"mappings" : {
  "properties" : {
	"myNum" : {
	  "type" : "long"
	}
  }
}
```
7. Query in the new engine: `curl -s -XPOST http://localhost:9200/_plugins/_sql -H 'Content-Type: application/json' -d '{"query": "select * from dbg"}'`
```json
{
  "schema": [
    {
      "name": "myNum",
      "type": "long"
    }
  ],
  "datarows": [
    [
      5
    ],
    [
      3
    ]
  ],
  "total": 2,
  "size": 2,
  "status": 200
}
```
(if you have only second doc in the index)
```json
"schema": [
    {
      "name": "myNum",
      "type": "long"
    }
  ],
  "datarows": [
    [
      3
    ],
    [
      4
    ]
  ]
```
8. Query in the legacy engine: `curl -s -XPOST http://localhost:9200/_plugins/_sql -H 'Content-Type: application/json' -d '{"query": "select * from dbg", "fetch_size": 20}'`
```json
{
  "schema": [
    {
      "name": "myNum",
      "type": "long"
    }
  ],
  "total": 2,
  "datarows": [
    [
      5
    ],
    [
      [
        3,
        4
      ]
    ]
  ],
  "size": 2,
  "status": 200
}
```

## What is the expected behavior?
**TBD**

### Why legacy response is incorrect?
It declares data type as long, but returns a number **and** array of numbers. Imagine a user has a parser for response, what should parser do with such values?
You can try our JDBC driver as an example of a customer application.

## What is your host/environment?
`main` @ 6108ca1a1

### PR DESCRIPTION
**Pull request by normanj-bitquill**
### Description
Preserve array values so that they are represented correctly in the result set with all nested values.

### Related Issues
Resolves #1300

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
 - [ ] New functionality has javadoc added.
 - [ ] New functionality has a user manual doc added.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [ ] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by normanj-bitquill** [comment]
I am still working on the code for making this configurable. The idea is to have a query parameter named `arrays` that is optional. If it is included, the only valid value is `preserve`.

If `arrays=preserve`, then arrays returned from the OpenSearch engine can flow to the result set and include all of the nested values.

**Review by penghuo — COMMENTED** [review]
1. could u add setting `plugins.query.field_type_tolerance`. If the plugins.query.field_type_tolerance setting is set to true, the backend will return scalar data types with array datasets, allowing basic queries like SELECT * FROM tbl WHERE condition; however, using multi-value fields in aggregations, ORDER BY clauses, or expressions will result in exceptions. If the setting is false or does not exist, only the first element of an array is returned, maintaining the current behavior.
2. could u add exception if operator/expression does not support array value, for instance groupby.

File: integ-test/src/test/java/org/opensearch/sql/legacy/ObjectFieldSelectIT.java [hunk 1]
```diff
@@ -81,7 +81,7 @@ public void testSelectObjectFieldOfArrayValuesItself() {
     JSONObject response = new JSONObject(query("SELECT accounts FROM %s"));
 
     // Only the first element of the list of is returned.
```
[the remark this answers is not in the document]
Comment (normanj-bitquill) [reply integ-test/src/test/java/org/opensearch/sql/legacy/ObjectFieldSelectIT.java:83]: Since the default behaviour is to only use the first element of an array, this comment is still valid.

File: opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java [hunk 2]
```diff
@@ -229,6 +229,13 @@ public class OpenSearchSettings extends Settings {
           Setting.Property.NodeScope,
           Setting.Property.Dynamic);
 
+  public static final Setting<?> FIELD_TYPE_TOLERANCE_SETTING =
+      Setting.boolSetting(
+          Key.FIELD_TYPE_TOLERANCE.getKeyValue(),
+          false,
```
Comment (penghuo) [inline opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java:235]: Set default = true. the reasons is most of user can get correct result ( similar to DSL response ). Even it is breaking current default behavior.

File: opensearch/src/main/java/org/opensearch/sql/opensearch/response/OpenSearchResponse.java [hunk 3]
```diff
@@ -48,27 +48,35 @@ public class OpenSearchResponse implements Iterable<ExprValue> {
...
   /** OpenSearchExprValueFactory used to build ExprValue from search result. */
   @EqualsAndHashCode.Exclude private final OpenSearchExprValueFactory exprValueFactory;
 
   /** Constructor of OpenSearchResponse. */
   public OpenSearchResponse(
       SearchResponse searchResponse,
       OpenSearchExprValueFactory exprValueFactory,
-      List<String> includes) {
+      List<String> includes,
+      boolean fieldTypeTolerance) {
```
Comment (penghuo) [inline opensearch/src/main/java/org/opensearch/sql/opensearch/response/OpenSearchResponse.java:61]: fieldTypeTolerance is not releated to OpenSearchResponse, Could we move this logic to OpenSearchExprValueFactory?

File: opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequest.java [hunk 4]
```diff
@@ -101,6 +103,21 @@ public OpenSearchQueryRequest(
     this.sourceBuilder = sourceBuilder;
     this.exprValueFactory = factory;
     this.includes = includes;
+    this.fieldTypeTolerance = false;
```
Comment (penghuo) [inline opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequest.java:106]: fieldTypeTolerance should not associate with OpenSearchRequest, It is been used when OpenSearchExprValueFactory parse response.?

File: integ-test/src/test/resources/expectedOutput/ppl/explain_filter_agg_push.json [hunk 5]
```diff
@@ -8,7 +8,7 @@
...
+          "request": "OpenSearchQueryRequest(indexName\u003dopensearch-sql_test_index_account, sourceBuilder\u003d{\"from\":0,\"size\":10000,\"timeout\":\"1m\",\"query\":{\"range\":{\"age\":{\"from\":30,\"to\":null,\"include_lower\":false,\"include_upper\":true,\"boost\":1.0}}},\"sort\":[{\"_doc\":{\"order\":\"asc\"}}],\"aggregations\":{\"composite_buckets\":{\"composite\":{\"size\":1000,\"sources\":[{\"state\":{\"terms\":{\"field\":\"state.keyword\",\"missing_bucket\":true,\"missing_order\":\"first\",\"order\":\"asc\"}}},{\"city\":{\"terms\":{\"field\":\"city.keyword\",\"missing_bucket\":true,\"missing_order\":\"first\",\"order\":\"asc\"}}}]},\"aggregations\":{\"avg_age\":{\"avg\":{\"field\":\"age\"}}}}}}, needClean\u003dtrue, searchDone\u003dfalse, pitId\u003dnull, cursorKeepAlive\u003dnull, searchAfter\u003dnull, searchResponse\u003dnull, fieldTypeTolerance\u003dfalse)"
```
Comment (penghuo) [inline integ-test/src/test/resources/expectedOutput/ppl/explain_filter_agg_push.json:11]: fieldTypeTolerance is not releated to OpenSearchQueryRequest.

**Review by penghuo — CHANGES_REQUESTED** [review]
Please update doc also https://github.com/opensearch-project/sql/blob/main/docs/user/admin/settings.rst

File: opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequest.java (hunk 4 above)
Comment (normanj-bitquill) [reply opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequest.java:106]: It is only here so that it can be passed down to the OpenSearchResponse. It is not used directly in OpenSearchRequest.

File: integ-test/src/test/resources/expectedOutput/ppl/explain_filter_agg_push.json (hunk 5 above)
Comment (normanj-bitquill) [reply integ-test/src/test/resources/expectedOutput/ppl/explain_filter_agg_push.json:11]: This was the only way I could see to pass the fieldTypeTolerance setting to OpenSearchResponse.

File: opensearch/src/main/java/org/opensearch/sql/opensearch/response/OpenSearchResponse.java (hunk 3 above)
Comment (normanj-bitquill) [reply opensearch/src/main/java/org/opensearch/sql/opensearch/response/OpenSearchResponse.java:61]: I can look, but making this change could take hours (with updating the affected tests).

File: opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java (hunk 2 above)
Comment (normanj-bitquill) [reply opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java:235]: OK.

File: integ-test/src/test/java/org/opensearch/sql/legacy/ObjectFieldSelectIT.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (normanj-bitquill) [reply integ-test/src/test/java/org/opensearch/sql/legacy/ObjectFieldSelectIT.java]: Removed the comment.

File: opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java (hunk 2 above)
Comment (normanj-bitquill) [reply opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java]: Default is now true.

File: opensearch/src/main/java/org/opensearch/sql/opensearch/response/OpenSearchResponse.java (hunk 3 above)
Comment (normanj-bitquill) [reply opensearch/src/main/java/org/opensearch/sql/opensearch/response/OpenSearchResponse.java]: Now it is passed through OpenSearchExprValueFactory

File: opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequest.java (hunk 4 above)
Comment (normanj-bitquill) [reply opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequest.java]: Updated.

File: integ-test/src/test/resources/expectedOutput/ppl/explain_filter_agg_push.json (hunk 5 above)
Comment (normanj-bitquill) [reply integ-test/src/test/resources/expectedOutput/ppl/explain_filter_agg_push.json]: Updated.

File: opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequest.java [hunk 6]
```diff
@@ -151,7 +153,8 @@ public OpenSearchQueryRequest(StreamInput in, OpenSearchStorageEngine engine) th
     }
 
     OpenSearchIndex index = (OpenSearchIndex) engine.getTable(null, indexName.toString());
-    exprValueFactory = new OpenSearchExprValueFactory(index.getFieldOpenSearchTypes());
+    exprValueFactory =
+        new OpenSearchExprValueFactory(index.getFieldOpenSearchTypes(), fieldTypeTolerance);
```
Comment (penghuo) [inline opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequest.java:157]: Logic should similar to OpenSearchScrollRequest right? If yes, fieldTypeTolerance should not associate with OpenSearchQueryRequest.

```
    OpenSearchIndex index = (OpenSearchIndex) engine.getTable(null, indexName.toString());
    exprValueFactory =
        new OpenSearchExprValueFactory(
            index.getFieldOpenSearchTypes(), index.isFieldTypeTolerance());
```

File: opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java [hunk 7]
```diff
@@ -74,6 +74,8 @@ public class OpenSearchExprValueFactory {
   /** The Mapping of Field and ExprType. */
   private final Map<String, OpenSearchDataType> typeMapping;
 
+  private final boolean fieldTypeTolerance;
```
Comment (penghuo) [inline opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java:77]: nit: add doc

File: opensearch/src/test/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactoryTest.java [hunk 8]
```diff
@@ -763,20 +824,31 @@ public void constructBinary() {
...
 
   /**
-   * Return the first element if is OpenSearch Array.
+   * Return the all elements if is OpenSearch Array.
    * https://www.elastic.co/guide/en/elasticsearch/reference/current/array.html.
    */
   @Test
-  public void constructFromOpenSearchArrayReturnFirstElement() {
-    assertEquals(integerValue(1), tupleValue("{\"intV\":[1, 2, 3]}").get("intV"));
+  public void constructFromOpenSearchArrayReturnAll() {
```
Comment (penghuo) [inline opensearch/src/test/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactoryTest.java:831]: we should also verify field_type_tolerance=false works.

File: opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScan.java [hunk 9]
```diff
@@ -47,14 +47,18 @@ public class OpenSearchIndexScan extends TableScanOperator implements Serializab
...
-  private Settings pluginSettings;
+  private boolean fieldTypeTolerance;
 
   /** Creates index scan based on a provided OpenSearchRequestBuilder. */
   public OpenSearchIndexScan(
-      OpenSearchClient client, int maxResponseSize, OpenSearchRequest request) {
+      OpenSearchClient client,
+      boolean fieldTypeTolerance,
+      int maxResponseSize,
+      OpenSearchRequest request) {
```
Comment (penghuo) [inline opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScan.java:57]: nit: we could keep original constructor which means fieldTypeTolerance=true, it could avoid unnecessary UT chagne.

File: opensearch/src/test/java/org/opensearch/sql/opensearch/response/OpenSearchResponseTest.java [hunk 10]
```diff
@@ -248,20 +251,15 @@ void iterator_metafields_scoreNaN() {
 
   @Test
   void iterator_with_inner_hits() {
+    Map<String, SearchHits> innerHits = new HashMap<>();
+    innerHits.put("a", mock(SearchHits.class));
+    when(searchHit1.getInnerHits()).thenReturn(innerHits);
```
Comment (penghuo) [inline opensearch/src/test/java/org/opensearch/sql/opensearch/response/OpenSearchResponseTest.java:256]: why change the mock?

File: integ-test/src/test/java/org/opensearch/sql/legacy/ObjectFieldSelectIT.java [hunk 11]
```diff
@@ -79,9 +79,7 @@ public void testSelectNestedFieldItself() {
   @Test
   public void testSelectObjectFieldOfArrayValuesItself() {
     JSONObject response = new JSONObject(query("SELECT accounts FROM %s"));
-
-    // Only the first element of the list of is returned.
-    verifyDataRows(response, rows(new JSONObject("{\"id\": 1}")));
+    verifyDataRows(response, rows(new JSONArray("[{\"id\":1},{\"id\":2}]")));
```
Comment (penghuo) [inline integ-test/src/test/java/org/opensearch/sql/legacy/ObjectFieldSelectIT.java:82]: could u test of field_type_tolerance=false

File: opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScan.java (hunk 9 above)
Comment (Swiddis) [reply opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScan.java:57]: +1. I'm also curious if it even needs to be a parameter since every refactor hardcodes it to `true` and the `false` case isn't even tested. What's the use case where we don't want this?

File: opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequest.java (hunk 6 above)
Comment (dai-chen) [reply opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequest.java:157]: maybe another option is to create `OpenSearchExprValueFactory` in request builder and pass it to request? In case factory needs more settings passed in future?

File: integ-test/src/test/java/org/opensearch/sql/ppl/StandaloneIT.java [hunk 12]
```diff
@@ -153,6 +153,7 @@ private Settings defaultSettings() {
           new ImmutableMap.Builder<Key, Object>()
               .put(Key.QUERY_SIZE_LIMIT, 200)
               .put(Key.SQL_PAGINATION_API_SEARCH_AFTER, true)
+              .put(Key.FIELD_TYPE_TOLERANCE, false)
```
Comment (dai-chen) [inline integ-test/src/test/java/org/opensearch/sql/ppl/StandaloneIT.java:156]: I can see some IT set it to true and some set it to false? Maybe most IT should stick with default setting and add dedicate IT to test the opposite?

File: opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java [hunk 13]
```diff
@@ -164,7 +168,7 @@ public ExprValue construct(String jsonString, boolean supportArrays) {
           new OpenSearchJsonContent(OBJECT_MAPPER.readTree(jsonString)),
           TOP_PATH,
           Optional.of(STRUCT),
-          supportArrays);
+          fieldTypeTolerance || supportArrays);
```
Comment (dai-chen) [inline opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java:171]: I'm thinking should we use `fieldTypeTolerance` directly in `parseArray` (not sure `parseGeopoint`)? Because I think `supportArrays` has its own meaning? Unless we change it and rename the argument?

**Review by dai-chen — COMMENTED** [review]
Please update documentation: https://github.com/opensearch-project/sql/blob/main/docs/user/admin/settings.rst

File: opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequest.java (hunk 6 above)
Comment (normanj-bitquill) [reply opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequest.java]: Updated.

File: opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java (hunk 7 above)
Comment (normanj-bitquill) [reply opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java:78]: Added a comment.

File: opensearch/src/test/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactoryTest.java (hunk 8 above)
Comment (normanj-bitquill) [reply opensearch/src/test/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactoryTest.java:831]: Added some tests for this.

File: opensearch/src/test/java/org/opensearch/sql/opensearch/response/OpenSearchResponseTest.java (hunk 10 above)
Comment (normanj-bitquill) [reply opensearch/src/test/java/org/opensearch/sql/opensearch/response/OpenSearchResponseTest.java:256]: The mock wasn't actually adding any inner hits before.

File: opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilder.java [hunk 14]
```diff
@@ -110,6 +110,7 @@ private OpenSearchRequest buildRequestWithPit(
     int size = requestedTotalSize;
     FetchSourceContext fetchSource = this.sourceBuilder.fetchSource();
     List<String> includes = fetchSource != null ? Arrays.asList(fetchSource.includes()) : List.of();
+    boolean fieldTypeTolerance = settings.getSettingValue(Settings.Key.FIELD_TYPE_TOLERANCE);
```
[the remark this answers is not in the document]
Comment (normanj-bitquill) [reply opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilder.java]: Removed.

File: opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java (hunk 13 above)
Comment (normanj-bitquill) [reply opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java:172]: This also applies to geopoints and anything else that could be in an array. If `fieldTypeTolerance` is not also applied to `parseGeopoint`, then an array of geopoints would get reduced to only the first element.

File: integ-test/src/test/java/org/opensearch/sql/ppl/StandaloneIT.java (hunk 12 above)
Comment (normanj-bitquill) [reply integ-test/src/test/java/org/opensearch/sql/ppl/StandaloneIT.java]: Changed this to `true` which is the default. There is another IT `ObjectFieldSelectIT.testSelectObjectFieldOfArrayValuesItselfNoFieldTypeTolerance` that tests with field type tolerance set to `false`.

**Review by penghuo — APPROVED** [review]
Thanks for the change!
Please update doc in following PR. https://github.com/opensearch-project/sql/blob/main/docs/user/admin/settings.rst

**Review by dai-chen — APPROVED** [review]
