### PR TITLE
Another TPCH fix: Wait for all shards

### LINKED ISSUE #4261: [BUG] CalcitePPLTpchIT is flaky
**What is the bug?**

TestQ1 is occasionally failing in main, e.g. https://github.com/opensearch-project/sql/actions/runs/17594180049/job/49982291692.

```
CalcitePPLTpchIT > testQ1 FAILED
    java.lang.AssertionError: 
    Expected: iterable with items [[], [], [], []] in any order
         but: not matched: <["A","F",37474,37569624.64,35676192.096999995,37101416.222424,25.354533152909337,25419.231826792962,0.0508660351826793,1478]>
        at __randomizedtesting.SeedInfo.seed([7DBF59379F8C433E:DF95364E8E9BEC79]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at org.opensearch.sql.util.MatcherUtils.verify(MatcherUtils.java:193)
        at org.opensearch.sql.util.MatcherUtils.verifyDataRows(MatcherUtils.java:160)
        at org.opensearch.sql.calcite.tpch.CalcitePPLTpchIT.testQ1(CalcitePPLTpchIT.java:59)
```

At a quick glance, seems like data is being fetched before a refresh runs.

**How can one reproduce the bug?**
With great care.

**What is the expected behavior?**
Should pass consistently.

**What is your host/environment?**
 - OS: Mac OS 13
 - Java 24

**Do you have any screenshots?**
N/A

**Do you have any additional context?**
N/A

### LINKED ISSUE #5103: [AUTOCUT] Integration Test Failed for sql-3.5.0
#### Details

| Platform | Dist | Arch | Dist Build No. | RC | Test Report | Workflow Run | Failing tests |
|----------|------|------|----------------|----|-------------|--------------|---------------|
| linux | deb | arm64 | 11664 | 5 | https://ci.opensearch.org/ci/dbc/integ-test/3.5.0/11664/linux/arm64/deb/test-results/10899/integ-test/test-report.yml | https://build.ci.opensearch.org/job/integ-test/10899/display/redirect | [Check metrics](https://metrics.opensearch.org/_dashboards/app/dashboards?security_tenant=global#/view/21aad140-49f6-11ef-bbdd-39a9b324a5aa?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-30d,to:now))&_a=(description:'OpenSearch%20Release%20Build%20and%20Integration%20Test%20Results',expandedPanelId:7a6ee111-1c99-4f96-9a3f-c0f248181980,filters:!(('':(store:appState),meta:(alias:!n,disabled:!f,index:d90d2ba0-8fe0-11ef-a168-f19b1bbc360c,key:version,negate:!f,params:(query:'3.5.0'),type:phrase),query:(match_phrase:(version:'3.5.0'))),('':(store:appState),meta:(alias:!n,disabled:!f,index:d90d2ba0-8fe0-11ef-a168-f19b1bbc360c,key:component,negate:!f,params:(query:sql),type:phrase),query:(match_phrase:(component:sql)))),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'OpenSearch%20Release%20Build%20and%20Integration%20Test%20Results',viewMode:view)) |
| linux | rpm | arm64 | 11664 | 5 | https://ci.opensearch.org/ci/dbc/integ-test/3.5.0/11664/linux/arm64/rpm/test-results/10898/integ-test/test-report.yml | https://build.ci.opensearch.org/job/integ-test/10898/display/redirect | [Check metrics](https://metrics.opensearch.org/_dashboards/app/dashboards?security_tenant=global#/view/21aad140-49f6-11ef-bbdd-39a9b324a5aa?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-30d,to:now))&_a=(description:'OpenSearch%20Release%20Build%20and%20Integration%20Test%20Results',expandedPanelId:eae6bad4-cffc-4672-a688-14155229ea63,filters:!(('':(store:appState),meta:(alias:!n,disabled:!f,index:d90d2ba0-8fe0-11ef-a168-f19b1bbc360c,key:version,negate:!f,params:(query:'3.5.0'),type:phrase),query:(match_phrase:(version:'3.5.0'))),('':(store:appState),meta:(alias:!n,disabled:!f,index:d90d2ba0-8fe0-11ef-a168-f19b1bbc360c,key:component,negate:!f,params:(query:sql),type:phrase),query:(match_phrase:(component:sql)))),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'OpenSearch%20Release%20Build%20and%20Integration%20Test%20Results',viewMode:view)) |
| linux | tar | arm64 | 11664 | 5 | https://ci.opensearch.org/ci/dbc/integ-test/3.5.0/11664/linux/arm64/tar/test-results/10897/integ-test/test-report.yml | https://build.ci.opensearch.org/job/integ-test/10897/display/redirect | [Check metrics](https://metrics.opensearch.org/_dashboards/app/dashboards?security_tenant=global#/view/21aad140-49f6-11ef-bbdd-39a9b324a5aa?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-30d,to:now))&_a=(description:'OpenSearch%20Release%20Build%20and%20Integration%20Test%20Results',expandedPanelId:c570bdfd-3122-4e31-a02d-2130d797d9fc,filters:!(('':(store:appState),meta:(alias:!n,disabled:!f,index:d90d2ba0-8fe0-11ef-a168-f19b1bbc360c,key:version,negate:!f,params:(query:'3.5.0'),type:phrase),query:(match_phrase:(version:'3.5.0'))),('':(store:appState),meta:(alias:!n,disabled:!f,index:d90d2ba0-8fe0-11ef-a168-f19b1bbc360c,key:component,negate:!f,params:(query:sql),type:phrase),query:(match_phrase:(component:sql)))),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'OpenSearch%20Release%20Build%20and%20Integration%20Test%20Results',viewMode:view)) |

Check out test report manifest linked above for steps to reproduce, cluster and integration test failure logs. For additional information checkout the [wiki](https://github.com/opensearch-project/opensearch-build/wiki/Testing-the-Distribution) and [OpenSearch Metrics Dashboard](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/21aad140-49f6-11ef-bbdd-39a9b324a5aa).

### PR DESCRIPTION
**Pull request by Swiddis**
### Description
TPCH is flaky again in CI (#5103 / #4261), but I haven't seen it failing in `main` for a while and I see we have the workaround that waits for docs to be reported.

I _think_ the situation is that the CI server is running a multi-node integ test, while our ITs normally are single-node. For multiple nodes, it may be the case that one node reports documents while the other doesn't. On that hypothesis, this change forces the tests to wait for all shards to accept new documents.

I tried just `wait_for_active_shards=all` but this causes integ tests to hang on single-node setups because there's nowhere to put the replica. So in addition I added a helper that sets the replica count to 0 on integ test indices, which should fix both the waiting issue and the above routing issue.

### Related Issues
Resolves #5103
Resolves #4261 (I hope)

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
 - [ ] New functionality has javadoc added.
 - [ ] New functionality has a user manual doc added.
- [ ] New PPL command [checklist](https://github.com/opensearch-project/sql/blob/main/docs/dev/ppl-commands.md) all confirmed.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [ ] Commits are signed per the DCO using `--signoff` or `-s`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Swiddis** [comment]
nvm, this hangs because it waits forever for replicas on a single node. But I can work around that...

File: integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java [hunk 1]
```diff
@@ -210,19 +210,6 @@ protected synchronized void loadIndex(Index index, RestClient client) throws IOE
...
-    // https://github.com/opensearch-project/sql/issues/4261
-    int countDown = 3; // 1500ms timeout
-    while (countDown != 0 && getDocCount(client, indexName) == 0) {
-      try {
-        Thread.sleep(500);
-        countDown--;
-      } catch (InterruptedException e) {
-        throw new IOException(e);
-      }
-    }
```
Comment (LantaoJin) [inline integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java:225]: for safety, I think we can keep this logic to mitigate the impacts.

Comment (Swiddis) [reply integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java:225]: This logic also caused build fleet testing times to go from 2 hours to 5 hours (which I think means it was broken in general), we should avoid hardcoded sleep durations anyway if we need to have some sort of check. At worst maybe a retry policy directly on the TPCH ITs.
