### PR TITLE
Datetime aggregation fixes.

### LINKED ISSUE #645: [BUG] Aggregate on date function does not work as expected
**What is the bug?**
```
PUT {{baseUrl}}/test_00001/
Content-Type: application/json

{
  "settings": {
    "index": {
      "number_of_shards": 1,
      "number_of_replicas": 0
    }
  },
  "mappings": {
    "properties": {
      "date": {
        "type": "keyword"
      },
      "status": {
        "type": "integer"
      }   
    }
  }
}

curl -XPOST "http://localhost:9200/_bulk?refresh=true" -H 'Content-Type: application/json' -d'
{ "index" : { "_index" : "test_00001", "_id" : "1" } }
{ "date" : "2022-01-01", "status" : 1}
{ "index" : { "_index" : "test_00001", "_id" : "2" } }
{ "date" : "2022-02-01", "status" : 2}
{ "index" : { "_index" : "test_00001", "_id" : "3" } }
{ "date" : "2022-03-01", "status" : 3}
{ "index" : { "_index" : "test_00001", "_id" : "4" } }
{ "date" : "2022-04-01", "status" : 2}
'

POST {{baseUrl}}/_plugins/_sql
Content-Type: application/json

{
  "query": "SELECT min(date(date)) FROM test_00001 GROUP BY status"
}

{
  "error": {
    "type": "SearchPhaseExecutionException",
    "reason": "Error occurred in OpenSearch engine: all shards failed",
    "details": "Shard[0]: AggregationExecutionException[Unsupported script value [2022-01-01], expected a number, date, or boolean]\n\nFor more details, please send request for Json format to see the raw response from OpenSearch engine."
  },
  "status": 503
}
```

### PR DESCRIPTION
**Pull request by Yury-Fridlyand**
Signed-off-by: Yury-Fridlyand <yuryf@bitquilltech.com>

### Description
Make listed aggregations work with datetime types.
Please, see team review and discussion in https://github.com/Bit-Quill/opensearch-project-sql/pull/144.

#### Fixes
* `min`
* `max`
* `avg`

#### Not included
* `var_samp`
* `var_pop`
* `stddev_samp`
* `stddev_pop`
* `sum` [1]

#### Presicion
Aggregation done with milliseconds precision - this follows OpenSearch approach. See code snippets: [one](https://github.com/opensearch-project/OpenSearch/blob/140e8d3e6c91519edc47be07b4cd053fdfac1769/server/src/main/java/org/opensearch/search/aggregations/support/values/ScriptDoubleValues.java#L71-L76), [two](https://github.com/opensearch-project/OpenSearch/blob/140e8d3e6c91519edc47be07b4cd053fdfac1769/server/src/main/java/org/opensearch/search/aggregations/support/values/ScriptDoubleValues.java#L109-L115).
We convert datetimes to millis and back on our own (see below), so we can scale up to nanoseconds. Such fix requires additional changes - few tests fail.

#### `ExpressionAggregationScript::execute`
A callback function, called by OpenSearch node to extract a value during processing aggregation script.
This added for backward compatibility:
https://github.com/Bit-Quill/opensearch-project-sql/blob/272bf67c9009727a7ce24958b58f0357f4e1dc4e/opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/aggregation/ExpressionAggregationScript.java#L53-L55
This - to extract value. Fortunately, `toEpochMilli()` returns negative values for pre-Epoch timestamps, so we are able to use it for group/compare any values.
https://github.com/Bit-Quill/opensearch-project-sql/blob/272bf67c9009727a7ce24958b58f0357f4e1dc4e/opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/aggregation/ExpressionAggregationScript.java#L56-L67
OpenSearch accepts dates in `Joda` lib types and converts to milliseconds since Epoch. We have java datetime types, to I do conversion there.
https://github.com/opensearch-project/OpenSearch/blob/140e8d3e6c91519edc47be07b4cd053fdfac1769/server/src/main/java/org/opensearch/search/aggregations/support/values/ScriptDoubleValues.java#L123

#### `BucketAggregationBuilder::buildCompositeValuesSourceBuilder`
To properly process datetime types it is required to provide a hint to the engine.
https://github.com/opensearch-project/sql/blob/3a902ef7677e942f3c55b90ea44f303111aa416e/opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/BucketAggregationBuilder.java#L73-L76

#### `ExprValueUtils`
These two methods used by `avg` in-memory aggregation for datetime types.
https://github.com/Bit-Quill/opensearch-project-sql/blob/272bf67c9009727a7ce24958b58f0357f4e1dc4e/core/src/main/java/org/opensearch/sql/data/model/ExprValueUtils.java#L190
https://github.com/Bit-Quill/opensearch-project-sql/blob/272bf67c9009727a7ce24958b58f0357f4e1dc4e/core/src/main/java/org/opensearch/sql/data/model/ExprValueUtils.java#L213

#### `AvgAggregator`
1. Added new field to store which type is being aggregated
2. `AvgState` was renamed to `DoubleAvgState`
3. `DateTimeAvgState` does the same logic, but for datetime types.
https://github.com/Bit-Quill/opensearch-project-sql/blob/272bf67c9009727a7ce24958b58f0357f4e1dc4e/core/src/main/java/org/opensearch/sql/expression/aggregation/AvgAggregator.java#L105-L117
4. Added abstract class `AvgState`

#### `AggregatorFunction`
New signature were added.
https://github.com/Bit-Quill/opensearch-project-sql/blob/272bf67c9009727a7ce24958b58f0357f4e1dc4e/core/src/main/java/org/opensearch/sql/expression/aggregation/AggregatorFunction.java#L69-L76
Actually, plugin was able to do push down aggregation on datetime types, but this weren't accepted.

[1] It works on MySQL, but I don't see any reason to implement this for datetime types.

#### In-memory aggregation
https://github.com/Bit-Quill/opensearch-project-sql/blob/17e1ae98bd7e403bc94043a607ae1993d5062422/integ-test/src/test/java/org/opensearch/sql/sql/AggregationIT.java#L196-L199
```sql
SELECT avg(CAST(time1 AS time)) OVER(PARTITION BY datetime1) from calcs;
```
(cast required to ensure that you're working with `TIME`).
To try other types, use
```sql
CAST(date0 AS date)            
datetime(CAST(time0 AS STRING))
CAST(time1 AS time)            
CAST(datetime0 AS timestamp)   
```

#### Push Down aggregation (`metric`)
```sql
SELECT min(CAST(date0 AS date)) from calcs;
```

#### Push Down aggregation (`composite_buckets`)
```sql
SELECT CAST(datetime0 AS timestamp) FROM calcs GROUP BY 1;
```

### Issues Resolved
Fixes #645
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass, including unit test, integration test and doctest
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
  - [x] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by MitchellGale-BitQuill — DISMISSED** [review]

File: core/src/main/java/org/opensearch/sql/expression/aggregation/AvgAggregator.java [hunk 1]
```diff
@@ -23,20 +24,36 @@
...
 
   @Override
   public AvgState create() {
-    return new AvgState();
+    switch (dataType) {
+      case DATE:
+      case DATETIME:
+      case TIMESTAMP:
+      case TIME:
+        return new DateTimeAvgState(dataType);
```
Comment (dai-chen) [inline core/src/main/java/org/opensearch/sql/expression/aggregation/AvgAggregator.java:45]: Is it a little cleaner if we have different `AvgState` class? The reason is although we create single `DateTimeAvgState` here, they behave different in `result()` and `iterate()`. So there is more `switch` in `ExprValueUtils.extractEpochMilliFromAnyDateTimeType` and `ExprValueUtils. convertEpochMilliToDateTimeType`.

File: core/src/main/java/org/opensearch/sql/expression/aggregation/AvgAggregator.java [hunk 2]
```diff
@@ -47,18 +64,56 @@ public String toString() {
...
+      if (count == 0) {
+        return ExprNullValue.of();
+      }
+      return ExprValueUtils.convertEpochMilliToDateTimeType(Math.round(total / count), dataType);
+    }
+
+    @Override
+    protected AvgState iterate(ExprValue value) {
+      total += ExprValueUtils.extractEpochMilliFromAnyDateTimeType(value);
+      return super.iterate(value);
```
Comment (dai-chen) [inline core/src/main/java/org/opensearch/sql/expression/aggregation/AvgAggregator.java:116]: An improvement I'm thinking in https://github.com/opensearch-project/sql/pull/1045 recently is can we build our physical operator based on expression system and avoid using native Java as much as possible. If we can treat our expression system as a higher level language than Java, we can avoid many logic already implemented in our expr value and functions, such as explicit/implicit conversion, arithmetic and lots of other operations.

For example, can we do it in this way:

```
class AvgState:
   total = doubleValue(0.0)
   count = integerValue(0)

  def iterate(value: ExprValue):
    count = DSL.add(count, integerValue(1))
    total = DSL.add(total, value) // specific ExprValue is responsible for converting itself to ExprDoubleValue
```

Comment (Yury-Fridlyand) [reply core/src/main/java/org/opensearch/sql/expression/aggregation/AvgAggregator.java:116]: Thanks for the idea. I'll have a look and check how can I update this after #1045.

Comment (dai-chen) [reply core/src/main/java/org/opensearch/sql/expression/aggregation/AvgAggregator.java:116]: Sure. Just some thought. I'm working on https://github.com/opensearch-project/sql/pull/1045 and checking if I can re-publish it to 2.x once done. Thanks!

Comment (Yury-Fridlyand) [reply core/src/main/java/org/opensearch/sql/expression/aggregation/AvgAggregator.java:116]: `result` function should return an `ExprValue`:
https://github.com/opensearch-project/sql/blob/e280866ad6a248e852528326ecf568c95b4958a2/core/src/main/java/org/opensearch/sql/expression/aggregation/AggregationState.java#L15-L19

Are you planning to update all aggregators to return `Expression` instead of `ExprValue`?
Without changing the interface, implementation looks like
```
def result():
  return DSL.divide(total, count).valueOf();
```

Is ok for now? I feel that we are loosing all benefits of `DSL` because we switch down to java.

**Comment by Yury-Fridlyand** [comment]
Please, see fix in 8ff4298b0.

File: core/src/main/java/org/opensearch/sql/expression/aggregation/AvgAggregator.java (hunk 2 above)
Comment (dai-chen) [reply core/src/main/java/org/opensearch/sql/expression/aggregation/AvgAggregator.java]: Sorry I mixed the Expression and ExprValue in the sample code above. Here is what I was thinking about. Let me know how you feel implement our physical operator in this way.

```
class AvgState:
   total = doubleValue(0.0)
   count = integerValue(0)

  def iterate(value: ExprValue):
    count = DSL.add(DSL.literal(count), DSL.literal(1)).valueOf()
    total = DSL.add(DSL.literal(total), DSL.castToDouble(DSL.literal(value))).valueOf()

  def result():
    return DSL.divide(DSL.literal(total), DSL.literal(count)).valueOf()
```

File: core/src/main/java/org/opensearch/sql/expression/aggregation/AvgAggregator.java (hunk 1 above)
Comment (dai-chen) [reply core/src/main/java/org/opensearch/sql/expression/aggregation/AvgAggregator.java]: Yes, I'm thinking build higher level operator on top of our expression value system. Please see new sample code below.

File: core/src/main/java/org/opensearch/sql/expression/aggregation/AvgAggregator.java (hunk 2 above)
Comment (Yury-Fridlyand) [reply core/src/main/java/org/opensearch/sql/expression/aggregation/AvgAggregator.java]: Updated in c7734442e.

Comment (Yury-Fridlyand) [reply core/src/main/java/org/opensearch/sql/expression/aggregation/AvgAggregator.java]: > Are you planning to update all aggregators to return `Expression` instead of `ExprValue`?

This will make all in-memory aggregation to use DSL. Probably this bring a benefit for Analyzer and/or Optimizer in future.
Please, create a follow-up task if you feel we need to do this.

**Review by dai-chen — APPROVED** [review]
Thanks for the changes! 

Minor comment: I just realized that our cast function doesn't accept `ExprType`, so the switch in `AvgAggregator` is required. Besides improving cast function, probably one thing we can do now is to pass a cast function to an unique `AvgState` class. For example, in switch statement, pass `DSL::castToTimestamp`, `DSL::castToDouble` accordingly etc. I think the `Instant.ofEpochMilli()` call in each `AvgState` should be part of cast function from double to timestmap/date/time etc?

We can do it later if it makes sense and if you want. Thanks!

**Comment by Yury-Fridlyand** [comment]
> Minor comment: I just realized that our cast function doesn't accept `ExprType`, so the switch in `AvgAggregator` is required. Besides improving cast function, probably one thing we can do now is to pass a cast function to an unique `AvgState` class. For example, in switch statement, pass `DSL::castToTimestamp`, `DSL::castToDouble` accordingly etc. I think the `Instant.ofEpochMilli()` call in each `AvgState` should be part of cast function from double to timestmap/date/time etc?

Just to confirm - do you want to add new cast `LONG`/`DOUBLE` to all datetime types? Then to call it in `AvgState::result()` implementations.

**Review by dai-chen — DISMISSED** [review]

File: docs/user/dql/aggregations.rst [hunk 3]
```diff
@@ -182,7 +182,7 @@ AVG
 Description
 >>>>>>>>>>>
 
-Usage: AVG(expr). Returns the average value of expr.
+Usage: AVG(expr). Returns the average value of `expr`. `expr` could be of any of the numeric and datetime data types. Datetime aggregation perfomed with milliseconds precision.
```
Comment (MaxKsyunz) [inline docs/user/dql/aggregations.rst:185]:
```suggestion
Usage: AVG(expr). Returns the average value of `expr`. `expr` can be any numeric or datetime data type. Datetime aggregation is performed with milliseconds precision.
```

File: docs/user/dql/aggregations.rst [hunk 4]
```diff
@@ -201,7 +201,7 @@ MAX
 Description
 >>>>>>>>>>>
 
-Usage: MAX(expr). Returns the maximum value of expr.
+Usage: MAX(expr). Returns the maximum value of `expr`. `expr` could be of any of the numeric and datetime data types. Datetime aggregation perfomed with milliseconds precision.
```
Comment (MaxKsyunz) [inline docs/user/dql/aggregations.rst:204]:
```suggestion
Usage: MAX(expr). Returns the maximum value of `expr`. `expr` can be any numeric or datetime data type. Datetime aggregation is performed with milliseconds precision.
```

File: docs/user/dql/aggregations.rst [hunk 5]
```diff
@@ -219,7 +219,7 @@ MIN
 Description
 >>>>>>>>>>>
 
-Usage: MIN(expr). Returns the minimum value of expr.
+Usage: MIN(expr). Returns the minimum value of `expr`. `expr` could be of any of the numeric and datetime data types. Datetime aggregation perfomed with milliseconds precision.
```
Comment (MaxKsyunz) [inline docs/user/dql/aggregations.rst:222]:
```suggestion
Usage: MIN(expr). Returns the minimum value of `expr`. `expr` can be any numeric or datetime data type. Datetime aggregation is performed with milliseconds precision.
```

File: opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/aggregation/ExpressionAggregationScript.java [hunk 6]
```diff
@@ -42,7 +49,22 @@ public ExpressionAggregationScript(
...
   public Object execute() {
-    return expressionScript.execute(this::getDoc, this::evaluateExpression).value();
+    var expr = expressionScript.execute(this::getDoc, this::evaluateExpression);
+    if (expr.type() instanceof OpenSearchDataType) {
+      return expr.value();
+    }
+    switch ((ExprCoreType)expr.type()) {
+      case TIME:
+        // workaround for session context issue
+        // TODO remove once fixed
```
Comment (MaxKsyunz) [inline opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/aggregation/ExpressionAggregationScript.java:59]: Can you explain what the issue is? Link to any relevant github issues or PRs?

**Review by dai-chen — DISMISSED** [review]

File: opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/aggregation/ExpressionAggregationScript.java (hunk 6 above)
Comment (Yury-Fridlyand) [reply opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/aggregation/ExpressionAggregationScript.java]: Fixed in af13d834d.

File: core/src/main/java/org/opensearch/sql/expression/aggregation/AvgAggregator.java [hunk 7]
```diff
@@ -47,18 +75,117 @@ public String toString() {
...
+      }
+
+      return new ExprDateValue(
+          new ExprTimestampValue(Instant.ofEpochMilli(
+              DSL.divide(DSL.literal(total), DSL.literal(count)).valueOf().longValue()))
+                  .dateValue());
+    }
+
+    @Override
+    protected AvgState iterate(ExprValue value) {
```
Comment (penghuo) [inline core/src/main/java/org/opensearch/sql/expression/aggregation/AvgAggregator.java:126]: is it possible to reuse `DSL.adddate()`?

Comment (Yury-Fridlyand) [reply core/src/main/java/org/opensearch/sql/expression/aggregation/AvgAggregator.java:126]: Yes, but `DateAvgState` will be less clear and readable:
```java
  protected static class DateAvgState extends AvgState {

    public DateAvgState() {
      this.count = new ExprIntegerValue(0);
      this.total = new ExprDateValue(LocalDate.EPOCH);
    }

    @Override
    public ExprValue result() {
      if (0 == count.integerValue()) {
        return ExprNullValue.of();
      }

      return DSL.adddate(DSL.literal(new ExprDateValue(LocalDate.EPOCH)), 
          DSL.literal(DSL.divide(DSL.literal(DAYS.between(LocalDate.EPOCH, total.dateValue())),
              DSL.literal(count)).valueOf().longValue())).valueOf();
    }

    @Override
    protected AvgState iterate(ExprValue value) {
      total = DSL.adddate(DSL.literal(total),
          DSL.literal(DAYS.between(LocalDate.EPOCH, value.dateValue())))
          .valueOf();

      return super.iterate(value);
    }
  }
```

File: core/src/main/java/org/opensearch/sql/expression/aggregation/AvgAggregator.java [hunk 8]
```diff
@@ -23,20 +32,39 @@
...
   public AvgAggregator(List<Expression> arguments, ExprCoreType returnType) {
     super(BuiltinFunctionName.AVG.getName(), arguments, returnType);
+    dataType = returnType;
   }
 
   @Override
   public AvgState create() {
-    return new AvgState();
+    switch (dataType) {
+      case DATE:
```
[the remark this answers is not in the document]
Comment (Yury-Fridlyand) [reply core/src/main/java/org/opensearch/sql/expression/aggregation/AvgAggregator.java:49]: Well, meaning is almost the same as `avg(datetime)` or `avg(time)` has - something like to find average age or something/somebody.
I added this because:
* OpenSearch supports `avg(date)` aggregation, but we don't always pushdown aggregations to the engine. In that case we have to do this in memory.
* MySQL supports it and we're trying to align with it too.

There is no storable `INTERVAL` type in OpenSearch, and SQL has no function which returns it. There is no combination of query-dataset which will involve `avg(interval)`.

**Comment by MaxKsyunz** [comment]
@Yury-Fridlyand it makes sense to switch base branch to `main` and then use backport to merge it to 2.x branch.

File: opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/BucketAggregationBuilder.java [hunk 9]
```diff
@@ -64,6 +70,10 @@ private CompositeValuesSourceBuilder<?> buildCompositeValuesSourceBuilder(
               .missingBucket(true)
               .missingOrder(missingOrder)
               .order(sortOrder);
+      // Time types values are converted to LONG in ExpressionAggregationScript::execute
+      if (List.of(TIMESTAMP, TIME, DATE, DATETIME).contains(expr.getDelegated().type())) {
```
[the remark this answers is not in the document]
Comment (Yury-Fridlyand) [reply opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/BucketAggregationBuilder.java:74]: No, because I check whether type is one of TIMESTAMP, TIME, DATE, DATETIME

**Review by penghuo — APPROVED** [review]

**Review by dai-chen — DISMISSED** [review]
Thanks for the fix!

**Review by dai-chen — APPROVED** [review]

**Review by MaxKsyunz — APPROVED** [review]

File: core/src/main/java/org/opensearch/sql/expression/aggregation/AvgAggregator.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (Yury-Fridlyand) [reply core/src/main/java/org/opensearch/sql/expression/aggregation/AvgAggregator.java:49]: As it was discussed outside of GH, it was decided to proceed with this feature.
