### PR TITLE
Fix search anoymizer only

### LINKED ISSUE #4290: [BUG] PPLAnonymizer logging  is not logging the exact user given search command.
** Issues **

1. In the current state, processed query is being logged instead of anonymized raw query from customer. Eg: `source = index field=vamsi` ----> `source = index field:***`. Ideal log: `source = index field=***`

2. `searchLiterals are not handled properly in PPLDataAnonymizer.`

3. Anonymizer is the only reason for introducing search node. Rethink and revamp search node. where ever possible.

### PR DESCRIPTION
**Pull request by xinyual**
### Description
The pr fix the PPLQueryDataAnonymizer's bug about search command.

### Related Issues
Resolves #4290 

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
 - [ ] New functionality has javadoc added.
 - [ ] New functionality has a user manual doc added.
- [ ] New PPL command [checklist](https://github.com/opensearch-project/sql/blob/main/docs/dev/ppl-commands.md) all confirmed.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff` or `-s`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java [hunk 1]
```diff
@@ -879,7 +879,7 @@ private String anonymizeStatement(String query, boolean isExplain) {
   @Test
   public void testSearchWithAbsoluteTimeRange() {
     assertEquals(
-        "source=table (@timestamp:*** AND (@timestamp:***",
+        "source=table (identifier >= ***) AND (identifier <= ***)",
```
Comment (yuancu) [inline ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java]: Can you include more test cases to cover group, in, not, and or?

File: core/src/test/java/org/opensearch/sql/ast/tree/SearchTest.java [hunk 2]
```diff
@@ -29,7 +29,7 @@ public class SearchTest {
   public void setUp() {
     mockChild = mock(UnresolvedPlan.class);
     testQueryString = "field1:value1 AND field2:value2";
-    search = new Search(mockChild, testQueryString);
+    search = new Search(mockChild, testQueryString, null);
```
Comment (yuancu) [inline core/src/test/java/org/opensearch/sql/ast/tree/SearchTest.java]: Maybe it's better to create two constructors to avoid assigning null for use cases that do not need original `SearchExpression`: one with child and query string, another with child, query string, and original search expression

File: core/src/main/java/org/opensearch/sql/ast/tree/Search.java [hunk 3]
```diff
@@ -12,19 +12,22 @@
...
+@EqualsAndHashCode(onlyExplicitlyIncluded = true, callSuper = false)
 @RequiredArgsConstructor
 public class Search extends UnresolvedPlan {
 
-  private final UnresolvedPlan child;
-  private final String queryString;
+  @EqualsAndHashCode.Include private final UnresolvedPlan child;
+  @EqualsAndHashCode.Include private final String queryString;
+
+  private final SearchExpression originalExpression;
```
Comment (yuancu) [inline core/src/main/java/org/opensearch/sql/ast/tree/Search.java]: I think it can be `@Nullable`, with comments like `original expression is only used for anomanyzer tests`

**Review by yuancu — APPROVED** [review]

File: ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java (hunk 1 above)
Comment (xinyual) [reply ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java]: Already add one.

File: core/src/test/java/org/opensearch/sql/ast/tree/SearchTest.java (hunk 2 above)
Comment (xinyual) [reply core/src/test/java/org/opensearch/sql/ast/tree/SearchTest.java]: Already add one.

File: core/src/main/java/org/opensearch/sql/ast/tree/Search.java (hunk 3 above)
Comment (xinyual) [reply core/src/main/java/org/opensearch/sql/ast/tree/Search.java]: Already add.

File: ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java [hunk 4]
```diff
@@ -879,10 +879,37 @@ private String anonymizeStatement(String query, boolean isExplain) {
...
+        anonymize(
+            "search (severityText=\"ERROR\" OR severityText=\"WARN\") AND severityNumber>10"
+                + " source=t"));
+  }
+
+  @Test
+  public void testSearchWithOr() {
+    assertEquals(
+        "source=table (identifier >= *** OR identifier <= ***)",
+        anonymize("search source=t earliest='2012-12-10 15:00:00' or latest=now"));
```
Comment (LantaoJin) [inline ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java]: It's odd that the `=` anonymized to `>=` and  `<=`. It changes the semantic IMO.

Comment (LantaoJin) [reply ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java]: Change to such as `time_identifier`?
For meta fields such as `_id`, `_doc` etc, how about anonymize to `meta_identifier`?

Comment (xinyual) [reply ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java]: Already add `time_identifier` with `meta_identifier`. Please check it.

**Review by yuancu — APPROVED** [review]
