### PR TITLE
Do not remove nested fields in resolving AllFieldsExcludeMeta

### LINKED ISSUE #4575: [BUG] Nested struct fields cannot be accessed in PPL join results - ClassCastException
## Query Information

**PPL Command/Query:**
```ppl
source=test-nested-join 
| where ISPRESENT(unmapped.additionalEventData.CipherSuite) 
| eval copyCipher=unmapped.additionalEventData.CipherSuite 
| join type=inner left=ALL, right=CIPHER ON ALL.copyCipher = CIPHER.MostUsedCipher 
[
  source=test-nested-join 
  | rename unmapped.additionalEventData.CipherSuite as MostUsedCipher 
  | where ISPRESENT(MostUsedCipher) 
  | fields MostUsedCipher 
  | top MostUsedCipher
] 
| fields time, api.service.name, unmapped.additionalEventData.CipherSuite
```

**Expected Result:**
The query should successfully project nested struct fields from join results, returning:
```json
{
  "schema": [
    {"name": "time", "type": "timestamp"},
    {"name": "api.service.name", "type": "string"},
    {"name": "unmapped.additionalEventData.CipherSuite", "type": "string"}
  ],
  "datarows": [
    ["2025-10-15 10:00:00", "ServiceA", "TLS_AES_128_GCM_SHA256"],
    ["2025-10-15 11:00:00", "ServiceB", "TLS_AES_256_GCM_SHA384"],
    ...
  ]
}
```

**Actual Result:**
```json
{
  "error": {
    "reason": "There was internal problem at backend",
    "details": "java.sql.SQLException: exception while executing query: class java.util.LinkedHashMap cannot be cast to class org.apache.calcite.avatica.util.ByteString (java.util.LinkedHashMap is in module java.base of loader 'bootstrap'; org.apache.calcite.avatica.util.ByteString is in unnamed module of loader java.net.FactoryURLClassLoader)",
    "type": "RuntimeException"
  },
  "status": 500
}
```

## Dataset Information

**Dataset/Schema Type**
- [x] Custom (details below)

**Index Mapping**
```json
{
  "mappings": {
    "properties": {
      "time": { "type": "date" },
      "api": {
        "properties": {
          "service": {
            "properties": {
              "name": { "type": "keyword" }
            }
          }
        }
      },
      "unmapped": {
        "properties": {
          "additionalEventData": {
            "properties": {
              "CipherSuite": { "type": "keyword" }
            }
          }
        }
      }
    }
  }
}
```

**Sample Data**
```json
{
  "time": "2025-10-15T10:00:00Z",
  "api": {
    "service": {
      "name": "ServiceA"
    }
  },
  "unmapped": {
    "additionalEventData": {
      "CipherSuite": "TLS_AES_128_GCM_SHA256"
    }
  }
}
```

## Bug Description

**Issue Summary:**
After a JOIN operation, nested struct fields cannot be accessed in the `fields` command. Attempting to project specific nested fields (e.g., `api.service.name`, `unmapped.additionalEventData.CipherSuite`) results in a ClassCastException where `LinkedHashMap` cannot be cast to `ByteString`.

**Steps to Reproduce:**

1. Create test index:
```bash
curl -X PUT "http://localhost:9200/test-nested-join" -H 'Content-Type: application/json' -d'
{
  "mappings": {
    "properties": {
      "time": { "type": "date" },
      "api": {
        "properties": {
          "service": {
            "properties": {
              "name": { "type": "keyword" }
            }
          }
        }
      },
      "unmapped": {
        "properties": {
          "additionalEventData": {
            "properties": {
              "CipherSuite": { "type": "keyword" }
            }
          }
        }
      }
    }
  }
}'
```

2. Insert test data:
```bash
curl -X POST "http://localhost:9200/test-nested-join/_bulk" -H 'Content-Type: application/json' -d'
{"index":{}}
{"time":"2025-10-15T10:00:00Z","api":{"service":{"name":"ServiceA"}},"unmapped":{"additionalEventData":{"CipherSuite":"TLS_AES_128_GCM_SHA256"}}}
{"index":{}}
{"time":"2025-10-15T11:00:00Z","api":{"service":{"name":"ServiceB"}},"unmapped":{"additionalEventData":{"CipherSuite":"TLS_AES_256_GCM_SHA384"}}}
{"index":{}}
{"time":"2025-10-15T12:00:00Z","api":{"service":{"name":"ServiceC"}},"unmapped":{"additionalEventData":{"CipherSuite":"TLS_AES_128_GCM_SHA256"}}}
{"index":{}}
{"time":"2025-10-15T13:00:00Z","api":{"service":{"name":"ServiceD"}},"unmapped":{"additionalEventData":{"CipherSuite":"TLS_AES_256_GCM_SHA384"}}}
'

curl -X POST "http://localhost:9200/test-nested-join/_refresh"
```

3. Execute the failing query:
```bash
curl -X POST "http://localhost:9200/_plugins/_ppl" -H 'Content-Type: application/json' -d'
{
  "query": "source=test-nested-join | where ISPRESENT(unmapped.additionalEventData.CipherSuite) | eval copyCipher=unmapped.additionalEventData.CipherSuite | join type=inner left=ALL, right=CIPHER ON ALL.copyCipher = CIPHER.MostUsedCipher [ source=test-nested-join | rename unmapped.additionalEventData.CipherSuite as MostUsedCipher | where ISPRESENT(MostUsedCipher) | fields MostUsedCipher | top MostUsedCipher ] | fields time, api.service.name, unmapped.additionalEventData.CipherSuite"
}'
```

**Impact:**
Users cannot access nested struct fields in join results, forcing them to retrieve entire struct objects and parse them client-side.

## Tentative Root Cause

**This is a preliminary analysis and requires further investigation.**

The issue occurs in the result serialization/projection phase after join execution:

1. During join processing, struct fields are internally represented as `LinkedHashMap` objects
2. When the `fields` command attempts to project nested fields, it tries to access the nested path
3. The projection/serialization logic attempts to cast the struct to `ByteString`, which fails because it's a `LinkedHashMap`

The workaround (referencing entire structs) works because it serializes the complete `LinkedHashMap` without nested field access.

This appears to be in the result formatting layer where nested field access after joins is not properly handled, likely in the Calcite result serialization or the OpenSearch SQL response formatter.

## Workaround

Reference entire struct objects instead of nested fields:

```bash
curl -X POST "http://localhost:9200/_plugins/_ppl" -H 'Content-Type: application/json' -d'
{
  "query": "source=test-nested-join | where ISPRESENT(unmapped.additionalEventData.CipherSuite) | eval copyCipher=unmapped.additionalEventData.CipherSuite | join type=inner left=ALL, right=CIPHER ON ALL.copyCipher = CIPHER.MostUsedCipher [ source=test-nested-join | rename unmapped.additionalEventData.CipherSuite as MostUsedCipher | where ISPRESENT(MostUsedCipher) | fields MostUsedCipher | top MostUsedCipher ] | fields time, api, unmapped"
}'
```

This returns the entire struct, which can be parsed client-side to extract desired nested fields.

## Environment Information

**OpenSearch Version:** 3.4.0-SNAPSHOT
**SQL Plugin Version:** 3.4.0.0-SNAPSHOT

## Related Issues

- #52 - Nested field query improvement (general tracking issue for nested field limitations including joins)

### PR DESCRIPTION
**Pull request by LantaoJin**
### Description
Fix the issue that struct/nested field cannot be accessed after join (or other bi-operator):
```
{
  "mappings": {
    "properties": {
      "time": { "type": "date" },
      "a": {
        "properties": {
          "b": {
            "properties": {
              "c": { "type": "keyword" }
            }
          }
        }
      },
      "d": {
        "properties": {
          "e": {
            "properties": {
              "f": { "type": "keyword" }
            }
          }
        }
      }
    }
  }
}
```
For query
```
source=test | join type=inner left=l, right=r ON l.time = r.time test
| fields a.b.c
```
its AST tree is
```
plan=Project(projectList=[AllFields()]
	child=[Join(
		left=SubqueryAlias(alias=l, 
			child=[Project(projectList=[AllFieldsExcludeMeta()]
				child=[Relation(tableNames=[test])])])]),
		right=SubqueryAlias(alias=r, 
			child=[Project(projectList=[AllFieldsExcludeMeta()]
				child=[Relation(tableNames=[test])])])])])
```

Current `visitProject()` **mistakenly removes nested fields** in handling `AllFieldsExcludeMeta`, which cause no `a.b.c` fields in join's children. So `a.b.c` cannot be accessed after join.

### Related Issues
Resolves #4575 

### Check List
- [x] New functionality includes testing.
- [ ] New functionality has been documented.
 - [ ] New functionality has javadoc added.
 - [ ] New functionality has a user manual doc added.
- [ ] New PPL command [checklist](https://github.com/opensearch-project/sql/blob/main/docs/dev/ppl-commands.md) all confirmed.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff` or `-s`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: core/src/main/java/org/opensearch/sql/calcite/QualifiedNameResolver.java [hunk 1]
```diff
@@ -65,6 +65,7 @@ private static RexNode resolveInNonJoinCondition(
     log.debug("resolveInNonJoinCondition() called with nameNode={}", nameNode);
 
     return resolveLambdaVariable(nameNode, context)
+        .or(() -> resolveFieldDirectly(nameNode, context, 1))
```
Comment (LantaoJin) [inline core/src/main/java/org/opensearch/sql/calcite/QualifiedNameResolver.java:68]: This code isn't for fixing the current issue, just a small enhancement for which name parts great than 1.

Comment (yuancu) [reply core/src/main/java/org/opensearch/sql/calcite/QualifiedNameResolver.java]: Is there a test that covers this case?
