### PR TITLE
Bug Fix: Enable legacy settings in new setting action

### LINKED ISSUE #96: [BUG] Legacy settings are rejected by RestQuerySettingAction
**Describe the bug**

**To Reproduce**
Send request from OpenSearch Dashboards dev tools:
```
PUT _plugins/_query/settings
{
  "transient" : {
    "opendistro.sql.enabled" : "true"
  }
}
```

Got error:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "action_request_validation_exception",
        "reason" : "Validation Failed: 1: no settings to update;"
      }
    ],
    "type" : "action_request_validation_exception",
    "reason" : "Validation Failed: 1: no settings to update;"
  },
  "status" : 400
}
```

**Expected behavior**
Setting should be able to update with either legacy setting `opendistro.sql.*`, `opendistro.ppl.*`, `opendistro.query.*` or the new setting `plugins.sql.*`, `plugins.ppl.*`, `plugins.query.*`

**Plugins**
Please list all plugins currently enabled.
SQL

**Host/Environment (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Version [e.g. 22] Catalina

**Additional context**

### PR DESCRIPTION
**Pull request by chloe-zh**
Signed-off-by: Chloe Zhang <chloezh1102@gmail.com>

### Description
Example 1:
```
PUT _opendistro/_sql/settings
{
  "transient" : {
    "opendistro.sql.enabled" : "false"
  }
}
```
Response:
```
#! Deprecation: [opendistro.ppl.enabled] setting was deprecated in OpenSearch and will be removed in a future release! See the breaking changes documentation for the next major version.
#! Deprecation: [opendistro.sql.enabled] setting was deprecated in OpenSearch and will be removed in a future release! See the breaking changes documentation for the next major version.
#! Deprecation: [PUT /_opendistro/_sql/settings] is deprecated! Use [PUT /_plugins/_query/settings] instead.
{
  "acknowledged" : true,
  "persistent" : { },
  "transient" : {
    "opendistro" : {
      "sql" : {
        "enabled" : "false"
      }
    }
  }
}
```
Example 2:
```
PUT _plugins/_query/settings
{
  "transient" : {
    "opendistro.ppl.enabled" : "false"
  }
}
```
Response:
```
#! Deprecation: [opendistro.sql.enabled] setting was deprecated in OpenSearch and will be removed in a future release! See the breaking changes documentation for the next major version.
#! Deprecation: [opendistro.ppl.enabled] setting was deprecated in OpenSearch and will be removed in a future release! See the breaking changes documentation for the next major version.
{
  "acknowledged" : true,
  "persistent" : { },
  "transient" : {
    "opendistro" : {
      "ppl" : {
        "enabled" : "false"
      }
    }
  }
}
```
 
### Issues Resolved
#96 
 
### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: plugin/src/main/java/org/opensearch/sql/plugin/rest/RestQuerySettingsAction.java [hunk 1]
```diff
@@ -44,8 +44,12 @@
   private static final String SQL_SETTINGS_PREFIX = "plugins.sql.";
   private static final String PPL_SETTINGS_PREFIX = "plugins.ppl.";
   private static final String COMMON_SETTINGS_PREFIX = "plugins.query.";
+  private static final String LEGACY_SQL_SETTINGS_PREFIX = "opendistro.sql.";
+  private static final String LEGACY_PPL_SETTINGS_PREFIX = "opendistro.ppl.";
+  private static final String LEGACY_COMMON_SETTINGS_PREFIX = "opendistro.query.";
```
Comment (dai-chen) [inline plugin/src/main/java/org/opensearch/sql/plugin/rest/RestQuerySettingsAction.java:49]: Is this not needed? Because previously there was no setting name prefixed with `opendistro.query`?

Comment (chloe-zh) [reply plugin/src/main/java/org/opensearch/sql/plugin/rest/RestQuerySettingsAction.java:49]: `opendistro.query.size_limit`

Comment (dai-chen) [reply plugin/src/main/java/org/opensearch/sql/plugin/rest/RestQuerySettingsAction.java:49]: Got it. Thanks!

**Review by dai-chen — APPROVED** [review]
Thanks for the fix!

**Review by penghuo — APPROVED** [review]
Thanks for the change!
