### PR TITLE
[BugFix] Fix multiple appendpipe error while revisiting parent AST

### LINKED ISSUE #5173: [BUG] Double appendpipe causes 'different planner' assertion due to AST re-visitation
## Query Information
**PPL Command/Query:**
```ppl
source=bounty-numbers | appendpipe [stats avg(value) as avg_val] | appendpipe [stats max(value) as max_val]
```
**Expected Result:**
Query should execute and return appended aggregation output without planner failure.

**Actual Result:**
HTTP 400 assertion error:
`Relational expression ... belongs to a different planner than is currently being used.`

## Dataset Information
**Dataset/Schema Type**
- [ ] OpenTelemetry (OTEL)
- [ ] Simple Schema for Observability (SS4O)
- [ ] Open Cybersecurity Schema Framework (OCSF)
- [x] Custom (details below)

**Index Mapping**
```json
{
  "mappings": {
    "properties": {
      "count": { "type": "integer" },
      "category": { "type": "keyword" },
      "subcategory": { "type": "keyword" },
      "value": { "type": "double" },
      "ts": { "type": "date" }
    }
  }
}
```
**Sample Data**
```json
[
  { "count": 1, "category": "A", "subcategory": "X", "value": 10.5, "ts": "2024-01-01" },
  { "count": 2, "category": "A", "subcategory": "Y", "value": 20.3, "ts": "2024-01-02" },
  { "count": 10, "category": "B", "subcategory": "X", "value": 100.0, "ts": "2024-01-03" }
]
```

## Bug Description
**Issue Summary:**
Chained `appendpipe` triggers planner mismatch assertion.

**Steps to Reproduce:**
1. Create index and insert sample rows.
2. Run the query above.
3. Observe HTTP 400 assertion about different planner.

**Impact:**
Multi-stage appendpipe transformations fail and break query pipelines.

### PR DESCRIPTION
**Pull request by songkant-aws**
### Description
Chained appendpipe queries can produce literal-only projections during prepare-time field trimming. Calcite may simplify those projections into Values, which can trigger planner mismatch assertions during execution. Preserve the Project shape for this narrow case in OpenSearchRelFieldTrimmer.

### Related Issues
Resolves #5173 

### Check List
- [x] New functionality includes testing.
- [ ] New functionality has been documented.
 - [ ] New functionality has javadoc added.
 - [ ] New functionality has a user manual doc added.
- [ ] New PPL command [checklist](https://github.com/opensearch-project/sql/blob/main/docs/dev/ppl-commands.md) all confirmed.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff` or `-s`.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: core/src/main/java/org/opensearch/sql/calcite/utils/OpenSearchRelFieldTrimmer.java [hunk 1]
```diff
@@ -30,9 +40,94 @@
...
+        RelOptUtil.permute(project.getCluster().getTypeFactory(), rowType, mapping);
+
+    if (shouldAvoidSimplifyValues(newProjects, newInput)) {
+      return result(
+          project.copy(project.getTraitSet(), newInput, newProjects, newRowType), mapping, project);
+    }
+
+    openSearchRelBuilder.push(newInput);
+    openSearchRelBuilder.project(newProjects, newRowType.getFieldNames(), false, correlationIds);
+    return result(openSearchRelBuilder.build(), mapping, project);
```
Comment (songkant-aws) [inline core/src/main/java/org/opensearch/sql/calcite/utils/OpenSearchRelFieldTrimmer.java]: In trimFields(Project, ...), the old openSearchRelBuilder.project(...) call could trigger Calcite's internal simplifyValues() when trimming produced a literal-only projection over a fixed-row-count input. That rewrite could replace the Project with Values, which is the shape that led to the planner mismatch in chained appendpipe.

**Review by LantaoJin — DISMISSED** [review]

**Comment by qianheng-aws** [comment]
As discussed offline, it's root cause is inconsistent planner/cluster are being used in trim phase and optimize phase.

In original calcite, one prepare statement will be used through the whole process. While in PPL, we create 2 different prepares for analyzing and executing(including trimming, optimizing and planning, only trimming uses the planner from this new created prepare while others reuse the planner in RelNode).

The ideal solution should be reusing the same planner for trimming as well.

**Comment by songkant-aws** [comment]
@qianheng-aws As suggested, prepare-time trimming now reuses the incoming RelNode's cluster so it stays aligned with the analyzed plan. The change also preserves pre-registered hint strategies required by PPL custom aggregate hints. If we find other prepare-time state that also needs to stay aligned with the incoming RelNode, we can address those cases incrementally.

**Review by qianheng-aws — APPROVED** [review]

**Comment by qianheng-aws** [comment]
LGTM

**Review by LantaoJin — APPROVED** [review]

**Comment by LantaoJin** [comment]
@songkant-aws the multiple `LogicalUnion`s could be optimized as discussed offline?

**Comment by songkant-aws** [comment]
@LantaoJin I checked Calcite already has some optimization rules for multiple LogicalUnions. Sometimes it can merge multiple unions into one.
