### PR TITLE
Filter expression with `OR isnull(x)` should be pushed down

### LINKED ISSUE #4046: [BUG] Pushdown not work with expression `OR isnull(x)`
**What is the bug?**
Pushdown not work with expression `OR isnull(x)`
```
POST /_plugins/_ppl/_explain
{
  "query": """
source=account | where firstname = 'Amber' or isnull(gender)
  """
}
```

returns

```
{
  "calcite": {
    "logical": """LogicalSystemLimit(fetch=[10000], type=[QUERY_SIZE_LIMIT])
  LogicalProject(account_number=[$0], firstname=[$1], address=[$2], balance=[$3], gender=[$4], city=[$5], employer=[$6], state=[$7], age=[$8], email=[$9], lastname=[$10])
    LogicalFilter(condition=[OR(=($1, 'Amber'), IS NULL($4))])
      CalciteLogicalIndexScan(table=[[OpenSearch, account]])
""",
    "physical": """EnumerableLimit(fetch=[10000])
  EnumerableCalc(expr#0..10=[{inputs}], expr#11=['Amber':VARCHAR], expr#12=[=($t1, $t11)], expr#13=[IS NULL($t4)], expr#14=[OR($t12, $t13)], proj#0..10=[{exprs}], $condition=[$t14])
    CalciteEnumerableIndexScan(table=[[OpenSearch, account]], PushDownContext=[[PROJECT->[account_number, firstname, address, balance, gender, city, employer, state, age, email, lastname]], OpenSearchRequestBuilder(sourceBuilder={"from":0,"timeout":"1m","_source":{"includes":["account_number","firstname","address","balance","gender","city","employer","state","age","email","lastname"],"excludes":[]}}, requestedTotalSize=2147483647, pageSize=null, startFrom=0)])
"""
  }
}
```
which the predicate pushdown does not work.

### PR DESCRIPTION
**Pull request by LantaoJin**
### Description
Filter expression with `OR isnull(x)` should be pushed down in Calcite engine
Example:
```
| where firstname = 'Amber' or isnull(gender)
```
Should be pushed down to
```
  "query": {
    "bool": {
      "should": [
        {
          "bool": {
            "must_not": [
              {
                "exists": {
                  "field": "gender",
                  "boost": 1
                }
              }
            ],
            "adjust_pure_negative": true,
            "boost": 1
          }
        },
        {
          "term": {
            "firstname.keyword": {
              "value": "Amber",
              "boost": 1
            }
          }
        }
      ],
      "adjust_pure_negative": true,
      "boost": 1
    }
  }
```
### Related Issues
Resolves #4046 

### Check List
- [x] New functionality includes testing.
- [ ] New functionality has been documented.
 - [ ] New functionality has javadoc added.
 - [ ] New functionality has a user manual doc added.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: opensearch/src/main/java/org/opensearch/sql/opensearch/request/PredicateAnalyzer.java [hunk 1]
```diff
@@ -634,13 +634,20 @@ private static QueryExpression constructQueryExpressionForSearch(
...
     }
 
+    private boolean containIsEmptyFunction(RexCall call) {
+      return call.getKind() == SqlKind.OR
+          && call.getOperands().stream().anyMatch(o -> o.getKind() == SqlKind.IS_NULL)
+          && call.getOperands().stream()
+              .anyMatch(
+                  o ->
+                      o.getKind() == SqlKind.OTHER
+                          && ((RexCall) o).getOperator().equals(SqlStdOperatorTable.IS_EMPTY));
```
Comment (qianheng-aws) [inline opensearch/src/main/java/org/opensearch/sql/opensearch/request/PredicateAnalyzer.java:643]: Shall we check other functions as well? e.g. `LENGTH`

**Review by qianheng-aws — APPROVED** [review]

File: opensearch/src/main/java/org/opensearch/sql/opensearch/request/PredicateAnalyzer.java (hunk 1 above)
Comment (qianheng-aws) [reply opensearch/src/main/java/org/opensearch/sql/opensearch/request/PredicateAnalyzer.java:643]: Function LENGTH support accepting NULL as its arguments. No need to change.

**Review by penghuo — APPROVED** [review]
