### PR TITLE
Fix `ClassCastException` for value-storing aggregates on nested PPL fields

### LINKED ISSUE #4359: [BUG] ClassCastException for value-storing aggregates on nested PPL fields
**What is the bug?**
Value-storing aggregate functions (`first()`, `last()`, `min()`, `max()`, etc.) throw a `ClassCastException` when their argument is a deeply nested field accessed via dotted path wrapped in backticks (e.g., `resource.attributes.telemetry.sdk.language`). Calculation-only aggregates (`count()`, `dc()`, `sum()`, `avg()`) work as expected.

---

**How can one reproduce the bug?**

1. Use an index matching `logs-otel-v1*` (or any index with similar nested object structure shown below).
2. In PPL, run one of the following (value-storing aggregates with nested fields):

   ```spl
   source=logs-otel-v1* | stats first(`resource.attributes.telemetry.sdk.language`) by severityNumber
   source=logs-otel-v1* | stats last(`resource.attributes.telemetry.sdk.language`) by severityNumber
   source=logs-otel-v1* | stats min(`resource.attributes.telemetry.sdk.language`) by severityNumber
   source=logs-otel-v1* | stats max(`resource.attributes.telemetry.sdk.language`) by severityNumber
   ```
3. Observe a 500 with `ClassCastException` in the response.
4. Compare with working queries:

   ```spl
   -- calculation-only aggregates on the same nested path
   source=logs-otel-v1* | stats count(`resource.attributes.telemetry.sdk.language`) by severityNumber
   source=logs-otel-v1* | stats dc(`resource.attributes.telemetry.sdk.language`) by severityNumber
   -- simple fields work for all aggregates
   source=logs-otel-v1* | stats first(severityNumber)
   source=logs-otel-v1* | stats last(severityNumber)
   source=logs-otel-v1* | stats min(severityNumber)
   source=logs-otel-v1* | stats max(severityNumber)
   ```

---

**What is the expected behavior?**

* `first()`/`last()` return the first/last non-null value of the nested field (e.g., `"java"`).
* `min()`/`max()` return the lexicographic min/max for keyword fields on the nested path.
* All value-storing aggregates should accept nested dotted paths the same as simple fields—without throwing.

---

**What is your host/environment?**

* **Environment:** \[explore env]
* **Index Pattern:** `logs-otel-v1*` (or similar)
* **Plugins:** OpenSearch SQL (PPL)

**Do you have any additional context?**

**Actual error response**

```json
{
  "error": {
    "reason": "There was internal problem at backend",
    "details": "class java.util.HashMap cannot be cast to class java.lang.String (java.util.HashMap and java.lang.String are in module java.base of loader 'bootstrap')",
    "type": "ClassCastException"
  },
  "status": 500
}
```

**Function classification**

* **Affected (value-storing):** `first()`, `last()`, `min()`, `max()`, and any aggregate that returns the field value itself.
* **Unaffected (calculation-only):** `count()`, `dc()`, `sum()`, `avg()`.

### PR DESCRIPTION
**Pull request by ahkcs**
## Summary

Value-storing aggregate functions (`first`, `last`, `min`, `max`) failed with a `ClassCastException` when targeting deeply nested field paths such as `resource.attributes.telemetry.sdk.language`.
This PR fixes nested-field value extraction in OpenSearch SQL by handling `Map`/`HashMap` objects that represent nested structures, eliminating the unsafe cast and restoring expected behavior for value-storing aggregates.

---

## Problem

These queries previously failed with `ClassCastException` for value-storing aggregates:

```spl
source=logs-otel-v1* | stats first(`resource.attributes.telemetry.sdk.language`) by severityNumber
source=logs-otel-v1* | stats last(`resource.attributes.telemetry.sdk.language`) by severityNumber
source=logs-otel-v1* | stats min(`resource.attributes.telemetry.sdk.name`) by severityNumber
source=logs-otel-v1* | stats max(`resource.attributes.telemetry.sdk.name`) by severityNumber
```

While simple fields worked:

```spl
source=logs-otel-v1* | stats first(severityNumber)
```

> Note: Calculation-only aggregates like `count()` and `dc()` were unaffected because they don’t store field values.

Observed error:

```json
{
  "error": {
    "reason": "There was internal problem at backend",
    "details": "class java.util.HashMap cannot be cast to class java.lang.String",
    "type": "ClassCastException"
  }
}
```

---

## Root Cause

Execution-path analysis showed the failure at the final type-conversion layer in value-storing aggregates:

1. **Field resolution** returned partial `Map` structures (e.g., `{attributes={telemetry={sdk={language=java}}}}`) instead of the terminal primitive (`"java"`).
2. **Aggregates** (`first`, `last`, `min`, `max`) stored these `Map` objects in their accumulators.
3. **Type conversion** later attempted `(String) value` in `ObjectContent.stringValue()` where `value` was a `Map`.

Why calculation-only aggregates work: functions like `count()` and `dc()` perform calculations without storing the actual field values, so they never hit this conversion path.

---

## Solution

Implement nested-map handling in `ObjectContent.stringValue()` so value-storing aggregate outputs can be safely converted to strings.

**Key changes**

* Detect `Map` values and recursively extract the terminal primitive via `extractFinalPrimitiveValue(...)`.
* Preserve existing behavior for non-`Map` values (backward compatible).

**Before**

```java
return (String) value;  // throws ClassCastException if value is a Map
```

**After**

```java
if (value instanceof Map) {
  Map<String, Object> map = (Map<String, Object>) value;
  Object finalValue = extractFinalPrimitiveValue(map); // drills down single-value maps
  if (finalValue != null && !(finalValue instanceof Map)) {
    return finalValue.toString();
  }
  return map.toString();
}
return (String) value;
```

**Example extraction**
Input: `{attributes={telemetry={sdk={language=java}}}}`
→ `{telemetry={sdk={language=java}}}`
→ `{sdk={language=java}}`
→ `{language=java}`
→ `"java"`

---

## Verification (now succeeds)

```spl
source=logs-otel-v1* | stats first(`resource.attributes.telemetry.sdk.language`) by severityNumber
source=logs-otel-v1* | stats last(`resource.attributes.telemetry.sdk.language`) by severityNumber
source=logs-otel-v1* | stats min(`resource.attributes.telemetry.sdk.language`) by severityNumber
source=logs-otel-v1* | stats max(`resource.attributes.telemetry.sdk.language`) by severityNumber
```

## Resolves

* Resolves #4359

### CODE REVIEW

File: integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLAggregationIT.java [hunk 1]
```diff
@@ -1246,4 +1248,112 @@ public void testLimitAfterAggregation() throws IOException {
...
+  @Test
+  public void testMinMaxMultipleNestedFields() throws IOException {
+    // Test min/max with multiple nested field aggregations in one query
+    JSONObject actual =
+        executeQuery(
+            String.format(
+                "source=%s | stats min(`resource.attributes.telemetry.sdk.language`) as min_lang,"
+                    + " max(`resource.attributes.telemetry.sdk.language`) as max_lang",
+                TEST_INDEX_TELEMETRY));
+    verifySchema(actual, schema("min_lang", "string"), schema("max_lang", "string"));
```
Comment (LantaoJin) [inline integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLAggregationIT.java:1356]: What if the type of nested `language` is an integer, can the ppl work?

Comment (ahkcs) [reply integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLAggregationIT.java:1356]: Yes, in ObjectContent.java, first the `extractFinalPrimitiveValue` method will extract the value as Object and then we'll add toString() to it.

Comment (LantaoJin) [reply integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLAggregationIT.java:1356]: No I mean what if the mapping contains 
```
                    "properties": {
                      "version": {
                        "type": "integer"
                      }
```
and query with `` | stats min(`resource.attributes.telemetry.sdk.version`) ``.
Can you update the mapping and data, and test above query?

Comment (ahkcs) [reply integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLAggregationIT.java:1356]: Changed the approach - moved the fix from ObjectContent.java to OpenSearchExprValueFactory.construct() for better universal handling. Updated the telemetry mapping to test for types like integer and boolean

File: opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java [hunk 2]
```diff
@@ -526,4 +527,26 @@ private ExprValue parseInnerArrayValue(
...
+  @SuppressWarnings("unchecked")
+  private Object extractFinalPrimitiveValue(Object value) {
+    if (value == null || !(value instanceof Map)) {
+      return value;
+    }
+
+    Map<String, Object> map = (Map<String, Object>) value;
+    if (map.size() == 1) {
+      Object singleValue = map.values().iterator().next();
+      return extractFinalPrimitiveValue(singleValue);
```
Comment (Swiddis) [inline opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java:547]: Is there risk of a RecursionError here?

If this is only loaded from an index, it's maybe fine (I think you can't index massively nested structures, not sure). But if there's a path where this is executed on user input, it'd be very easy to cause a crash with this.

File: opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java [hunk 3]
```diff
@@ -526,4 +527,26 @@ private ExprValue parseInnerArrayValue(
...
+   * @param value The value to extract from
+   * @return The extracted primitive value, or the original value if extraction is not possible
+   */
+  @SuppressWarnings("unchecked")
+  private Object extractFinalPrimitiveValue(Object value) {
+    if (value == null || !(value instanceof Map)) {
+      return value;
+    }
+
+    Map<String, Object> map = (Map<String, Object>) value;
```
Comment (Swiddis) [inline opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java:544]: Why do this cast at runtime instead of just specifying the type in the signature and pushing the check to the left?

**Review by Swiddis — APPROVED** [review]

**Review by LantaoJin — APPROVED** [review]
LGTM if the CI rerun passed.

**Comment by LantaoJin** [comment]
@ahkcs please manually backport it, thanks
