### PR TITLE
Fix the aggregation filter missing in named aggregators

### LINKED ISSUE #122: [BUG] Aggregation with filter loses filtering when the aggregate is not pushed down
**Describe the bug**
The aggregator properties are missing after analyzing because the analyzer wraps the aggregator to the delegated aggregator of `NamedAggregator` without inheriting the properties to the wrapper (Named Aggregator). 

**To Reproduce**

Sample data:
```
PUT accounts/_bulk
{"index":{"_id":"1"}}
{"account_number":1,"balance":39225,"firstname":"Amber","lastname":"Duke","age":32,"gender":"M","address":"880 Holmes Lane","employer":"Pyrami","email":"amberduke@pyrami.com","city":"Brogan","state":"IL"}
{"index":{"_id":"6"}}
{"account_number":6,"balance":5686,"firstname":"Hattie","lastname":"Bond","age":36,"gender":"M","address":"671 Bristol Street","employer":"Netagy","email":"hattiebond@netagy.com","city":"Dante","state":"TN"}
{"index":{"_id":"13"}}
{"account_number":13,"balance":32838,"firstname":"Nanette","lastname":"Bates","age":28,"gender":"F","address":"789 Madison Street","employer":"Quility","email":"nanettebates@quility.com","city":"Nogal","state":"VA"}
{"index":{"_id":"18"}}
{"account_number":18,"balance":4180,"firstname":"Dale","lastname":"Adams","age":33,"gender":"M","address":"467 Hutchinson Court","email":"daleadams@boink.com","city":"Orick","state":"MD"}
```

Example of bug:
```
select count(*) filter(where age > 30) from (select * from accounts) as a

Result:
{
  "schema": [
    {
      "name": """count(*) filter(where age > 30)""",
      "type": "integer"
    }
  ],
  "datarows": [
    [
      4
    ]
  ],
  "total": 1,
  "size": 1,
  "status": 200
}

Explain:
{
  "root": {
    "name": "ProjectOperator",
    "description": {
      "fields": """[count(*) filter(where age > 30)]"""
    },
    "children": [
      {
        "name": "AggregationOperator",
        "description": {
          "aggregators": """[count(*) filter(where age > 30)]""",
          "groupBy": "[]"
        },
        "children": [
          {
            "name": "ProjectOperator",
            "description": {
              "fields": "[account_number, firstname, address, balance, gender, city, employer, state, age, email, lastname]"
            },
            "children": [
              {
                "name": "OpenSearchIndexScan",
                "description": {
                  "request": """OpenSearchQueryRequest(indexName=accounts, sourceBuilder={"from":0,"size":200,"timeout":"1m","_source":{"includes":["account_number","firstname","address","gender","balance","city","employer","state","age","email","lastname"],"excludes":[]}}, searchDone=false)"""
                },
                "children": []
              }
            ]
          }
        ]
      }
    ]
  }
}
```

Example working as expected:
```
select count(*) filter(where age > 30) from accounts

Result:
{
  "schema": [
    {
      "name": """count(*) filter(where age > 30)""",
      "type": "integer"
    }
  ],
  "datarows": [
    [
      3
    ]
  ],
  "total": 1,
  "size": 1,
  "status": 200
}

Explain:
{
  "root": {
    "name": "ProjectOperator",
    "description": {
      "fields": """[count(*) filter(where age > 30)]"""
    },
    "children": [
      {
        "name": "OpenSearchIndexScan",
        "description": {
          "request": """OpenSearchQueryRequest(indexName=accounts, sourceBuilder={"from":0,"size":0,"timeout":"1m","aggregations":{"count(*) filter(where age > 30)":{"filter":{"range":{"age":{"from":30,"to":null,"include_lower":false,"include_upper":true,"boost":1.0}}},"aggregations":{"count(*) filter(where age > 30)":{"value_count":{"field":"_index"}}}}}}, searchDone=false)"""
        },
        "children": []
      }
    ]
  }
}

```

**Plugins**
SQL

**Host/Environment (please complete the following information):**
 - OS: MacOS
 - Version: Catalina 10.15.7

### PR DESCRIPTION
**Pull request by chloe-zh**
Signed-off-by: Chloe Zhang <chloezh1102@gmail.com>

### Description
When create `NamedAggregator` instance, let the instance take the properties (currently only the `condition` expression) from the delegated aggregator to avoid the errors that come from aggregator property inconsistency.

Comparison test failed, added IT test in `AggregationIT.java` instead.
 
### Issues Resolved
#122 
 
### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: core/src/main/java/org/opensearch/sql/expression/aggregation/NamedAggregator.java [hunk 1]
```diff
@@ -64,6 +66,7 @@ public NamedAggregator(
     super(delegated.getFunctionName(), delegated.getArguments(), delegated.returnType);
     this.name = name;
     this.delegated = delegated;
+    this.condition = delegated.condition != null ? delegated.condition : null;
```
Comment (dai-chen) [inline core/src/main/java/org/opensearch/sql/expression/aggregation/NamedAggregator.java:69]: Is this same as `this.condition = delegate.condition`? Or you actually wanted to check if `delegated` is null?

**Review by dai-chen — APPROVED** [review]
Thanks for the fix!

File: core/src/main/java/org/opensearch/sql/expression/aggregation/NamedAggregator.java (hunk 1 above)
Comment (chloe-zh) [reply core/src/main/java/org/opensearch/sql/expression/aggregation/NamedAggregator.java:69]: It should be the same with `this.condition = delegate.condition`. Thanks!

**Review by penghuo — APPROVED** [review]
