### PR TITLE
Replace non-ASCII characters in code and docs.

### LINKED ISSUE #1364: [AUTOCUT] OS Distribution Build Failed for sql-2.6.0
***Received Error***: **Error building sql, retry with: ./build.sh manifests/2.6.0/opensearch-2.6.0.yml --component sql --snapshot**.
                      The distribution build for sql has failed.
                      Please see build log at https://build.ci.opensearch.org/job/distribution-build-opensearch/7115/consoleFull

### PR DESCRIPTION
**Pull request by Yury-Fridlyand**
### Description
Replace non-ASCII characters in code and docs.
Characters left:
```
DEVELOPER_GUIDE.rst:132:   │   ├── attributions.md
DEVELOPER_GUIDE.rst:133:   │   ├── category.json
DEVELOPER_GUIDE.rst:134:   │   ├── dev
DEVELOPER_GUIDE.rst:135:   │   └── user
```
and `°` (temperature degree symbol) in IT sample data:
```
integ-test/src/test/resources/beer.stackexchange.json:26
integ-test/src/test/resources/beer.stackexchange.json:60
```

**UPD**
Removed all non-English comments from legacy engine

### Issues Resolved
Fixes #1364
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: common/src/test/java/org/opensearch/sql/common/grok/BasicTest.java [hunk 1]
```diff
@@ -113,22 +113,22 @@ public void test006_testLoadPatternFromFileIso_8859_1() throws IOException, Grok
...
     compiler.register(new FileInputStream(temp), StandardCharsets.ISO_8859_1);
     Grok grok = compiler.compile("%{TEST}");
-    assertEquals("(?<name0>§)", grok.getNamedRegex());
+    assertEquals("(?<name0>#)", grok.getNamedRegex());
   }
 
   @Test
   public void test007_testLoadPatternFromReader() throws IOException, GrokException {
-    Reader reader = new StringReader("TEST €");
+    Reader reader = new StringReader("TEST $");
```
Comment (MaxKsyunz) [inline common/src/test/java/org/opensearch/sql/common/grok/BasicTest.java:127]: This is changing the nature of the test. The test specifically uses non-ascii characters.

It's best to use unicode escape [sequence](https://www.javatpoint.com/java-escape-characters) here.

File: common/src/test/java/org/opensearch/sql/common/grok/BasicTest.java [hunk 2]
```diff
@@ -113,22 +113,22 @@ public void test006_testLoadPatternFromFileIso_8859_1() throws IOException, Grok
     try (FileOutputStream fis = new FileOutputStream(temp);
          BufferedWriter bw = new BufferedWriter(
              new OutputStreamWriter(fis, StandardCharsets.ISO_8859_1))) {
-      bw.write("TEST §");
+      bw.write("TEST #");
```
[the remark this answers is not in the document]
Comment (Yury-Fridlyand) [reply common/src/test/java/org/opensearch/sql/common/grok/BasicTest.java]: Thanks, fixed in 55182bf31.

File: common/src/test/java/org/opensearch/sql/common/grok/BasicTest.java (hunk 1 above)
Comment (Yury-Fridlyand) [reply common/src/test/java/org/opensearch/sql/common/grok/BasicTest.java]: Thanks, fixed in 55182bf31.

**Review by MaxKsyunz — APPROVED** [review]

**Comment by Yury-Fridlyand** [comment]
Rebased

**Review by MaxKsyunz — APPROVED** [review]

**Review by dai-chen — APPROVED** [review]
Thanks for the fix!

**Comment by dai-chen** [comment]
may need to merge main to fix BWC test?

**Comment by Yury-Fridlyand** [comment]
> may need to merge main to fix BWC test?

I think this doesn't help. BWC in GHA environment runs on Linux and it is not sensitive for Unicode characters. Jenkins CI runs on Windows and fails.

**Review by acarbonetto — APPROVED** [review]

**Review by GabeFernandez310 — APPROVED** [review]
